### ISSUE TITLE
llvm: Depends on libxml2

### ISSUE THREAD

**Issue by dragonxlwang** [Linuxbrew/linuxbrew#1008]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

```sh
brew install llvm --with-clang
```
failes with fresh install of brew on Scientific Linux release 6.7 (Carbon)

here's the [log](https://gist.github.com/21431926f23f231c720720be491da9fb)

It reports
```
/home/xwang95/.linuxbrew/bin/ar: ../../libLLVMR600CodeGen.a: No space left on device
make[2]: *** [lib/libLLVMR600CodeGen.a] Error 1
make[2]: *** Deleting file `lib/libLLVMR600CodeGen.a'
make[2]: Leaving directory `/tmp/llvm20160330-27652-1evsf8t'
make[1]: *** [lib/Target/R600/CMakeFiles/LLVMR600CodeGen.dir/all] Error 2
collect2: error: ld returned 1 exit status
```

which I don't quite understand as it appears that on the system I still have plenty of space left (1.7T)

**Comment by sjackman** [comment]
It builds in a temporary directory `/tmp` by default, which may be full, as it's often configured as a small and fast RAM disk. Set the environment variable `HOMEBREW_TEMP`
```sh
mkdir ~/tmp
export HOMEBREW_TEMP=~/tmp
brew install llvm --with-clang
```

**Comment by dragonxlwang** [comment]
I tried the walkaround and it still fails.

This time the error seems related to LD:

```
/home/xwang95/.linuxbrew/bin/ld: cannot find -lxml2
collect2: error: ld returned 1 exit status
make[2]: *** [bin/c-index-test] Error 1
make[2]: Leaving directory `/home/xwang95/tmp/llvm20160330-19540-1rm3q3o'
make[1]: *** [tools/clang/tools/c-index-test/CMakeFiles/c-index-test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/xwang95/tmp/llvm20160330-19540-1rm3q3o'
```
And the [gist](https://gist.github.com/dragonxlwang/1b71836ea4f24f9dbd2893e77d108a10)

**Comment by sjackman** [comment]
Try `brew install xml2 llvm --with-clang`

**Comment by dragonxlwang** [comment]
however, it seems there is still something not set correctly:
```
$ brew install xml2
==> Downloading http://download.ofb.net/gale/xml2-0.5.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/home/xwang95/.linuxbrew/Cellar/xml2/0.5
Last 15 lines from /home/xwang95/.cache/Homebrew/Logs/xml2/01.configure:
checking for style of include used by make... GNU
checking dependency style of /home/xwang95/.linuxbrew/bin/gcc-5... gcc3
checking for pkg-config... /home/xwang95/.linuxbrew/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for XML... no
configure: error: Package requirements (libxml-2.0) were not met:

No package 'libxml-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XML_CFLAGS
and XML_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

```
$ sudo yum install libxml2
[sudo] password for xwang95:
Loaded plugins: kmdl, priorities, refresh-packagekit, security
Setting up Install Process
2411 packages excluded due to repository priority protections
Package libxml2-2.7.6-20.el6_7.1.x86_64 already installed and latest version
Nothing to do
```

**Comment by sjackman** [comment]
Sorry. That was a typo. It should have been
`brew install libxml2 llvm --with-clang`

**Comment by dragonxlwang** [comment]
@sjackman ,thanks! But I thought my distro has already libxml2 as shown above, dunno why brew still say it cannot find it anyhow.

**Comment by sjackman** [comment]
On OS distributions with `glibc` < 2.19, the default behaviour of Linuxbrew is not to use any libraries installed by the host OS, known as a Standalone Installation of Linuxbrew.
https://gist.github.com/dragonxlwang/21431926f23f231c720720be491da9fb#file-00-config-out-L13
`OS glibc: 2.12`

**Comment by dragonxlwang** [comment]
Thanks! but this seems to contradict with my memory when I was installing ycm last night where it report it has error thrown by my glibc under /lib64 (os lib)... as you instructed, I already have used ``brew sh`` but it seems when compiling cmake it persist to work with os libs... I will confirm this after  install the llvm

**Comment by dragonxlwang** [comment]
Yes, llvm --with-clang can be correctly installed! Thanks!

**Comment by sjackman** [comment]
Glad to hear it!
