### ISSUE TITLE
substitute linuxbrew glibc for os glibc

### ISSUE THREAD

**Issue by dragonxlwang** [Linuxbrew/linuxbrew#1011]
This is a followup issue regarding the glibc linking problem

I have successfully installed glibc. When compiling a c file I have
```
$ ldd glibc
        linux-vdso.so.1 (0x00007fff4b51d000)
        libc.so.6 => /home/xwang95/.linuxbrew/lib/libc.so.6 (0x00007fbb4c83e000)
        /home/xwang95/.linuxbrew/lib/ld.so (0x00007fbb4cbba000)
```

But when locating ``glibc.so.6`` I am seeing:

```sh
$ sudo ldconfig
$ locate libc.so.6
/lib/libc.so.6
/lib/i686/nosegneg/libc.so.6
/lib64/libc.so.6
```

Adding the path to $LD_LIBRARY_PATH seems causing more problem (segmentation problem after shell login)

Please let me know how to fix that in the rightway...

**Comment by sjackman** [comment]
```sh
sudo updatedb
locate libc.so.6
```

**Comment by dragonxlwang** [comment]
sorry that I should mention that I already give that a try before which doesn't make a change

**Comment by sjackman** [comment]
Perhaps `updatedb` probably isn't configured to index home directories.
Do you have issues other than the output of `locate` that you're trying to resolve? Based on the output of `ldd`, it looks like it's working.

**Comment by dragonxlwang** [comment]
Let me try my best to explain what's my problem looks like:

I need to compile you-complete-me on an old scientific linux 6 (linux 2.6.32), and it complains that the glibc too old --- that's why I resorted to linuxbrew. by using a standalone brew, specifically, libpython, libclang, glibc, I still get run time error from the compiled ycm --- it says that it still looking for old glibc in /lib64 directory ... 

Today I made a mistake. I tried to upgrade glibc using root by myself and ended up the whole system is messed up... I didn't realize that it's much more complicated to install than I thought... now I couldn't even ssh the server anymore. I am waiting our cs department staff to help me out ....

I will report back to you once the server rebooted from the linux CD...

**Comment by sjackman** [comment]
Down the rabbit hole! You could perhaps try creating a formula for `you-complete-me` and compiling it that way. Otherwise, check out `brew sh` and `brew diy`.

**Comment by dragonxlwang** [comment]
yeah, that might actually save lots of trouble and be good for others running on scilinux…

I think it’s time for me to contribute a little as well… Let me try it first :P

**Comment by DoomHammer** [comment]
Cannot say much about `brew diy` but tried `brew sh` with YCM on Tuesday and it works as advertised. You can see it in my [.vimrc](https://github.com/DoomHammer/dotfiles/blob/master/.vimrc#L8)

**Comment by dragonxlwang** [comment]
@DoomHammer  thanks! Can you please share what brew packages you installed instead of using the system ones?

**Comment by DoomHammer** [comment]
There are many of them, but the most important, I believe, would be `gcc --with-glibc` and `python`.

**Comment by dragonxlwang** [comment]
I think you are saying gcc & glibc? now gcc doesn't have --with-glibc option.

I have all of them. After compile ycm in ``brew sh`` environment, when running it, I still get:

```
import ycm_core ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/user/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_core.so)
```

I looked ycm_core.so:

```
ldd ycm_core.so
        linux-vdso.so.1 (0x00007ffc113b6000)
        libpython2.7.so.1.0 => /home/xwang95/.linuxbrew/lib/libpython2.7.so.1.0 (0x00007f249f0a9000)
        libclang.so.3.7 => /home/xwang95/.vim/bundle/YouCompleteMe/third_party/ycmd/./libclang.so.3.7 (0x00007f249caa4000)
        librt.so.1 => /home/xwang95/.linuxbrew/lib/librt.so.1 (0x00007f249c89b000)
        libstdc++.so.6 => /home/xwang95/.linuxbrew/lib/libstdc++.so.6 (0x00007f249c526000)
        libm.so.6 => /home/xwang95/.linuxbrew/lib/libm.so.6 (0x00007f249c234000)
        libgcc_s.so.1 => /home/xwang95/.linuxbrew/lib/libgcc_s.so.1 (0x00007f249c020000)
        libc.so.6 => /home/xwang95/.linuxbrew/lib/libc.so.6 (0x00007f249bca4000)
        libpthread.so.0 => /home/xwang95/.linuxbrew/lib/libpthread.so.0 (0x00007f249ba88000)
        libdl.so.2 => /home/xwang95/.linuxbrew/lib/libdl.so.2 (0x00007f249b884000)
        libutil.so.1 => /home/xwang95/.linuxbrew/lib/libutil.so.1 (0x00007f249b681000)
        /home/xwang95/.linuxbrew/Cellar/glibc/2.19/lib64/ld-linux-x86-64.so.2 (0x00007f249f894000)
```

Do you have any ideas?

**Comment by DoomHammer** [comment]
Maybe you have `LD_LIBRARY_PATH` set so it overrides Linuxbrew libs?

**Comment by sjackman** [comment]
Please report `brew config` and `brew doctor`

`platform.libc_ver()` may be reporting the version of libc found in `/lib` rather than the version against which it is linked.

**Comment by sjackman** [comment]
I can confirm that I also see
```
>>> import platform
>>> platform.libc_ver()
('glibc', '2.2.5')
```
but the system that I'm running on is `glibc 2.12` and Linuxbrew is `glibc 2.19`, so Python is out to lunch.

**Comment by dragonxlwang** [comment]
sure!
```
$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew
HEAD: 94df1009303a7c707c88bbce32ba4657a887c055
Last commit: 2 days ago
HOMEBREW_PREFIX: /home/xwang95/.linuxbrew
HOMEBREW_REPOSITORY: /home/xwang95/.linuxbrew
HOMEBREW_CELLAR: /home/xwang95/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 16-core 64-bit arrandale
Kernel: Linux 2.6.32-573.22.1.el6.x86_64 x86_64 GNU/Linux
OS: Scientific Linux release 6.7 (Carbon)
Codename: Carbon
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
Clang: 3.4 build 0
X11: 2.7.8 => /usr
System Ruby: 1.8.7-p374 => /usr/bin/ruby
Perl: /home/xwang95/.linuxbrew/bin/perl => /home/xwang95/.linuxbrew/Cellar/perl/5.22.1/bin/perl
Python: /home/xwang95/.linuxbrew/bin/python => /home/xwang95/.linuxbrew/Cellar/python/2.7.11/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.6.0_45
```

And this [gist](https://gist.github.com/anonymous/6efa9dcb6f0dccd2a7d2a1f3aac8e6e0) includes the doctor diagnose

**Comment by dragonxlwang** [comment]
@DoomHammer , can I ask did you run on your system's vim or brew's vim? Also, can you please let me know if you also have the glibc linked to system lib when running in python?

**Comment by DoomHammer** [comment]
I am running brewed Neovim.

```
Python 2.7.11 (default, Mar 19 2016, 11:05:53) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.libc_ver()
('glibc', '2.2.5')
```

Python is... special
