### ISSUE TITLE
brew cleanup => Bad file descriptor @ rb_file_flock

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/linuxbrew#1017]
I keep getting these errors when I attempt `brew cleanup`.

That `.cache` folder contains lots of `.brewing` files. Most are zero length, but a couple of them have an old version of a Formula.

Any ideas?

```
% brew cleanup
Warning: Skipping (old) /bio/linuxbrew/Cellar/capnp/0.5.2 due to it being linked
Warning: Skipping gtk+: most recent version 2.24.30 not installed
Warning: Skipping lua: most recent version 5.2.4_3 not installed
Warning: Skipping homebrew/science/snap-aligner: most recent version 0.15 not installed
Warning: Skipping homebrew/science/uproc: most recent version 1.1.2 not installed
Warning: Skipping (old) /bio/linuxbrew/Cellar/ncurses/6.0 due to it being linked
Warning: Skipping homebrew/science/daligner: most recent version 1.0 not installed
Warning: Skipping qt: most recent version 4.8.7_2 not installed
Warning: Skipping (old) /bio/linuxbrew/Cellar/pillow/2.7.0 due to it being linked
Warning: Skipping homebrew/science/seqan: most recent version 2.1.0 not installed
Warning: Skipping jemalloc: most recent version 4.0.0 not installed
Warning: Skipping poppler: most recent version 0.42.0 not installed
Warning: Skipping homebrew/science/kat: most recent version 1.0.7 not installed
Warning: Skipping (old) /bio/linuxbrew/Cellar/vt/0.577 due to it being linked
Warning: Skipping linux-headers: most recent version 3.18.27 not installed
Error: Bad file descriptor @ rb_file_flock - /home/tseemann/.cache/Homebrew/Formula/gmp.brewing
```

**Comment by sjackman** [comment]
Hmm. No, I haven't run into that error myself. Perhaps the file system that you're on doesn't support `flock`? I'm not sure why those `brewing` files stick around. Should they be deleted automatically?

**Comment by tseemann** [comment]
My brew is on an NFS mount (shared across nodes). 

There does seem to be a bit of noise of `flock()` problems on Ruby over NFS on modern Centos:
eg. https://github.com/rubygems/rubygems/issues/806

I'll remove all the files and see what happens.

**Comment by sjackman** [comment]
I've been using Linuxbrew on NFS as well. I haven't had any trouble, but I suspect it depends heavily on the NFS implementation on the server and client.

**Comment by sjackman** [comment]
Do post here if you find a resolution.
