### ISSUE TITLE
how to add linuxbrew permanantly to my .bashrc or .zshrc

### ISSUE THREAD

**Issue by ahmedmagds** [Linuxbrew/linuxbrew#1030]
Each time I close my terminal from my Vitual box biolinux 8, I have to write these commands again
```
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
```
Is there a way not to do that each time?

**Comment by tseemann** [comment]
Put them in your `$HOME/.bash_profile` file.

Things in there will be run for every shell you start.
