### ISSUE TITLE
Create a :tcl requirement

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#1034]
Spun off from #1019 to address the problem of depending on `tcl-tk` without Tk support.

The plan is as follows (quoting from @sjackman): 
> create a :tcl Requirement that installs tcl-tk --without-tk by default but is satisfied by any installation of tcl-tk, including possibly the host's.

IMO, this should be a requirement in its own file so that other formulae beyond just `postgres` can use it.

**Comment by sjackman** [comment]
> this should be a requirement in its own file so that other formulae beyond just postgres can use it.

Agreed.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/brew#7
