### ISSUE TITLE
Create list of core Perl and Python modules for brew doctor

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/linuxbrew#1038]
There's a few core Perl and Python modules that are installed on a base Mac OS system that are expected to be installed by Homebrew formula. See for example `XML::Parser` in #1036, and Python's `setuptools` in about a dozen different issues. There should be a `brew doctor` check to confirm that these modules are installed on Linux.

# Python

```
setuptools
```

# Perl

```
XML::Parser
```

**Comment by DoomHammer** [comment]
As for checks there already is #973 . List would still be needed, though.

**Comment by tseemann** [comment]
Perl installs a bunch of "Core" modules, but these change with each version of Perl.

I'm assuming OSX has the set of core modules for the version it has installed, plus some extras perhaps?

My laptop has gone through 4 version of OSX via upgrades and I don't think I've ever used CPAN to install any Perl modules on it. Here's what folders I have:

```
ls /Library/Perl/
5.16	5.18	Updates
```
How would we go about finding a list of the modules in a virgin OSX install?

If you have a fresh OSX image I think `cpan -l` will do it.

**Comment by sjackman** [comment]
The list of Perl modules is rather longer than I had expected.
El Capitan https://gist.github.com/f39b8b95e3215458609dbe572b6a0a9d
```
❯❯❯ cpan -l | grep -v undef | sort -u | gist
```

**Comment by sjackman** [comment]
Perhaps we can just add to the list as people report bugs.

**Comment by DoomHammer** [comment]
Some of them might just be "standard" Perl libs as I see them on a Linux box as well.

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/brew#6
