### ISSUE TITLE
Custom linker documentation?

### ISSUE THREAD

**Issue by mynameismevin** [Linuxbrew/linuxbrew#1056]
I'm having an issue with linuxbrew, it's not finding the system linker because I'm on an armhf platform (rpi) with a custom kernel. If I unset the default linker variable, will linuxbrew find the default linker and update itself? I notice the linker seems to be hardcoded in [install.rb](https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Homebrew/cmd/install.rb), but changing it there doesn't seem to do anything.

Is there any documentation surrounding custom linkers with linuxbrew? If not, how can I troubleshoot this? I'm more then willing to document how I fixed this.

**Comment by sjackman** [comment]
Ah, you mean the dynamic linker, `ld.so`? Change the symlink named `ld.so` found in `$HOMEBREW_PREFIX/lib/ld.so`.

**Comment by mynameismevin** [comment]
The only one I found was in `~/.linuxbrew/Library/ENV/4.3/`. I'm assuming that's the proper one?

Thanks for the quick response. :+1:

**Comment by sjackman** [comment]
Are you referring to the dynamic linker `ld.so` or the static linker `ld`? `Library/ENV/4.3/` is for `superenv` and that is not used by `Linuxbrew`. Linuxbrew does not configure the static linker. To use a different static linker, trying creating a symlink from your linker to `~/.linuxbrew/bin/ld`.

**Comment by mynameismevin** [comment]
Ah that's what I was looking for. That fixed it. Where would you like me to document that?

**Comment by sjackman** [comment]
It's not so much specific to Linuxbrew as it is about configuring GCC. You can create a new page on the Wiki over at https://github.com/Linuxbrew/linuxbrew/wiki
