### ISSUE TITLE
Split linuxbrew repository into brew and formula

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/linuxbrew#1062]
See https://github.com/Homebrew/legacy-homebrew/pull/49752
and https://github.com/Homebrew/brew/pull/1

**Comment by sjackman** [comment]
@xu-cheng You wrote me a nice comment with the steps that I have to take to complete the split for Linuxbrew. Do you recall where that comment is? I've searched the above two issues but didn't manage to find it.

**Comment by xu-cheng** [comment]
https://github.com/Linuxbrew/linuxbrew/issues/1033

**Comment by sjackman** [comment]
Ah, thanks.
