### ISSUE TITLE
git: Error: Directory not empty

### ISSUE THREAD

**Issue by skystrife** [Linuxbrew/linuxbrew#1063]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug report:

Trying to bootstrap `linuxbrew` on a clean Ubuntu 12.04 docker container, just as a test. Everything goes well until trying to build `git`, where everything *seems* to build just fine, but I get some very nonsensical error when it's trying to install the html documentation:

```
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.8.0.tar.xz
Already downloaded: /home/meta/.cache/Homebrew/git--html-2.8.0.tar.xz
==> Verifying git--html-2.8.0.tar.xz checksum
Error: Directory not empty - /home/meta/.linuxbrew/Cellar/git/2.8.0/lib/perl/5.14.2
```
The referenced directory *definitely* doesn't exist. Any ideas?

Logs: https://gist.github.com/anonymous/858f592a733e03996c89ce8aea47f40e

**Comment by skystrife** [comment]
OK, I was able to solve this by using a brewed perl (which takes *forever* to install because of the `make test`...).

Does `git` need to depend on a more recent version of `perl` than 5.14.2?

**Comment by sjackman** [comment]
I'm glad to hear that you found a workaround. This error has come up before. Does this patch help? https://github.com/Linuxbrew/linuxbrew/issues/682#issuecomment-188460869

**Comment by skystrife** [comment]
Here's what's in that directory for me when running a shell after a `brew install -dv git` without first installing `perl`:

```bash
$ find /home/meta/.linuxbrew/Cellar/git/2.8.0/lib/perl/5.14.2
/home/meta/.linuxbrew/Cellar/git/2.8.0/lib/perl/5.14.2
/home/meta/.linuxbrew/Cellar/git/2.8.0/lib/perl/5.14.2/auto
/home/meta/.linuxbrew/Cellar/git/2.8.0/lib/perl/5.14.2/auto/Git
/home/meta/.linuxbrew/Cellar/git/2.8.0/lib/perl/5.14.2/auto/Git/.packlist
```

Your patch fixes the problem for me, btw. Can we merge it?

**Comment by sjackman** [comment]
Sure. Would you like to submit a pull request?
