### ISSUE TITLE
egma

### ISSUE THREAD

**Issue by DwinGrashof** [Linuxbrew/linuxbrew#1065]
# Please follow the general troubleshooting steps first:

- [ ] Ran `brew update` and retried your prior step?
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from:

`brew gist-logs <formula>`
(where `<formula>` is the name of the formula that failed to build).

### Feature/Formula Requests:

**Please note by far the quickest way to get a new feature or formula into Linuxbrew is to file a [Pull Request](https://github.com/Linuxbrew/linuxbrew/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by rwhogg** [comment]
Hello @DwinGrashof, was this issue opened by mistake? It doesn't have any details about what failed.

**Comment by DwinGrashof** [comment]
Hello,

Yes it was. I am sorry for the trouble.

Regards,
Dwin Grashof
