### ISSUE TITLE
Standalone installation of Linuxbrew

### ISSUE THREAD

**Issue by mbsullivan** [Linuxbrew/linuxbrew#107]
I just tested the installation of glibc under the bottle branch; it went pretty well, but there may be a couple missing dependencies. (I am installing it on a machine running CentOS 5.5, which is quite outdated.)

I haven't yet looked into how dependencies/version requirements are dictated in Homebrew/Linuxbrew, so I'll just describe the procedure I went through to get it installed. Here's what happened:

(1) prepared the bottle branch and installed patchelf using Linuxbrew's local gcc:
```
>cd $LINUXBREW; git checkout bottle
>brew install patchelf -v --cc=gcc-4.8
```

(2) tried glibc `brew install glibc -v --cc=glibc`, it fails with:
```
*** These critical programs are missing or too old: as ld
```
It seems to me like this means that a new version of binutils is a dependency.

(3) installed binutils `brew install binutils -v --cc=gcc-4.8`. 

(4) The binutils [recipe](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/binutils.rb) uses a program prefix 'g' (leading to `gld` and `gas`), which is non-standard for Linux distros I've used. This led to some errors, so I had to manually symlink $LINUXBREW/bin/ld and $LINUXBREW/bin/gas to the generated programs. Would this be considered a bug in linuxbrew's binutils?

(5) With the new binutils, an installation of glibc now runs into old kernel header files:
```
checking installed Linux kernel header files... TOO OLD!
```
It seems like this means that a new version of linux-headers is a dependency.

(4) Installed linux-headers with `brew install linux-headers -v --cc=gcc-4.8`. Something weird happened here... It seemed to not respect the --cc= version I gave it, and ended up using an old-and-busted gcc on the system path. (Any idea why this would happen?) I took this version of gcc out of my path and continued.

(5) With new binutils and linux-headers installed, glibc 2.19 installed like a charm. 

One more thing: I might add a caveat to the installer to warn the user to unset LD_LIBRARY_PATH immediately if they've left it pointing to $LINUXBREW/lib/. Otherwise the new glibc will minorly hose your system if it expects an older one.

**Comment by yeluolei** [comment]
@mbsullivan same problem with an old gcc version 3.5 and no system access rights, any process to install a new gcc?

**Comment by sjackman** [comment]
I believe these issues are resolved. I'm closing this ticket. Feel free to open a new ticket if some of the issues raised here are still current.
