### ISSUE TITLE
Linuxbrew should check whether dependencies are already installed

### ISSUE THREAD

**Issue by nabeelomer** [Linuxbrew/linuxbrew#1076]
Some dependencies may already be installed on the system by the platform's native package manager, Linux brew should check whether any of these are installed before installing them.

**Comment by tseemann** [comment]
I always wondered if Linuxbrew could make "virtual" installations into the Cellar by symlinking to an installed system package by querying the rpm/deb. ie. "mirror an RPM into the Cellar"

**Comment by nabeelomer** [comment]
@tseemann That is actually a very good idea.

**Comment by sjackman** [comment]
Yep, that would work. I've done something like that on an ad hoc basis occasionally. I wouldn't want it to be the default behaviour, because the version provided by the system, may not be compatible with the version expected to be installed by Linuxbrew.

**Comment by nabeelomer** [comment]
Could you share how you did it?

Theoretically, Linuxbrew could check if the version installed by the system is the compatible with what the formula requires.

Nabeel Omer

-----Original Message-----

**Comment by sjackman** [comment]
> Could you share how you did it?

Manually, but it could be automated. For example:
```sh
mkdir -p `brew --cellar`/xz/5.2.2/bin  `brew --cellar`/xz/5.2.2/lib
ln -s /usr/bin/xz `brew --cellar`/xz/5.2.2/bin/
ln -s /usr/lib/libxz* `brew --cellar`/xz/5.2.2/lib
brew link xz
```

**Comment by sjackman** [comment]
> Theoretically, Linuxbrew could check if the version installed by the system is the compatible with what the formula requires.

In fact, if you ran `brew upgrade` it would upgrade any host kegs that were older than the version provided by Linuxbrew unless you pinned the host keg.

**Comment by nabeelomer** [comment]
Would you be fine with this behavior if Linuxbrew checked whether the version provided by APT or whatever is the same that the formula requires?

**Comment by sjackman** [comment]
If you wanted to submit a PR that implemented a `brew link-host` command, I'd review it. i.e. `brew link-host xz`

**Comment by DoomHammer** [comment]
One problem I see with this approach is that formula names may differ from system packages (be it APT, yum, or whatever). Another: all those native package managers... their name is Legion. https://www.youtube.com/watch?v=jGALJwdBOX4

**Comment by sjackman** [comment]
Useful on occasion for packages without Linuxbrew formula. Closing as wontfix.
