### ISSUE TITLE
brew installation fails entirely, `brew` cannot run

### ISSUE THREAD

**Issue by tcby45** [Linuxbrew/linuxbrew#1077]
I just ran the install script mentioned in the README. Everything seemed to go successful, but then...

```
$ brew update && brew doctor
/home/ubuntu/.linuxbrew/Library/brew.sh: line 177: exec: : not found
Error: Git must be installed and in your PATH!
```
This happens for any command involving `brew`. Git, of course, is installed and in my path, or else the installation would have failed. What's going on?

**Comment by sjackman** [comment]
Is `ruby` in your path? Please report `which -a ruby`

**Comment by tcby45** [comment]
I think I figured it out - running that gave an error, so I had RVM get the newest version of Ruby, which warned me about something in my `.zshrc` not having `:$PATH` appended. I fixed that and everything works spectacularly. Thank you!

**Comment by sjackman** [comment]
Great! Glad to hear that you got it working.
