### ISSUE TITLE
Fish depends on ncurses

### ISSUE THREAD

**Issue by andrewrynhard** [Linuxbrew/linuxbrew#1079]
This is not an issue (yet) but a question. When I installed `fish` I needed to run `sudo yum install -y ncurses-devel` or the build would fail. I remember having to do this for another package (can't remember the exact one) as well. Is this by design or should the formula include these in their dependencies?

**Comment by rwhogg** [comment]
We try to rely on host system dependencies as little as possible. I can confirm that the dependency is missing; thanks for reporting!

If you'd like, you can submit a pull request that adds the following:

```ruby
depends_on "homebrew/dupes/ncurses" unless OS.mac?
```

If not, I'll get around to submitting it myself soon.

**Comment by andrewrynhard** [comment]
The `#Contributing` message mentioned that if I was in doubt, to add PRs to Linuxbrew. Should I move this to Homebrew?

**Comment by rwhogg** [comment]
The `ncurses` dependency isn't necessary on OS X (ncurses is provided by default there), so please send the PR here rather than to Homebrew.

In general, if you're adding something with `unless OS.mac?` or `if OS.linux?` it probably should come here rather than to Homebrew.

**Comment by andrewrynhard** [comment]
Great. I have made the PR.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#263
