### ISSUE TITLE
util-linux: conflicts with gnu-getopt

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#1091]
Both of them install a `getopt` command.

**Comment by sjackman** [comment]
I'm inclined to remove the `getopt` command from `util-linux` and use `gnu-getopt`. In cases like this, I usually defer to whatever Debian is doing.

**Comment by rwhogg** [comment]
> I'm inclined to remove the getopt command from util-linux and use gnu-getopt

I like that plan; it's what I did locally to deal with this.

**Comment by sjackman** [comment]
`/usr/bin/getopt` is provided by `util-linux` on Debian.
https://packages.debian.org/search?searchon=contents&keywords=%2Fbin%2Fgetopt&mode=exactfilename&suite=stable&arch=any

Unless we have a good reason otherwise, I prefer to go with whatever Debian has done.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#144
