### ISSUE TITLE
vpcs fails to build

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#1093]
Message:

```
==> make -f Makefile.osx
gcc   -DDarwin -Di386 -DHV -Wall  -c vpcs.c
gcc   -DDarwin -Di386 -DHV -Wall  -c daemon.c
gcc   -DDarwin -Di386 -DHV -Wall  -c readline.c
gcc   -DDarwin -Di386 -DHV -Wall  -c packets.c
daemon.c:53:18: fatal error: util.h: No such file or directory
compilation terminated.
Makefile.osx:38: recipe for target 'daemon.o' failed
make: *** [daemon.o] Error 1
```

I already have a fix for this; I'll submit it after the freeze is over.

**Comment by rwhogg** [comment]
I think there's something wrong with the bottle, so I'm reopening this. I didn't pull the bottle anyways

**Comment by sjackman** [comment]
You can use https://github-issue-mover.appspot.com to migrate issues to `Linuxbrew/homebrew-core`.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#129
