### ISSUE TITLE
Introduce a HOMEBREW_ARCH environment variable to specify target microarchitecture

### ISSUE THREAD

**Issue by eiennohito** [Linuxbrew/linuxbrew#1095]
It is useful in scenarios when you have heterogenous grid of computers with different microarchitectures and want to build binaries that can be used everywhere.

Discussion is started in #1094.

**Comment by eiennohito** [comment]
`-march=native` started to make shared installation unusable in our environment :(

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/brew#42
