### ISSUE TITLE
subversion --with-serf: deparallelize make install

### ISSUE THREAD

**Issue by eiennohito** [Linuxbrew/linuxbrew#1097]
Regular install of the formula works, but `--with-serf` fails.

Here are logs: https://gist.github.com/anonymous/e810f289d9e4cfb5095af136fb3e3bc1

I do not see anything weird in the log.
Any ideas?

**Comment by eiennohito** [comment]
Doing `--verbose --debug` install, performing make install by hand and ignoring the error result in a working svn by the way.

**Comment by sjackman** [comment]
```
libtool: warning: '/dev/shm/subversion20160426-24557-8xnu2u/subversion-1.9.3/subversion/libsvn_ra_local/libsvn_ra_local-1.la' has not been installed in '/mnt/orange/brew/data/Cellar/subversion/1.9.3/lib'
/mnt/orange/brew/data/bin/ld: cannot find -lsvn_delta-1
collect2: error: ld returned 1 exit status
libtool: warning: '/dev/shm/subversion20160426-24557-8xnu2u/subversion-1.9.3/subversion/libsvn_repos/libsvn_repos-1.la' has not been installed in '/mnt/orange/brew/data/Cellar/subversion/1.9.3/lib'
libtool:   error: error: relink 'libsvn_ra_serf-1.la' with the above command before installing it
libtool: warning: '/dev/shm/subversion20160426-24557-8xnu2u/subversion-1.9.3/subversion/libsvn_fs/libsvn_fs-1.la' has not been installed in '/mnt/orange/brew/data/Cellar/subversion/1.9.3/lib'
make: *** [install-serf-lib] Error 1
```
https://gist.github.com/anonymous/e810f289d9e4cfb5095af136fb3e3bc1#file-05-make-L141

**Comment by sjackman** [comment]
For what purpose do you need `--with-serf`? This option is unfortunately known not to work on Linux.

**Comment by eiennohito** [comment]
Otherwise http/https transports of svn do not work making built subversion pretty useless (or am I doing something wroing?)

Second invocation of make install finishes correctly.

**Comment by sjackman** [comment]
Your timing is good. I hadn't yet run into this issue myself, and just encountered it. `brew install homebrew/science/k8` requires `svn --with-serf` for `http` support.

**Comment by sjackman** [comment]
I see the same error as you did above when installing `subversion --with-serf`.

**Comment by sjackman** [comment]
Running `brew install subversion --with-serf` at error selecting `5. shell` then running `make install; exit` and selecting `2. ignore` works great. Thanks for the workaround, Arseny.

**Comment by eiennohito** [comment]
Maybe their local automake&company files are broken. 
I will try to regenerate them using autotools and report what happens when I'll have some time.

**Comment by sjackman** [comment]
This patch worked for me!
```diff
diff --git a/Library/Formula/subversion.rb b/Library/Formula/subversion.rb
index fadccc4..b7619d5 100644
--- a/Library/Formula/subversion.rb
+++ b/Library/Formula/subversion.rb
@@ -168,7 +168,8 @@ class Subversion < Formula
 
     system "./configure", *args
     system "make"
-    system "make", "install"
+    # Fix ld: cannot find -lsvn_delta-1
+    ENV.deparallelize { system "make", "install" }
     bash_completion.install "tools/client-side/bash_completion" => "subversion"
 
     system "make", "tools"
```

**Comment by eiennohito** [comment]
Great! `--with-serf` should be made a default option once more, probably.

**Comment by sjackman** [comment]
Woops. Spoke too soon. I forgot to add the `--with-serf` in that test. =/
I'm testing it now `--with-serf`.

**Comment by sjackman** [comment]
It works! For real this time. :tada:

**Comment by sjackman** [comment]
This issue was moved to Linuxbrew/homebrew-core#4
