### ISSUE TITLE
`cairo` fails on Linux Mint 17.3 Rosa XFCE x64

### ISSUE THREAD

**Issue by circlespainter** [Linuxbrew/linuxbrew#1105]
- [X] Ran `brew update` and retried.
- [X] Ran `brew doctor` -> All OK.

### Bug report:

`cairo` fails on Linux Mint 17.3 Rosa XFCE x64 with `checking whether cairo's XCB surface backend feature could be enabled... no (requires xcb >= 1.6 xcb-render >= 1.6 http://xcb.freedesktop.org)`.

Logs gist: https://gist.github.com/anonymous/ec07977ee5f5ed4c374c717fda62a784

**Comment by sjackman** [comment]
Try `brew install linuxbrew/xorg/xorg cairo`

**Comment by circlespainter** [comment]
This installs a lot of stuff (brew's version of many X libs it seems) but it works, thanks

**Comment by sjackman** [comment]
Thanks for the bug report and update, Fabio.
This issue will be fixed by https://github.com/Linuxbrew/brew/issues/5
