### ISSUE TITLE
ncurses: doesn't install curses headers to .linuxbrew/include

### ISSUE THREAD

**Issue by oneillkza** [Linuxbrew/linuxbrew#144]
The ncurses headers (curses.h, ncurses.h, etc) are needed by some software (eg GHC). However, while the ncurses.rb formula does install these in the Cellar, it doesn't make them available in .linuxbrew/include

What is needed is something like:

```
 ln -s ~/.linuxbrew/Cellar/ncurses/5.9/include/ncursesw/* ~/.linuxbrew/include
```

But in the correct way within ruby, using the homebrew variables specifying the locations of these files in a version-independent manner. (This is slightly beyond me, or I would patch it myself).

Note that this is a necessary step towards solving #143.

**Comment by rwhogg** [comment]
@sjackman I think this issue can be closed.
