### ISSUE TITLE
svn: Failed to build

### ISSUE THREAD

**Issue by graydetroit** [Linuxbrew/linuxbrew#182]
I'm having an issue installing svn on my Laravel Homestead VM running on osx 10.10.

Here's the [gist](https://gist.github.com/248280fdbfd5c8d3bcf6)

Thanks.

**Comment by paulhybryant** [comment]
serf seems to compile fine for me but it failed during "make install"

Then I tried brew install --debug subversion

When it raise from ruby
1. raise
2. ignore
3. backtrace
4. irb
5. shell

I chose 5
execute "make install"
exit shell

then choose 4
do nothing and exit

and the installation continued and succeeded.
Not sure why.

**Comment by sjackman** [comment]
Does `brew install homebrew/dupes/krb5` before `brew install subversion` help `subversion` to install correctly?
Should `--without-serf` be the default for `subversion` in Linuxbrew?
What functionality does this disable if we do disable `serf` by default?

**Comment by sjackman** [comment]
Installing `homebrew/dupes/krb5` does not seem to be enough to get `subversion`'s `serf` to compile correctly. I'm going to disable `serf` by default.
```
scons: Reading SConscript files ...
/bin/sh: 1: /usr: Permission denied
OSError: '/usr --cflags gssapi' exited 126:
  File "/tmp/subversion--serf20160224-17504-1skjz6v/serf-1.3.8/SConstruct", line 360:
    env.ParseConfig('$GSSAPI --cflags gssapi')
  File "/home/linuxbrew/.linuxbrew/Cellar/scons/2.4.1/libexec/scons-local/SCons/Environment.py", line 1576:
    return function(self, self.backtick(command))
  File "/home/linuxbrew/.linuxbrew/Cellar/scons/2.4.1/libexec/scons-local/SCons/Environment.py", line 594:
    raise OSError("'%s' exited %d" % (command, status))
```
