### ISSUE TITLE
isl 0.14.1 fails to build as gcc depends on isl (same applies to mpfr)

### ISSUE THREAD

**Issue by davydden** [Linuxbrew/linuxbrew#487]
on a stand alone linuxbrew there is a problem upgrading `isl`, `mpfr` and `gcc`.
The issue boils down to gcc being built against `isl` and `mpfr`
```
configure:3774: checking whether the C compiler works
configure:3796: /XXX/.linuxbrew/bin/gcc-4.9 -Os -w -pipe -march=core2 -isystem/XXX/.linuxbrew/include -L/XXX/.linuxbrew/lib -Wl,--dynamic-linker=/XXX/.linuxbrew/opt/glibc/lib/ld-linux-x86-64.so.2 -Wl,-rpath,/XXX/.linuxbrew/lib conftest.c  >&5
/XXX/.linuxbrew/Cellar/gcc/4.9.2/libexec/gcc/x86_64-unknown-linux-gnu/4.9.2/cc1: error while loading shared libraries: libisl.so.10: cannot open shared object file: No such file or directory
```
i ran with `-d` to confirm that `libisl.so.10` is not in `lib`:
```
==> ./configure --disable-silent-rules --prefix=/XXX/.linuxbrew/Cellar/isl/0.14.1 --with-gmp=system --with-gmp-prefix=/XXX/.linuxbrew/opt/gmp
checking for gcc... /XXX/.linuxbrew/bin/gcc-4.9
checking whether the C compiler works... no
configure: error: in `/tmp/isl20150716-33394-1ldpd8x/isl-0.14.1':
configure: error: C compiler cannot create executables
See `config.log' for more details
/XXX/.linuxbrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: ./configure --disable-dependency-tracking --disable-silent-rules --prefix=/XXX/.linuxbrew/Cellar/isl/0.14.1 --with-gmp=system --with-gmp-prefix=/XXX/.linuxbrew/opt/gmp
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
When you exit this shell, you will return to the menu.
iwtm51@hydra:/tmp/isl20150716-33394-1ldpd8x/isl-0.14.1> ls /XXX/.linuxbrew/lib | grep "isl"
cloog-isl
isl
libcloog-isl.a
libcloog-isl.so
libcloog-isl.so.4
libcloog-isl.so.4.0.0
```

same applies to `mpfr` and `gcc` itself.

Solution is to `brew tap homebrew/versions` and force using system's gcc: 
`brew upgrade isl --cc=gcc-4.7` and `brew upgrade mpfr --cc=gcc-4.7`.

I wonder if there is way to do it somehow automatically within the formulae so that the user does not hit those compiler-not-working errors? Or alternatively hack `homebrew` to keep `isl` and `mpfr` in the `lib` even during installation so that compiler works and then unlink them right before symlinking newer versions.

It's a kind of circular issue, no idea if there is a solution at all.

**Comment by sjackman** [comment]
Try
```sh
LD_LIBRARY_PATH=`brew --prefix isl`/lib: brew upgrade isl
LD_LIBRARY_PATH=`brew --prefix mpfr`/lib brew upgrade mpfr
brew upgrade gcc
```

**Comment by davydden** [comment]
can't try as I already installed it, but I think your solution would work as it did work in https://github.com/Homebrew/homebrew-science/issues/2521

**Comment by sjackman** [comment]
Glad to hear it worked. There's a challenge here with what `LD_LIBRARY_PATH` should be set to when upgrading. The old version, the new version, or both. All three have problems.

**Comment by davydden** [comment]
i think it should be old. If i upgrade `isl`, it's not yet build and linked whereas `gcc` wants the `.so`. So i think it should be old.

**Comment by sjackman** [comment]
With `netcdf` though it has to be new to install or upgrade `netcdf`.

**Comment by davydden** [comment]
sure, absolutely, `netcdf` is a different story.

**Comment by davydden** [comment]
maybe add by default the old one and have a mechanism to switch to the new prefix if needed? Perhaps, there will be less formulas like `netcdf`, and more like `isl` and `mpfr`

**Comment by davydden** [comment]
btw, with `gcc` one would still need to `brew upgrade gcc --cc=gcc-4.7` or put the previous gcc's bin into path, perhaps, together with LD_LIBRARY_PATH as in the above.

**Comment by sjackman** [comment]
Another option is to add `isl` and `mpfr` to the `RPATH` of `gcc`.
