### ISSUE TITLE
hello: Error: hello cannot be built with any available compilers.

### ISSUE THREAD

**Issue by Mikaela** [Linuxbrew/linuxbrew#517]
```
nemo@synvaler:~$ brew install hello
Error: hello cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
```

and that command also ends into gcc not being installed.

But I still have gcc

```
nemo@synvaler:~$ LC_ALL=C gcc --version
gcc (Linaro GCC 4.8-2014.01) 4.8.3 20140106 (Mer 4.8.3-1)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

and g++

```
g++ (Linaro GCC 4.8-2014.01) 4.8.3 20140106 (Mer 4.8.3-1)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I have no idea what else linuxbrew could want. `brew doctor` only tells me

> Your system is ready to brew.

and I cannot use `brew gist-logs` as there aren't logs yet.

`uname -a`: `Linux synvaler 3.4.106.20150416.1 #1 SMP PREEMPT Tue Jun 23 14:12:57 UTC 2015 armv7l armv7l armv7l GNU/Linux`

**Comment by saketkc** [comment]
Can you retry after doing `export HOMEBREW_CC=gcc`

**Comment by Mikaela** [comment]
```
nemo@synvaler:~$ export HOMEBREW_CC=gcc
nemo@synvaler:~$ brew install hello
Error: hello cannot be built with any available compilers.
To install this formula, you may need to:
  brew install gcc
````

**Comment by saketkc** [comment]
I had a similar issue, when installing `linuxbrew` on a new machine with `gcc-4.4`.
Just doing, `export HOMEBREW_CC=gcc` worked.

**Comment by tdsmith** [comment]
Try the solution here: https://github.com/Homebrew/linuxbrew/issues/452#issuecomment-115435227

**Comment by Mikaela** [comment]
That solution didn't work directly, but with small modifications it started working. The issue appears to be and gcc-4.8 and g++-4.8 are in `/bin` instead of `/usr/bin`, so that directory should probably also be looked at and I will keep this open.

```
nemo@synvaler:~$ brew install hello
==> Downloading http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz
==> Downloading from http://www.nic.funet.fi/pub/gnu/ftp.gnu.org/pub/gnu/hello/h
######################################################################## 100,0%
==> ./configure --disable-silent-rules --prefix=/home/nemo/.local/Cellar/hello/2
==> make install
/home/nemo/.local/Cellar/hello/2.10: 52 files, 320K, built in 62 seconds
```

The fix was:

```bash
ln -s $(which gcc-4.8) /usr/bin/gcc-4.8
ln -s $(which g++-4.8) /usr/bin/g++-4.8
```

Thanks

**Comment by joshuaswilcox** [comment]
Hm, i still get this, and FWIW i get this for gcc

    28-08-15 13:31:12> which gcc
    /usr/bin/gcc

**Comment by sjackman** [comment]
The workaround for your issue, Joshua, is here: https://github.com/Linuxbrew/linuxbrew/wiki/Standalone-Installation#create-symlinks-for-gcc
```
ln -s $(which gcc) `brew --prefix`/bin/gcc-$(gcc -dumpversion |cut -d. -f1,2)
ln -s $(which g++) `brew --prefix`/bin/g++-$(g++ -dumpversion |cut -d. -f1,2)
ln -s $(which gfortran) `brew --prefix`/bin/gfortran-$(gfortran -dumpversion |cut -d. -f1,2)
```
