### ISSUE TITLE
Build X11 development libraries and headers for Linux

### ISSUE THREAD

**Issue by kitmonisit** [Linuxbrew/linuxbrew#527]
Hi, I had been reading #64 and its related issues. Unless I missed something, I understand that there are no plans yet to build X11 with Homebrew, according to #166 . Does anyone think it might be a good idea to pursue this? We could limit it to just Linux machines.

If we don't pursue this, then that means we can never really use Homebrew without `sudo` :cry: 

I find this important because gtk+ does not build without cairo's X11 backend support (See #96). Also, Homebrew vim cannot be compiled with the `+clipboard` feature (for access to system clipboard) without X11.

Below are notes I've written while building X11 manually. Those libraries are to be built in order.

    DONE util-macros    http://www.x.org/releases/X11R7.7/src/everything/util-macros-1.17.tar.bz2
    DONE xproto         http://www.x.org/releases/X11R7.7/src/everything/xproto-7.0.23.tar.bz2
    DONE xextproto      http://www.x.org/releases/X11R7.7/src/everything/xextproto-7.2.1.tar.bz2
    DONE xtrans         http://www.x.org/releases/X11R7.7/src/everything/xtrans-1.2.7.tar.bz2
        xtrans has its `xtrans.pc` file found in `PREFIX/share/pkgconfig`.  After
        `make install`, either append `PREFIX/share/pkgconfig` to `PKG_CONFIG_PATH`
        or symlink `xtrans.pc` to `PREFIX/lib/pkgconfig`.
    DONE libxml2        http://xmlsoft.org/sources/libxml2-2.9.2.tar.gz
        `./configure` can find `PREFIX/lib/libpython2.7.so`, but upon compilation,
        it complains that it cannot find `-lpython2.7`.  An ugly hack consists of
        editing the resulting `python/Makefile` after configure.  Append
        `-LPREFIX/lib` to the `PYTHON_LIBS` variable.

        An alternative is to run `LDFLAGS=-L$PREFIX/lib ./configure`
    
        This is caused by `python-config --ldflags` (in the `configure` script) not
        returning the `-LPREFIX/lib` argument.
    DONE libxslt        http://xmlsoft.org/sources/libxslt-1.1.28.tar.gz
    DONE xcb-proto      http://www.x.org/releases/X11R7.7/src/everything/xcb-proto-1.7.1.tar.bz2
        Need `./autogen.sh`
    DONE pthread-stubs  http://www.x.org/releases/X11R7.7/src/everything/libpthread-stubs-0.3.tar.bz2
    DONE xcb            http://www.x.org/releases/X11R7.7/src/everything/libxcb-1.8.1.tar.bz2
    DONE kbproto        http://www.x.org/releases/X11R7.7/src/everything/kbproto-1.0.6.tar.bz2
    DONE inputproto     http://www.x.org/releases/X11R7.7/src/everything/inputproto-2.2.tar.bz2
    DONE libxau         http://www.x.org/releases/X11R7.7/src/everything/libXau-1.0.7.tar.bz2
    DONE libx11         http://www.x.org/releases/X11R7.7/src/everything/libX11-1.5.0.tar.bz2
    
    cairo
    - to enable X11 backend support
    - need `--x-includes` and `--x-libraries` options to `./configure`
    - `gtk+` will not build if `cairo` does not have X11 backend support (cannot find `cairo-xlib`)
    DONE renderproto    http://www.x.org/releases/X11R7.7/src/everything/renderproto-0.11.1.tar.bz2
    DONE libxrender     http://www.x.org/releases/X11R7.7/src/everything/libXrender-0.9.7.tar.bz2
    DONE libxext        http://www.x.org/releases/X11R7.7/src/everything/libXext-1.3.1.tar.bz2
    
    vim
    - to enable X11 support 
    - need `--with-x --x-libraries --x-includes` options to `./configure`
    - necessary for system clipboard access (`+clipboard` shown in `:version`)
    DONE libICE         http://www.x.org/releases/X11R7.7/src/everything/libICE-1.0.8.tar.bz2
    DONE libSM          http://www.x.org/releases/X11R7.7/src/everything/libSM-1.2.1.tar.bz2
    DONE libXt          http://www.x.org/releases/X11R7.7/src/everything/libXt-1.1.3.tar.bz2

**Comment by sjackman** [comment]
Yes, I do think there is a benefit to building X11 with Homebrew. I haven't had the time to tackle it. Feel free to submit a pull request if you have the inclination.

**Comment by rwhogg** [comment]
I know I previously backed out of this, but I'm willing to give this a try. I've already got `libxcb` to compile. I'll submit a work-in-progress PR soon.

**Comment by sjackman** [comment]
That's great. Thanks, Bob. I hope it goes well! Do you plan on putting the individual libraries each in their own formula, or all in one big formula? Have you seen the LFS page? http://www.linuxfromscratch.org/blfs/view/svn/x/x7lib.html

**Comment by rwhogg** [comment]
I don't think every individual library warrants its own package, but I think I will probably split them up.

My thinking so far is basically: if more than one package in the dependency tree directly requires it, it'll get its own library.

BTW, some of the resources for `makedepend` are also needed by `libxcb`. What would you like to do with those?

Thanks for pointing out the LFS page, I'd forgotten that that exists!

It might take some time for me to get as far as XLib.

**Comment by sjackman** [comment]
`makedepend` is an upstream Homebrew formula, so I don't want to mess with it. I'll just leave it as is.

**Comment by sjackman** [comment]
> It might take some time for me to get as far as XLib.

No rush, but I'm excited that you're working on it.

**Comment by meonlol** [comment]
I've messed around with trying to build x11 and it's dependencies from source, but I think there is a more general issue here. I already have x11 installed per default but it can not find it for any x11 related formulas. I don't understand it fully, but am I right that the `https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Homebrew/requirements/x11_requirement.rb` class looks for the XQuartz installation only? If that is correct, I don't think building from source will help us much until regular X11 is supported as well.

**Comment by sjackman** [comment]
`xquartz.rb` is hacked up for Linux to say that X11 is installed, whether it is or not, so that `x11_requirement.rb` is always satisfied on Linux. It's definitely not ideal.
https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Homebrew/os/mac/xquartz.rb#L33
@maxim-belkin and @rwhogg are working on building Xorg from source.
https://github.com/Linuxbrew/homebrew-xorg/blob/master/xorg.rb
Try `brew install linuxbrew/xorg/xorg`
