### ISSUE TITLE
synapse package

### ISSUE THREAD

**Issue by typekpb** [Linuxbrew/linuxbrew#539]
not sure about the proper place to report, but would love to see the package for launcher called synapse: https://launchpad.net/synapse-project

please note this would be linux only package

**Comment by rwhogg** [comment]
I'd welcome a pull request for this, but I don't have the time to do it myself.

If you want to try to create the formula yourself, please see [the formula cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook).

Thanks for the package suggestion!

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#142
