### ISSUE TITLE
cairo: error: X11/extensions/XShm.h: No such file or directory

### ISSUE THREAD

**Issue by typekpb** [Linuxbrew/linuxbrew#542]
I'm trying to install cairo on linuxbrew using:

        brew install cairo

it fails with error:

        ==> ./configure --prefix=/home/pb/.linuxbrew/Cellar/cairo/1.14.2_1 --enable-gobject=yes --enable-svg=yes --enable-tee=yes --enable-xcb=no
        ==> make install
        make[2]: *** [install] Error 2
        make[2]: Leaving directory `/tmp/cairo20150907-9581-1xl4e8d/cairo-1.14.2/src'
        make[1]: *** [install-recursive] Error 1
        make[1]: Leaving directory `/tmp/cairo20150907-9581-1xl4e8d/cairo-1.14.2'
        make: *** [install] Error 2

gist created by: 

        brew gist-logs cairo

is: https://gist.github.com/7b1ebc1171d2707dba67

**Comment by sjackman** [comment]
`cairo-xlib-surface.c:71:33: fatal error: X11/extensions/XShm.h: No such file or directory`
https://gist.github.com/anonymous/7b1ebc1171d2707dba67#file-02-make-L137

Try
```sh
brew install linuxbrew/xorg/xorg cairo --with-x11
```

**Comment by sjackman** [comment]
`--with-x11` should be the default for `cairo` on Linuxbrew.

**Comment by sjackman** [comment]
Bob, would you like to take a stab at fixing this, when you have time? On non-Mac systems, `:x11` should be `:recommended` rather than `:optional`.

**Comment by sjackman** [comment]
On second thought, don't worry about it, Bob. I had forgotten that Piotr had worked on this issue. I've asked him to take a look at it in #974.

**Comment by DoomHammer** [comment]
A look has been taken ;)
