### ISSUE TITLE
ncurses installation failure

### ISSUE THREAD

**Issue by ianchen06** [Linuxbrew/linuxbrew#554]
Hello I was trying to install vim with linuxbrew, and when it is installing ncurses, it throws the following error when compiling.

```
touch pc-files
/bin/sh -c 'for name in *.pc; do /usr/bin/install -c -m 644 $name /usr/lib/x86_64-linux-gnu/pkgconfig/$name; done'
/usr/bin/install: cannot create regular file ‘/usr/lib/x86_64-linux-gnu/pkgconfig/formw.pc’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/lib/x86_64-linux-gnu/pkgconfig/menuw.pc’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/lib/x86_64-linux-gnu/pkgconfig/ncurses++w.pc’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/lib/x86_64-linux-gnu/pkgconfig/ncursesw.pc’: Permission denied
DESTDIR= \
	prefix=/home/ian/.linuxbrew/Cellar/ncurses/6.0 \
	exec_prefix=/home/ian/.linuxbrew/Cellar/ncurses/6.0 \
	bindir=/home/ian/.linuxbrew/Cellar/ncurses/6.0/bin \
	top_srcdir=.. \
	srcdir=. \
	datadir=/home/ian/.linuxbrew/Cellar/ncurses/6.0/share \
	ticdir=/home/ian/.linuxbrew/Cellar/ncurses/6.0/share/terminfo \
	source=terminfo.tmp \
	cross_compiling=no \
	/bin/sh ./run_tic.sh
/usr/bin/install: cannot create regular file ‘/usr/lib/x86_64-linux-gnu/pkgconfig/panelw.pc’: Permission denied
** Building terminfo database, please wait...
make[1]: *** [install.libs] Error 1
make[1]: *** Waiting for unfinished jobs....
Running sh ./shlib tic to install /home/ian/.linuxbrew/Cellar/ncurses/6.0/share/terminfo ...

	You may see messages regarding extended capabilities, e.g., AX.
	These are extended terminal capabilities which are compiled
	using
		tic -x
	If you have ncurses 4.2 applications, you should read the INSTALL
	document, and install the terminfo without the -x option.

1667 entries written to /home/ian/.linuxbrew/Cellar/ncurses/6.0/share/terminfo
** built new /home/ian/.linuxbrew/Cellar/ncurses/6.0/share/terminfo
** sym-linked /home/ian/.linuxbrew/Cellar/ncurses/6.0/lib/terminfo for compatibility
installing std
installing stdcrt
installing vt100
installing vt300
make[1]: Leaving directory `/tmp/ncurses20150916-22742-1osmtqm/ncurses-6.0/misc'
make: *** [install] Error 2

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew
HEAD: 4e9b33a11eaf7275bf0c816dd711f23fec682778
Last commit: 13 days ago
HOMEBREW_PREFIX: /home/ian/.linuxbrew
HOMEBREW_CELLAR: /home/ian/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 8-core 64-bit 6
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: N/A
System Ruby: 1.9.3-p484 => /usr/bin/ruby1.9.1
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby1.9.1
Java: N/A

CC: /usr/bin/gcc-4.8
CXX: /usr/bin/g++-4.8
OBJC: /usr/bin/gcc-4.8
OBJCXX: /usr/bin/g++-4.8
CFLAGS: -Os -w -pipe -march=core2
CXXFLAGS: -Os -w -pipe -march=core2
CPPFLAGS: -isystem/home/ian/.linuxbrew/include -P
LDFLAGS: -L/home/ian/.linuxbrew/lib -Wl,-rpath,/home/ian/.linuxbrew/lib
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /home/ian/.linuxbrew
PKG_CONFIG_LIBDIR: /home/ian/.linuxbrew/Cellar/ncurses/6.0/lib/pkgconfig
PATH: /home/ian/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ian/.linuxbrew/Library/ENV/scm
```

It seems to be trying to write files to system directories?

**Comment by clozed2u** [comment]
Same here. Tested on Ubuntu 14.04.3.

**Comment by dunn** [comment]
Yeah, we need to figure out how to stop it from trying to write to `/usr/lib`.

**Comment by bosr** [comment]
Hi,

After looking into the `ncurses` source, I found that you can circumvent the problem by adding this to the formula in line 32:

    "--with-pkg-config-libdir=#{prefix}/pc",

This make `ncurses` install the package into a brew-managed location (inside your home by default). 

The caveat is that I made up this path, so I don't expect any pkgconfig installation to find it without help. 

Cheers,
Romain

**Comment by dunn** [comment]
Oh, great!

The odd thing is that when I add `--with-pkg-config-libdir=#{lib}/pkgconfig` to the configure arguments, it doesn't actually create that directory and the pkgconfig files. Does it for you?

**Comment by bosr** [comment]
Hi
Actually `#{prefix}` refers to the installation directory which is already created at this point of time, so if you replace this with `#{lib}`, I'm not sure what it refers to

Cheers

Romain

**Comment by dunn** [comment]
`lib` is just an alias for `prefix/"lib"`.

**Comment by yoaquim** [comment]
Having the same issue; I'm on elementary OS 0.3.1, Freya.

No update on this? Seems like short-circuiting the install location works, but is this an actual solution?

Any reason `ncurses` **needs** to install to `/usr/lib`? Where does `brew` typically install this stuff, under `~/.linuxbrew`, correct?

**Comment by sjackman** [comment]
I'm on vacation in Thailand until the new year. Please bump this thread after then. Sorry for the delay.

**Comment by aftnix** [comment]
Its OK :+1: In the mean time I will stick to the  `vim` from its git repo, though the `HEAD` of that is randomly crashing in my system. That's why i opted for `brew vim`.

**Comment by dunn** [comment]
This may be resolved by https://github.com/Homebrew/homebrew-dupes/commit/09d96f4fe3c4bdbd7fc2be5e75468df22b863301; can you try running `brew update` and trying again?

**Comment by sjackman** [comment]
I'm going to assume this is fixed by the above commit. Thanks, Alex.
