### ISSUE TITLE
Python3 no sqlite

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/linuxbrew#585]
I've installed python3, but there is no support for sqlite. I believe sqlite support is default for the install.

**Comment by dlukes** [comment]
Try uninstalling python3, (re)installing sqlite (with brew), and then reinstalling python3 (run `brew info python3` prior to the installation and see if there's a green tick mark beside the `sqlite` dependency). Worked for me, though fair warning, in my case I also had to reinstall openssl, which was pretty painful (it kept looking for some dylibs which of course don't exist on Linux, so it took some convincing).

**Comment by sjackman** [comment]
The OpenSSL bug will be fixed later today. See #729

**Comment by dlukes** [comment]
Oh great, thanks so much!

**Comment by sjackman** [comment]
The OpenSSL bug is fixed.

**Comment by sjackman** [comment]
`sqlite` is already a dependency of `python3`.
```ruby
  depends_on "sqlite" => :recommended
```
There was a bug fixed in the last week for the `python3` formula related to `CPPFLAGS`. Try reinstalling `python3` as David suggested.

**Comment by jwhite007** [comment]
I actually had this working long ago and forgot, exactly, what fixed it... sorry, guys. Thanks for the input, though.
