### ISSUE TITLE
fontforge failed to build on debian jessie

### ISSUE THREAD

**Issue by midzer** [Linuxbrew/linuxbrew#607]
https://gist.github.com/anonymous/2f77619924c2e7ee90db

**Comment by midzer** [comment]
Retrying build from scratch now.
Python headers have to be installed via `apt-get install python-dev`

**Comment by rwhogg** [comment]
@midzer did the build work with the Python headers installed?

**Comment by sjackman** [comment]
See also #924 
@DoomHammer Could you `brew doctor` check for Python `setuptools` also check that the Python headers are installed?

**Comment by midzer** [comment]
@rwhogg I reinstalled fresh Linuxbrew with python headers. fontforge still fails to install.

Error message remains the same as in first posts gist in config.log:

> /usr/bin/ld: cannot find -lintl
collect2: error: ld returned 1 exit status

**Comment by sjackman** [comment]
This patch should fix the `-lintl` error:
https://github.com/Linuxbrew/linuxbrew/pull/975
