### ISSUE TITLE
R CMD permissions are wrong

### ISSUE THREAD

**Issue by jrderuiter** [Linuxbrew/linuxbrew#614]
When using a freshly installed R from linuxbrew, I ran into the following error when trying to install rpy2:

```{bash}
R CMD config --ldflags
/home/user/.linuxbrew/Cellar/r/3.2.2_1/lib/R/bin/Rcmd: 62: exec: config: not found
```

After some digging if found that it seems that the files in ${R_HOME}/bin are not being created with the correct permissions, as these are not executable by default. Giving these files executable permissions solves the above issue and allows me to correctly install rpy2. 

I did not have this issue on a Mac with homebrew, so it seems to be specific to linuxbrew. On the other hand, my Mac install probably used a bottle and did therefore not build from scratch.

**Comment by thriqon** [comment]
This could be related to a similar bug I ran into a few days ago: #612

Could you do a `file` on the executable in question and comment with the result here?

**Comment by jrderuiter** [comment]
File output is below. I also included an ls to show the permissions of the files.

```{bash}
j.d.ruiter@steroid:~/.linuxbrew/Cellar/r/3.2.2_1/lib/R/bin$ file *
BATCH:         ASCII text
build:         ASCII text
check:         ASCII text
COMPILE:       ASCII text
config:        ASCII text
exec:          directory
f77_f2c:       Bourne-Again shell script, ASCII text executable
INSTALL:       ASCII text
javareconf:    ASCII text, with very long lines
libtool:       Bourne-Again shell script, ASCII text executable
LINK:          ASCII text
mkinstalldirs: Bourne-Again shell script, ASCII text executable
pager:         Bourne-Again shell script, ASCII text executable
R:             Bourne-Again shell script, ASCII text executable
Rcmd:          Bourne-Again shell script, ASCII text executable
Rd2pdf:        ASCII text
Rdconv:        ASCII text
Rdiff:         ASCII text
REMOVE:        ASCII text
Rprof:         ASCII text
Rscript:       ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=cfcd6acac2e6ca11847f148e0efcdd3d257e12d5, not stripped
rtags:         ASCII text
SHLIB:         ASCII text
Stangle:       ASCII text
Sweave:        ASCII text
```

```{bash}
j.d.ruiter@steroid:~/.linuxbrew/Cellar/r/3.2.2_1/lib/R/bin$ ls -alih
total 1.3M
4308815652 drwxr-xr-x  3 j.d.ruiter domain users  598 Oct 26 13:24 .
4308815617 drwxr-xr-x 10 j.d.ruiter domain users  267 Oct 26 13:25 ..
4308740360 -r--r--r--  1 j.d.ruiter domain users 1.8K Oct 26 13:24 BATCH
4308815655 -r--r--r--  1 j.d.ruiter domain users  317 Oct 26 13:24 build
4306613928 -r--r--r--  1 j.d.ruiter domain users  317 Oct 26 13:24 check
4306924644 -r--r--r--  1 j.d.ruiter domain users 2.2K Oct 26 13:24 COMPILE
4306924647 -r--r--r--  1 j.d.ruiter domain users 9.3K Oct 26 13:24 config
4306924669 drwxr-xr-x  2 j.d.ruiter domain users   19 Oct 26 13:24 exec
4310048686 -r-xr-xr-x  1 j.d.ruiter domain users 3.6K Oct 26 13:24 f77_f2c
4306613927 -r--r--r--  1 j.d.ruiter domain users  823 Oct 26 13:24 INSTALL
4306924649 -r--r--r--  1 j.d.ruiter domain users  15K Oct 26 13:24 javareconf
4303843917 -r-xr-xr-x  1 j.d.ruiter domain users 269K Oct 26 13:24 libtool
4306924645 -r--r--r--  1 j.d.ruiter domain users 1.4K Oct 26 13:24 LINK
4303896568 -r-xr-xr-x  1 j.d.ruiter domain users 3.5K Oct 26 13:24 mkinstalldirs
4306924650 -r-xr-xr-x  1 j.d.ruiter domain users  483 Oct 26 13:24 pager
4308740363 -r-xr-xr-x  1 j.d.ruiter domain users 9.0K Oct 26 13:24 R
4306924648 -r-xr-xr-x  1 j.d.ruiter domain users 1.4K Oct 26 13:24 Rcmd
4308815653 -r--r--r--  1 j.d.ruiter domain users  312 Oct 26 13:24 Rd2pdf
4308740361 -r--r--r--  1 j.d.ruiter domain users  359 Oct 26 13:24 Rdconv
4303843916 -r--r--r--  1 j.d.ruiter domain users  258 Oct 26 13:24 Rdiff
4303843915 -r--r--r--  1 j.d.ruiter domain users  158 Oct 26 13:24 REMOVE
4308815654 -r--r--r--  1 j.d.ruiter domain users  310 Oct 26 13:24 Rprof
4308740369 -r-xr-xr-x  1 j.d.ruiter domain users  14K Oct 26 13:24 Rscript
4306613929 -r--r--r--  1 j.d.ruiter domain users 4.1K Oct 26 13:24 rtags
4308740362 -r--r--r--  1 j.d.ruiter domain users  155 Oct 26 13:24 SHLIB
4310048685 -r--r--r--  1 j.d.ruiter domain users  318 Oct 26 13:24 Stangle
4306924646 -r--r--r--  1 j.d.ruiter domain users  316 Oct 26 13:24 Sweave
```

**Comment by thriqon** [comment]
OK, this seems to be a similar, albeit not identical problem to mine ;-) It has the same origins though: Homebrew trying to be smarter than it is. Am I right to assume that the `config` file does not have a shebang? (`#!/bin/bash`)?

**Comment by jrderuiter** [comment]
Jep.

```{bash}
## config -- Simple shell script to get the values of basic R configure
## variables, or the header and library flags necessary for linking
## against R.
##
## Usage:
##   R CMD config [options] [VAR]
```

**Comment by sjackman** [comment]
I ran into this bug as well.
I'm on vacation in Thailand until the new year. Please bump this thread after then. Sorry for the delay.

**Comment by jwhite007** [comment]
I'm running into a different, albeit related issue when I try to install packages within R with "install.packages('<package name>')". I get...

/toolbox/NGS/.linuxbrew/Cellar/r/3.2.3/lib/R/bin/Rcmd: line 62: exec: INSTALL: not found

INSTALL is in /toolbox/NGS/.linuxbrew/Cellar/r/3.2.3/lib/R/bin/, the same dir as Rcmd.

**Comment by tseemann** [comment]
I just encountered this problem on 3.2.4, so i'm bumping @sjackman !

**Comment by sjackman** [comment]
The workaround is super simple. I'm not sure why this bug doesn't affect Mac OS.
```sh
chmod +x `brew --prefix r`/lib/R/bin/*
```
Adding this line to the `def install` script won't help, because the problem is that the executable bit is being removed by `clean_dir` which removes the executable bit from files that aren't `ELF` and don't have a `#!` line. Adding a `skip_clean` directive may work.
```ruby
skip_clean "lib/R/bin"
```
As a last ditch, adding something like the following to `post_install` should work
```
chmod "+x", Dir[lib/"R/bin/*"]
```

**Comment by sjackman** [comment]
On Mac OS, these executables are installed to
`R.framework/Versions/3.2/Resources/bin`
My best guess is that these framework directories are spared the rampaging `clean_dir` by default on Mac OS.

**Comment by sjackman** [comment]
@tseemann Can you try out this untested patch?
```diff
  # Do not remove executable permission from these scripts.
  # See https://github.com/Linuxbrew/linuxbrew/issues/614
  skip_clean "lib/R/bin" unless OS.mac?
```

**Comment by sjackman** [comment]
Woops. I accidentally fat-fingered and pushed this patch to https://github.com/Homebrew/homebrew-science/commit/32b38d646ea6d34f48a89787547c2d4f9969d9f6. I mean to push a pull request. I'll test it now and hopefully it works…
