### ISSUE TITLE
installing mongoose error: pkg-config not present or broken 

### ISSUE THREAD

**Issue by pshdong** [Linuxbrew/linuxbrew#623]
I'm trying to install mongoose by linuxbrew:

 % brew install mongoose                      [11:53 AM]
==> Installing dependencies for mongoose: makedepend, zlib, openssl
==> Installing mongoose dependency: makedepend
Error: /home/dps/.linuxbrew/opt/pkg-config not present or broken
Please reinstall pkg-config. Sorry :(

%  uname -a                                  [12:01 AM]
Linux dps-LENOVO-SHOU 3.13.0-66-generic #108-Ubuntu SMP Wed Oct 7 15:20:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dunn** [comment]
Could you post `brew gist-logs mongoose`? Thanks!

**Comment by sjackman** [comment]
This is a known bug that I'm working on fixing. The workaround is
```
brew install pkg-config mongoose
```
