### ISSUE TITLE
PDF2htmlex build fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by pdurusau** [Linuxbrew/linuxbrew#633]
Built finds gcc but then reports "checking whether the C compiler works... no" Gist URL below. 

https://gist.github.com/anonymous/058e0fb1d853e7566487

**Comment by rwhogg** [comment]
Can you try `brew install gcc` and then try building again with Homebrew's GCC 5 (`brew install pdf2htmlex --cc=gcc-5`)?

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#141
