### ISSUE TITLE
./jsoncpp_test: error while loading shared libraries: libjsoncpp.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jrgreene** [Linuxbrew/linuxbrew#659]
Hi I was trying to install jsoncpp and the build process always fails and I have no idea why.

Here is a gist:
https://gist.github.com/anonymous/2d1dba55d994a006f3f8

Update:
I was able to fix the problem above by running the cmake and make install commands myself after downloading the source. I thought I was out of the fire, but then the next next thing I tried to install ran into another error.

Here in the next gist:
https://gist.github.com/edc4b3a408bb9d28d69a

Why is linuxbrew having so much trouble compiling things? Am I doing something wrong?

**Comment by sjackman** [comment]
I'm traveling until the new year. If you haven't yet found a workaround or solution for this issue, please bump this thread after then. Sorry for the delay.

**Comment by sjackman** [comment]
Does this issue still affect you? Please reopen this issue if it does.
