### ISSUE TITLE
brew gist-logs does not work

### ISSUE THREAD

**Issue by Rudloff** [Linuxbrew/linuxbrew#673]
It gives me this error:
```Error: HTTP 404 Not Found (expected 201)```

**Comment by sjackman** [comment]
I'm on vacation until the new year. If this issue is still a problem for you after then, please bump this thread. Sorry for the delay.

**Comment by eallik** [comment]
also experiencing exactly the same problem.

**Comment by sjackman** [comment]
@DomT4 Any idea why brew gist-log would not work?

**Comment by DomT4** [comment]
Related to this possibly: https://github.com/Homebrew/homebrew/issues/39864

**Comment by sjackman** [comment]
Ah, confusing that it gives a 404 rather than a 403, but that's a helpful lead.

**Comment by retokromer** [comment]
Perhaps this may be useful: on different Linuxes it works fine for me, giving
https://gist.github.com/cc481221830ac4933e8f
[I experience troubles on Mac, but that's are for sure my attempts to bypass that horrible Xcode.]

**Comment by iggyvolz** [comment]
Try running brew gist-logs without a token, or with a token that has gist rights?

**Comment by Rudloff** [comment]
Oh, you're right, I needed a token with gist rights. Thanks!

**Comment by sjackman** [comment]
To fix this error, go to https://github.com/settings/tokens
Select `edit` for your `HOMEBREW_GITHUB_API_TOKEN`
Enable the checkbox for `gist`
Select `Update token`
