### ISSUE TITLE
brew doctor fails to see bin path because of symlink

### ISSUE THREAD

**Issue by albertz** [Linuxbrew/linuxbrew#681]
https://gist.github.com/anonymous/9d9667f6d3f9c50c1283#file-doctor-out

I have `/u/zeyer/.linuxbrew/bin` in my `PATH` which is the same as `/work/asr2/zeyer/linuxbrew/bin` (because `/u/zeyer/.linuxbrew` is a symlink).

**Comment by sjackman** [comment]
I'm on vacation until the new year. If this issue is still a problem for you after then, please bump this thread. Sorry for the delay.

**Comment by albertz** [comment]
`brew doctor` still reports this problem. E.g.:

```

Warning: Homebrew's bin was not found in your PATH.
Consider setting the PATH for example like so
    echo 'export PATH="/work/asr2/zeyer/linuxbrew/bin:$PATH"' >> ~/.zshrc

Warning: You have a non-Homebrew 'pkg-config' in your PATH:
  /u/zeyer/.linuxbrew/bin/pkg-config
```

`/u/zeyer/.linuxbrew` is a symlink to `/work/asr2/zeyer/linuxbrew`.

**Comment by sjackman** [comment]
Can you instead add `/work/asr2/zeyer/linuxbrew/bin` to your `PATH`?

**Comment by albertz** [comment]
Yes I could but I would like to be able to move it later to some other place, that's why I use the symlink and from everywhere I refer to it as `/u/zeyer/.linuxbrew`.

Also, I think that Homebrew/Linuxbrew should be able to detect such cases.

**Comment by sjackman** [comment]
You can submit a pull request against the `brew doctor` check if you're inclined.
