### ISSUE TITLE
git: directory not empty

### ISSUE THREAD

**Issue by albertz** [Linuxbrew/linuxbrew#682]
https://gist.github.com/anonymous/fdad385fd98a7c662433

```
zeyer@sulfid /w/a/z/linuxbrew> brew install git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.6.1.tar.xz
Already downloaded: /u/zeyer/.cache/Homebrew/git-2.6.1.tar.xz
==> make install prefix=/work/asr2/zeyer/linuxbrew/Cellar/git/2.6.1 sysconfdir=/work/asr2/zeyer/linuxbrew/etc CC=/usr/bin/gcc-4.6 CFLAGS=-Os -w -pipe -march=co
==> make CC=/usr/bin/gcc-4.6 CFLAGS=-Os -w -pipe -march=core2 LDFLAGS=-L/work/asr2/zeyer/linuxbrew/lib -Wl,-rpath,/work/asr2/zeyer/linuxbrew/lib
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.6.1.tar.xz
Already downloaded: /u/zeyer/.cache/Homebrew/git--man-2.6.1.tar.xz
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.6.1.tar.xz
Already downloaded: /u/zeyer/.cache/Homebrew/git--html-2.6.1.tar.xz
Error: Directory not empty - /work/asr2/zeyer/linuxbrew/Cellar/git/2.6.1/lib/perl/5.14.2
```

Not sure what this means.

**Comment by albertz** [comment]
With `brew install -vd git`:

```
==> Verifying git--html-2.6.1.tar.xz checksum
/usr/lib/ruby/1.8/fileutils.rb:264:in `rmdir'
Errno::ENOTEMPTY: Directory not empty - /work/asr2/zeyer/linuxbrew/Cellar/git/2.6.1/lib/perl/5.14.2
1. raise
2. backtrace
3. shell
Choose an action: 2
/usr/lib/ruby/1.8/fileutils.rb:264:in `rmdir'
/usr/lib/ruby/1.8/fileutils.rb:264:in `rmdir'
/usr/lib/ruby/1.8/fileutils.rb:263:in `each'
/usr/lib/ruby/1.8/fileutils.rb:263:in `rmdir'
/work/asr2/zeyer/linuxbrew/Library/Formula/git.rb:155:in `install'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/debrew.rb:22:in `install'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/debrew.rb:97:in `debrew'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/debrew.rb:22:in `install'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/build.rb:130:in `install'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/formula.rb:906:in `brew'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/formula.rb:1486:in `stage'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/resource.rb:91:in `unpack'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/resource.rb:88:in `unpack'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/resource.rb:81:in `stage'
(__FORWARDABLE__):3:in `__send__'
(__FORWARDABLE__):3:in `stage'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/formula.rb:1477:in `stage'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/formula.rb:902:in `brew'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/build.rb:108:in `install'
/work/asr2/zeyer/linuxbrew/Library/Homebrew/build.rb:177
```

**Comment by sjackman** [comment]
I'm on vacation until the new year. If this issue is still a problem for you after then, please bump this thread. Sorry for the delay.

**Comment by vol7ron** [comment]
This is the output I get when I do `brew install git` or `brew update`

Output:
>==> Installing git
>==> Installing git
>==> Installing git
> *there's a lot of theses, which I've cut out, but you get the idea*
>==> Installing git
>==> Installing git
>==> Installing git
>
>Error: stack level too deep
>Please report this bug:
>   
> https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
>/usr/lib/ruby/1.9.1/set.rb:221
>:~$ brew doctor
>Please note that these warnings are just used to help the Homebrew maintainers
>with debugging if you file an issue. If everything you use Homebrew for is
>working fine: please don't worry and just ignore them. Thanks!
>
>Warning: Git could not be found in your PATH.
>Homebrew uses Git for several internal functions, and some formulae use Git
>checkouts instead of stable tarballs. You may want to install Git:
>  brew install git


Basically, it seems git cannot be installed via homebrew, or at least linuxbrew.  I'm not sure if this is by design, since I think git is also a dependency, or at least integrated into homebrew in some way.

**Comment by sjackman** [comment]
It looks like perhaps there's a cyclic dependency. Are there other formula in the cycle, or just git?

**Comment by vol7ron** [comment]
Just git in a new install of VirtualBox Ubuntu instance.

**Comment by retokromer** [comment]
A workaround for @vol7ron until fixed: When you install first git without brew (sudo apt-get install git), it doesn’t cycle – and works.
An information for @sjackman : Months ago the installation worked well with brew.

**Comment by vol7ron** [comment]
@retokromer yes, I can install *git* manually via *apt-get* or through the Ubuntu App store, but thought this was worth reporting as an issue.  

### Issue 2
Once *git* is installed (there are no updates from `brew update` and `brew doctor` returns nothing), I have tried to install *git* via homebrew (e.g., `brew install git`).  This yields another error when trying to make *tcl-tk*.  I'm guessing the X11 library is not loaded, since it could not find the path.

```
In file included from /tmp/tcl-tk--tk20151231-23694-1sitydr/tk8.6.4/unix/../generic/tkPort.h:21:0,
                 from /tmp/tcl-tk--tk20151231-23694-1sitydr/tk8.6.4/unix/../generic/tkInt.h:19,
                 from /tmp/tcl-tk--tk20151231-23694-1sitydr/tk8.6.4/unix/../generic/tkStubLib.c:14:
/tmp/tcl-tk--tk20151231-23694-1sitydr/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
make: *** [tkStubLib.o] Error 1
==> Formula
Tap: homebrew/homebrew-dupes
Path: ~/.linuxbrew/Library/Taps/homebrew/homebrew-dupes/tcl-tk.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/linuxbrew.git
HEAD: bb453ad33892df0d5560a177890a94810ecc71af
Last commit: 3 weeks ago
HOMEBREW_PREFIX: ~/.linuxbrew
HOMEBREW_REPOSITORY: ~/.linuxbrew
HOMEBREW_CELLAR: ~/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: single-core 64-bit 6
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: N/A
System Ruby: 1.9.3-p484 => /usr/bin/ruby1.9.1
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby1.9.1
Java: N/A
==> ENV
CC: /usr/bin/gcc-4.8
CXX: /usr/bin/g++-4.8
OBJC: /usr/bin/gcc-4.8
OBJCXX: /usr/bin/g++-4.8
CFLAGS: -Os -w -pipe -march=core2
CXXFLAGS: -Os -w -pipe -march=core2
CPPFLAGS: -isystem/~/.linuxbrew/include
LDFLAGS: -L/~/.linuxbrew/lib -Wl,-rpath,/~/.linuxbrew/lib
MAKEFLAGS: -j1
CMAKE_PREFIX_PATH: ~/.linuxbrew
PKG_CONFIG_LIBDIR: ~/.linuxbrew/lib/pkgconfig
PATH: ~/.linuxbrew/Cellar/tcl-tk/8.6.4/bin:~/.linuxbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:~/.linuxbrew/Library/ENV/scm

Error: homebrew/dupes/tcl-tk 8.6.4 did not build
Logs:
     ~/.cache/Homebrew/Logs/tcl-tk/05.configure
     ~/.cache/Homebrew/Logs/tcl-tk/06.make
     ~/.cache/Homebrew/Logs/tcl-tk/04.make
     ~/.cache/Homebrew/Logs/tcl-tk/01.configure
     ~/.cache/Homebrew/Logs/tcl-tk/02.make
     ~/.cache/Homebrew/Logs/tcl-tk/03.make
```

_**Note:** I replaced all instances of `home/<username>` and `/home/<username>` above, with `~`_

---

### Solution

In order to address this, I've tried to `brew install x11vnc`, which I was hoping would have the necessary libraries.  It did not.  `sudo apt-get install xauth` also did not work, since it seemed to already be installed.

The solution seemed to be installing the x11 dev: `sudo apt-get install libx11-dev`.  After doing this, linuxbrew failed on another error (curl was not installed).  So, I needed to install *curl*, which I could do through *brew*.

```
sudo apt-get install libx11-dev
brew install curl
```

This is worth mentioning, because it seems there are a lot of dependencies that need to available before *git* can be installed through linuxbrew and not everyone may have access to *sudo*, which is needed.  Because *git* is so prevalent to the homebrew/linuxbrew userbase and Ubuntu is one of the most popular Linux distros, I would think we'd want to have this fixed.

**Comment by retokromer** [comment]
@vol7ron My remark was just meant as a provisory workaround, which I quickly tested on a test machine, where I can then install all the ca. 12-15 formulas we are using for work without problems. On all our production computers git has been installed by brew months ago, and also updated. There *is* indeed something broken now!

**Comment by vol7ron** [comment]
@Reto thank you for confirming this. I'm also having issues installing a gcc brew, so I don't know what is up

**Comment by sjackman** [comment]
Thanks for reporting this bug. I'll look into it in a couple of days once I've returned from vacation.

**Comment by vol7ron** [comment]
You should be enjoying your vacation and not even checking your mail ;)

**Comment by sjackman** [comment]
Very true!

**Comment by sjackman** [comment]
See also #700

**Comment by sjackman** [comment]
See https://github.com/sjackman/docker-linuxbrew/blob/91f509802167f10a1ba9394c3750197b9a6eb9b6/linuxbrew-standalone/Dockerfile#L6-L8

Try
```sh
# Install git without tcl-tk to prevent the error:
# Tapping homebrew/dupes. You must: brew install git
RUN brew install git --with-brewed-curl --with-brewed-openssl --without-tcl-tk
```

**Comment by al-the-x** [comment]
Did any of this help solve your problem @albertz? I'm having the same problem in my environment: `Error: Directory not empty` on the Perl install directory. The `git` package doesn't seem to install after throwing that error...

**Comment by albertz** [comment]
I did a `brew update` and then tried `brew install git` again. It still fails but maybe that is an unrelated error. It has some more dependencies now and fails on one of them.

```
$ brew install git
==> Installing dependencies for git: binutils, linux-headers, glibc, openssl, pkg-config, curl
...
==> Installing git dependency: linux-headers
==> Downloading https://linuxbrew.bintray.com/bottles/linux-headers-3.15.9.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring linux-headers-3.15.9.x86_64_linux.bottle.tar.gz
/work/asr2/zeyer/linuxbrew/Cellar/linux-headers/3.15.9: 731 files, 3.3M
==> Installing git dependency: glibc
==> Downloading http://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
==> Downloading from http://www.gutscheinrausch.de/mirror/gnu/glibc/glibc-2.19.tar.bz2
######################################################################## 100.0%
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/work/asr2/zeyer/linuxbrew/Ce
Last 15 lines from /u/zeyer/.cache/Homebrew/Logs/glibc/01.configure:
checking for gmsgfmt... no
checking for msgfmt... msgfmt
checking version of msgfmt... 0.18.1, ok
checking for makeinfo... makeinfo
checking version of makeinfo... 4.13, ok
checking for sed... sed
checking version of sed... 4.2.1, ok
checking for gawk... gawk
checking version of gawk... 4.0.1, ok
checking for nm... nm
checking LD_LIBRARY_PATH variable... contains current directory
configure: error: 
*** LD_LIBRARY_PATH shouldn't contain the current directory when
*** building glibc. Please change the environment variable
*** and run configure again.
```

The error is not because of my env:

```
$ echo $LD_LIBRARY_PATH
/usr/lib32  /usr/local/lib  /usr/local/cuda-6.5/lib64
```

I also wonder, a whole new glibc, can't it just use the system glibc?

**Comment by albertz** [comment]
I reported that separately: #807

**Comment by albertz** [comment]
@al-the-x The options suggested (`--with-brewed-curl --with-brewed-openssl --without-tcl-tk`) will not remove the Glibc dependecy, so those don't help me.

**Comment by sjackman** [comment]
I'm experimenting with rolling out bottles (precompiled binaries) on Linuxbrew, and that requires updating `glibc` on older systems with `glibc` < 2.19. See #380. You're my guinea pig. Congratulations? If you wish to opt out of being my guinea pig, use `brew install -s git` or `export HOMEBREW_BUILD_FROM_SOURCE=1`.

**Comment by sjackman** [comment]
@al-the-x Please report the error message that you're seeing and `brew gist-logs git`

**Comment by al-the-x** [comment]
@sjackman Will do.

**Comment by zbeekman** [comment]
I too have the dreaded:

```
==> Verifying git--html-2.7.2.tar.xz checksum
Error: Directory not empty - /home/vagrant/.linuxbrew/Cellar/git/2.7.2/lib/perl/5.14.2
```

Error. I suspect it comes from `git.rb`:

```
vagrant@precise64:~$ grep -A 4 -B 4 'rmdir' .linuxbrew/Library/Formula/git.rb
      # Remove perllocal.pod, which conflicts with the perl formula.
      # I don't know why this issue doesn't affect Mac.
      pod = Pathname.new pod
      rm pod
      rmdir [pod.dirname, pod.dirname.dirname]
    end
  end

  def caveats; <<-EOS.undent
```

**Comment by sjackman** [comment]
The file being removed is named something like `lib/5.22.1/x86_64-linux-thread-multi/perllocal.pod`
In your case there must be other files installed as well.
Please run `brew install git -dv` and after the error ask for a shell prompt, then report the files found in the offending directory.
The following untested patch may work for you.
```diff
diff --git a/Library/Formula/git.rb b/Library/Formula/git.rb
index 75e012c..9f3d2c8 100644
--- a/Library/Formula/git.rb
+++ b/Library/Formula/git.rb
@@ -155,9 +155,7 @@ class Git < Formula
     if pod != nil
       # Remove perllocal.pod, which conflicts with the perl formula.
       # I don't know why this issue doesn't affect Mac.
-      pod = Pathname.new pod
-      rm pod
-      rmdir [pod.dirname, pod.dirname.dirname]
+      rm_r Pathname.new(pod).dirname.dirname
     end
   end
 
```

**Comment by zbeekman** [comment]
Thanks for your help.. I think your other comment on #380 has just made my life so much simpler... I was having issues with building glibc but through your guidance and some vagrant testing I think I'm up and running.

**Comment by sjackman** [comment]
Great! Glad to hear it.

**Comment by albertz** [comment]
`brew install -s git` worked now for me. I cannot use the bottled version because of #898.
