### ISSUE TITLE
brew config output

### ISSUE THREAD

**Issue by retokromer** [Linuxbrew/linuxbrew#684]
My OS linuX version is 0 ;-)

![linuxbrew](https://cloud.githubusercontent.com/assets/3246607/11768295/a5b03294-a1c8-11e5-9ec2-4a8f69c1c811.png)

Is it useful to fix the <code>brew config</code> output, or am I the only one who noticed some incoherences?

**Comment by sjackman** [comment]
Yes, the output could be tidied up for Linuxbrew. In particular, it should show the compiler path and version. I'm on vacation until the new year.

**Comment by retokromer** [comment]
This is funny too: same from reference and to reference:

![screenshot 2016-01-03 09 23 08](https://cloud.githubusercontent.com/assets/3246607/12077934/61c8342a-b1fc-11e5-86f0-96bcc7514008.png)

**Comment by sjackman** [comment]
The output of `brew config` is now much improved for Linuxbrew.
```
…
Kernel: Linux 2.6.18-371.1.2.el5 x86_64 GNU/Linux
OS: CentOS release 5.11 (Final)
OS glibc: 2.5
OS gcc: 4.1.2
Linuxbrew glibc: 2.19
Linuxbrew gcc: 5.3.0
Clang: 3.6 build 0
…
```
