### ISSUE TITLE
boost: really need boost installer that works and has boost.log

### ISSUE THREAD

**Issue by ahundt** [Linuxbrew/linuxbrew#687]
I've been trying to get a boost installer that works and has boost.log running using the system gcc, but haven't had any luck.

I made this tree to try and do it:
https://github.com/ahundt/linuxbrew/tree/robone

Here I'm merging a recent pull request from boost 1.60. 1.59 has bugs in the compilation of boost.log as well which are fixed in 1.60 (or a 1.59 patch that is available) so I'd prefer to used the unpatched bug-fixed version.

But it fails to build, passing `-ftemplate-limit=120` (or something close to that) that I believe are a clang construct not supported by GCC.

The current scripts disable it if there is gcc, and I'd like to use the system gcc on my ubuntu 14.04 non-standalone install so that I can integrate with code using existing installed libraries if at all possible. Is there any chance I could get help with making this work?

anyone who can help would be very much appreciated. Simply modifying the current master script to disable the log component seems to crash on boost-wave, but I'm not sure that can be disabled from command line. I'm not using wave. Thanks for your consideration/help.

Perhaps my best option is to just disable boost.log in my code and use the defaults that work without it....

**Comment by sjackman** [comment]
What version of system gcc are you using? What's the problem with boost.log? Please post a build log. I'm on vacation until the new year. Sorry for delays in my response.

**Comment by ahundt** [comment]
It is the default with 14.04. I'll try to get a log tomorrow

**Comment by sjackman** [comment]
What is the default version of GCC with Ubuntu 14.04?

**Comment by ahundt** [comment]
gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

**Comment by sjackman** [comment]
Does boost 1.59 build correctly for you with gcc 4.8.4? If not, please report `brew gist-logs boost`

**Comment by sjackman** [comment]
See also #643

**Comment by ahundt** [comment]
I believe there was another compiler error after that change

**Comment by ahundt** [comment]
I believe this is done

**Comment by sjackman** [comment]
Glad to hear it. Thanks for the update, Andrew.
