### ISSUE TITLE
libxml2 failed to install

### ISSUE THREAD

**Issue by vol7ron** [Linuxbrew/linuxbrew#695]
**Host:** VirtualBox Ubuntu 14.04.1
**Software:**
```
$ brew list | sort
ack
curl
expat
gawk
gdbm
git
git-flow
gzip
jpeg
libtool
libuuid
libyaml
m4
make
makedepend
ncurses
node
openssl
perl
pkg-config
python
python3
readline
ruby
sqlite
tcl-tk
texinfo
tree
unzip
wget
x11vnc
xz
zlib
```

### First error mesage
```
$ brew install --with-python libxml2
==> Downloading http://xmlsoft.org/sources/libxml2-2.9.3.tar.gz
Already downloaded: ~/.cache/Homebrew/libxml2-2.9.3.tar.gz
==> ./configure --prefix=~/.linuxbrew/Cellar/libxml2/2.9.3 --with-python --
==> make
Last 15 lines from ~/.cache/Homebrew/Logs/libxml2/02.make:
./.libs/libxml2.so: undefined reference to `deflate'
./.libs/libxml2.so: undefined reference to `inflateInit2_'
./.libs/libxml2.so: undefined reference to `inflate'
./.libs/libxml2.so: undefined reference to `gzwrite'
./.libs/libxml2.so: undefined reference to `crc32'
./.libs/libxml2.so: undefined reference to `deflateEnd'
./.libs/libxml2.so: undefined reference to `gzdopen'
./.libs/libxml2.so: undefined reference to `deflateInit2_'
./.libs/libxml2.so: undefined reference to `gzread'
collect2: error: ld returned 1 exit status
make[2]: *** [xmllint] Error 1
make[2]: Leaving directory `/tmp/libxml220160101-8153-jsjbl1/libxml2-2.9.3'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/libxml220160101-8153-jsjbl1/libxml2-2.9.3'
make: *** [all] Error 2
```

This required `brew install gzip`, which required `brew install texinfo` and `brew install make`.  After performing these, the error message was a little lighter:

### After gzip/texinfo/make installed
```
==> make
Last 15 lines from /home/devman/.cache/Homebrew/Logs/libxml2/02.make:
./.libs/libxml2.so: undefined reference to `gzwrite'
./.libs/libxml2.so: undefined reference to `crc32'
./.libs/libxml2.so: undefined reference to `deflateEnd'
./.libs/libxml2.so: undefined reference to `gzdopen'
./.libs/libxml2.so: undefined reference to `deflateInit2_'
./.libs/libxml2.so: undefined reference to `gzread'
collect2: error: ld returned 1 exit status
Makefile:1115: recipe for target 'xmllint' failed
make[2]: *** [xmllint] Error 1
make[2]: Leaving directory '/tmp/libxml220160101-22441-1lli9q8/libxml2-2.9.3'
Makefile:1438: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/libxml220160101-22441-1lli9q8/libxml2-2.9.3'
Makefile:857: recipe for target 'all' failed
make: *** [all] Error 2
```

I tried `brew install libtool`, which required `brew install m4`; but cannot find how to update gzdopen/deflate/etc (I have zlib already installed).

Any ideas? ... Other than installing gcc, not sure what else could affect this.  I'm hesitant to do any *apt-get install* as I would like to avoid it.

**Comment by dunn** [comment]
Can you post the `brew gist-logs libxml2` after each failure?

It's also worth noting that Linuxbrew is currently a ways behind Homebrew; it should become up-to-date again this week.

**Comment by vol7ron** [comment]
https://gist.github.com/vol7ron/ee184d5173227e547b42

**Comment by vol7ron** [comment]
I was able to successfully make/install after I ran the following command:

    sudo apt-get zlibc zlib1g zlib1g-dev

Of note, I had alread `brew install zlib`, so I'm not sure what else apt-get would be retrieving, that wasn't installed with brew.  Worth note, this is linuxbrew and not homebrew (if there is a distinction).

Can I get some confirmation that there is an issue and this shouldn't have happened, since I had already issued `brew install zlib`?  I'm trying to set up several VMs with little apt-get intervention.

**Comment by dunn** [comment]
> Can I get some confirmation that there is an issue and this shouldn't have happened, since I had already issued brew install zlib?

I'm not sure; I'm not on the Linuxbrew team.  The primary maintainer will be back this week, though.

**Comment by vol7ron** [comment]
Understood. In general, aside from some installation issues it seems to be working comparable to homebrew.

I've never tried using it from the start on a vanilla install of Ubuntu LTS. These issues I'm reporting is more of a notification, than a demand to get something patched immediately.

I imagine linuxbrew has much more complexity, since Macs come installed with certain languages, daemons, and utilities; coupled with the fact that there's only a few number of OSXes, many more versions of Linux. So Linuxbrew is may be harder to maintain for initial setup.

**Comment by sjackman** [comment]
Thanks for the bug report. Yes, this error is not expected. I'll look into it once I'm back from vacation.

**Comment by Npasic1** [comment]
u back?

**Comment by vol7ron** [comment]
The only way I'll be able to test is to spin up another VM and start from scratch again, but let me know if help is needed.  Otherwise, this can be closed from my perspective (and I suppose reopened when someone else encounters the issue if it reappears)

**Comment by sjackman** [comment]
Coincidentally, I ran into this issue myself recently. It should have been fixed in
181d0e9 libxml2: Fix --with-python for Linuxbrew
