### ISSUE TITLE
homebrew/python/scipy: Lapack_src

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/linuxbrew#727]
I'm attempting an install of scipy via pip in the brew-installed python. Numpy is claiming that it can't find lapack or blas resources even though I've installed lapack and openblas with brew. I could point numpy to them with the environment variables BLAS and LAPACK_SRC, however I don't find the lapack source in the brew install. Any suggestions on getting this to work? Thanks.

**Comment by sjackman** [comment]
I'm going to move your issue to Homebrew-science. I think you'll have better luck getting your question answered there. Please post the output of `brew gist-logs homebrew/python/scipy`.

**Comment by sjackman** [comment]
This issue was moved to Homebrew/homebrew-science#3238
