### ISSUE TITLE
Boost: Building boost on machines with large numbers of cores

### ISSUE THREAD

**Issue by jreeder** [Linuxbrew/linuxbrew#734]
Boost's b2 build system will only accept numbers between 1 and 256 for the -j parameter. I've attached a patch that fixes the boost.rb file. This would probably also apply to the other boost formulas. This is a naive fix and it might be better to cap ENV.make_jobs instead. I don't know enough to make that judgement. 

```patch
diff --git a/Library/Formula/boost.rb b/Library/Formula/boost.rb
index 95948d6..22e307a 100644
--- a/Library/Formula/boost.rb
+++ b/Library/Formula/boost.rb
@@ -114,7 +114,7 @@ class Boost < Formula
     args = ["--prefix=#{prefix}",
             "--libdir=#{lib}",
             "-d2",
-            "-j#{ENV.make_jobs}",
+            "-j#{ENV.make_jobs < 256 ? ENV.make_jobs : 256}",
             "--layout=tagged",
             "--user-config=user-config.jam",
             "install"]
```

**Comment by sjackman** [comment]
Interesting bug indeed. Have you reported this bug upstream to the authors of boost?

**Comment by sjackman** [comment]
I'd rather not merge this fix here in Linuxbrew, but you can submit it upstream to Homebrew/homebrew. They may not accept it because I don't think there are any Mac machines with more than 256 cores.

**Comment by jreeder** [comment]
No I haven’t reported it anywhere else yet. I’ll report it to the boost
devs, but I won’t bother with the homebrew upstream. Unless Apple gets
serious about multi-core, this will never affect anyone over there.

**Comment by sjackman** [comment]
Thanks for the bug report, John. Here's a workaround:
```sh
HOMEBREW_MAKE_JOBS=256 brew install boost
```
