### ISSUE TITLE
gtk+3 builds XQuartz backend and not X11 backend

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#739]
gtk+3 fails to build because it attempts to build the XQuartz backend and not the X11 backend. It does not appear to have been solved by #64.

I'm working on a PR for this; hopefully I'll be able to submit it soon.

**Comment by rwhogg** [comment]
Okay, I've mostly fixed the GTK+3 build, but in doing so discovered that the cairo is not being built with X11. I'll file a separate issue to fix cairo and supply a PR for that too.

**Comment by sjackman** [comment]
Fixed by #741
