### ISSUE TITLE
roswell: build failure because of m4 not present

### ISSUE THREAD

**Issue by snmsts** [Linuxbrew/linuxbrew#742]
I'm not sure why but error occurs because of ``m4``'s absence.
https://travis-ci.org/roswell/roswell/jobs/104415062

my recipe is here.
https://github.com/roswell/homebrew-roswell/blob/master/roswell.rb

Roswell depends on autoconf and I believe autoconf will introduce ``m4`` automatically
https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Formula/autoconf.rb

What can I do for this error?

**Comment by sjackman** [comment]
https://travis-ci.org/roswell/roswell/jobs/104415062#L1050-L1052
```
==> Installing roswell/roswell/roswell dependency: automake
Error: /home/travis/.linuxbrew/opt/m4 not present or broken
Please reinstall homebrew/dupes/m4. Sorry :(
```

The automake dependency on autoconf is a `:run` dependency, which I've actually never seen before.
```
  depends_on "autoconf" => :run
```

I'll have to look into it, but it looks for your log as though autoconf is never being installed, at least I don't see it mentioned anywhere in the log.

```
==> Installing dependencies for roswell/roswell/roswell: xz, automake
```

Is autoconf already installed? I'm at a loss as to why it's not being installed.

**Comment by snmsts** [comment]
Thank you for your response.

This is the log when it could successfuly build.
https://travis-ci.org/roswell/roswell/jobs/103271959#L239

the recipe I'm tapping is not having change this week. :(

**Comment by sjackman** [comment]
https://travis-ci.org/roswell/roswell/jobs/103271959#L239
```
==> Installing dependencies for roswell/roswell/roswell: xz, homebrew/dupes/m4, autoconf, automake
```

That looks more like it. Is this issue resolved then, or is that an older log file?

**Comment by snmsts** [comment]
it is old log

**Comment by sjackman** [comment]
Does this workaround work?
```sh
brew install m4 autoconf automake roswell/roswell/roswell
```

**Comment by snmsts** [comment]
works fine with the workaround.
https://travis-ci.org/roswell/roswell/jobs/104580886

**Comment by sjackman** [comment]
It appears the `autoconf` dependency of `roswell` is being dropped. I couldn't say why. It's a `:build` dependency and `roswell` does not provide a bottle, so the build dependencies should be installed. So, beyond the workaround, I have no solution for you right now.

**Comment by sjackman** [comment]
I'm not able to reproduce this issue in a clean Docker `sjackman/linuxbrew` instance:

```
❯❯❯ docker run -it sjackman/linuxbrew
$ COLUMNS=120 brew install roswell/roswell/roswell
==> Installing roswell from roswell/roswell
==> Installing dependencies for roswell/roswell/roswell: xz, homebrew/dupes/m4, autoconf, automake
==> Installing roswell/roswell/roswell dependency: xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.2.tar.gz
```

**Comment by sjackman** [comment]
I'm able to reproduce this error with `brew install rtorrent`.

**Comment by sjackman** [comment]
I found a workaround. Tap `homebrew/dupes` before installing the formula you want. This is definitely a bug.

```
❯❯❯ brew install rtorrrent
==> Installing dependencies for rtorrent: automake, libtool, pkg-config, cppunit, makedepend, zlib, openssl, libtorrent
```

```
❯❯❯ brew tap homebrew/dupes
❯❯❯ brew install rtorrent
==> Installing dependencies for rtorrent: homebrew/dupes/m4, autoconf, automake, libtool, pkg-config, cppunit, makedepend, zlib, openssl, libtorrent
```

**Comment by snmsts** [comment]
Oh Thanks!

**Comment by ginolon** [comment]
`brew tap homebrew/dupes`

works also for me... (rbenv) on Ubuntu.

Is this a bug?

**Comment by sjackman** [comment]
Yes, it's a bug.

**Comment by sjackman** [comment]
Reported upstream at #48834.

**Comment by sjackman** [comment]
Fixed thanks to @xu-cheng in https://github.com/Homebrew/homebrew/pull/48904
