### ISSUE TITLE
pod2man (wget dependency) not installing (404 Not Found)

### ISSUE THREAD

**Issue by vol7ron** [Linuxbrew/linuxbrew#743]
```
$ brew install wget
==> Installing dependencies for wget: pod2man
==> Installing wget dependency: pod2man
==> Downloading http://archives.eyrie.org/software/perl/podlators-4.04.tar.xz
==> Downloading from https://archives.eyrie.org/software/perl/podlators-4.04.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "pod2man"
Download failed: https://archives.eyrie.org/software/perl/podlators-4.04.tar.xz
```

I'm not sure why pod2man is a _wget_ dependency, but it looks like the download link is either not available or no longer exists.  I installed _wget_ a few weeks ago without any issue.

**Comment by tseemann** [comment]
The tarball no longer exists, the formula needs to be updated to 4.05 version from https://archives.eyrie.org/software/perl/ 

I am working on a pull request.

**Comment by vol7ron** [comment]
Would it make more sense to use https://archives.eyrie.org/software/perl/podlators.tar.gz (devoid of version) to avoid this from happening in the future?  Or is a version number required?

**Comment by tseemann** [comment]
A version number is required either in the .tar name (where it is auto detected), or as a `version` tag in the formula.   So when something updates, some work has to be done somewhere either way. The real issue is that the provider is deleting previous versions of the tar file when adding the new ones :-(

**Comment by tseemann** [comment]
Ihave an archived version of it, and the build fails anyway for me:

```
perl
Makefile.PL
PREFIX=/bio/linuxbrew/Cellar/pod2man/4.04
INSTALLSCRIPT=/bio/linuxbrew/Cellar/pod2man/4.04/bin
INSTALLMAN1DIR=/bio/linuxbrew/Cellar/pod2man/4.04/share/man/man1
INSTALLMAN3DIR=/bio/linuxbrew/Cellar/pod2man/4.04/share/man/man3

Only one of PREFIX or INSTALL_BASE can be given.  Not both.
```

Probably I have a newer version of the Maker module that comes with OS X ...

**Comment by tseemann** [comment]
@vol7ron Can you try this?

```
brew upgrade https://raw.githubusercontent.com/Linuxbrew/linuxbrew/podlators-4.05/Library/Formula/pod2man.rb
```

**Comment by sjackman** [comment]
The 404 error should be fixed upstream in Homebrew/homebrew.

@tseemann There is no particular tag for 404, just "build error".

**Comment by sjackman** [comment]
I'm going to close this issue. Please submit a pull request to Homebrew/homebrew resolving the 404. It will be fixed in Linuxbrew following the next weekly merge.

**Comment by vol7ron** [comment]
Sorry I never replied -- either I was in a pinch and had to manually fix this, or the issue resolved itself with the next brew update/upgrade.
