### ISSUE TITLE
Sonar builds OS X executables instead of Linux ones

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#750]
From sonar.rb:

```ruby
    # Delete native bin directories for other systems
    rm_rf Dir["bin/{aix,hpux,linux,solaris,windows}-*"]

    if MacOS.prefer_64_bit?
      rm_rf "bin/macosx-universal-32"
    else
      rm_rf "bin/macosx-universal-64"
    end

    # Delete Windows files
    rm_f Dir["war/*.bat"]
    libexec.install Dir["*"]

    if MacOS.prefer_64_bit?
      bin.install_symlink "#{libexec}/bin/macosx-universal-64/sonar.sh" => "sonar"
    else
      bin.install_symlink "#{libexec}/bin/macosx-universal-32/sonar.sh" => "sonar"
    end
  end
```

Note that the build itself succeeds, but when running `sonar console`, you get the following:

> Running SonarQube...
/home/bob/.linuxbrew/Cellar/sonar/5.3/libexec/bin/macosx-universal-64/./wrapper: 1: /home/bob/.linuxbrew/Cellar/sonar/5.3/libexec/bin/macosx-universal-64/./wrapper: Syntax error: word unexpected (expecting ")")

I can probably fix this myself; expect a patch sooner or later.

**Comment by sjackman** [comment]
Fixed by #751
