### ISSUE TITLE
libunique build fails due to OS X diagnostic check

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#753]
libunique fails to install because of the following check:

> Error: uninitialized constant Homebrew::Diagnostic::Checks::MacOS
Please report this bug:
    https://github.com/Homebrew/linuxbrew/wiki/troubleshooting
/home/bob/.linuxbrew/Library/Homebrew/diagnostic.rb:324:in `<class:Checks>'
/home/bob/.linuxbrew/Library/Homebrew/diagnostic.rb:72:in `<module:Diagnostic>'
/home/bob/.linuxbrew/Library/Homebrew/diagnostic.rb:7:in `<module:Homebrew>'
/home/bob/.linuxbrew/Library/Homebrew/diagnostic.rb:6:in `<top (required)>'
/home/bob/.linuxbrew/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/bob/.linuxbrew/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/bob/.linuxbrew/Library/Homebrew/cmd/install.rb:2:in `<top (required)>'
/home/bob/.linuxbrew/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/bob/.linuxbrew/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/bob/.linuxbrew/Library/brew.rb:25:in `require?'
/home/bob/.linuxbrew/Library/brew.rb:62:in `<main>'

I'll probably be able to fix this myself in a few days at the worst.

**Comment by rwhogg** [comment]
I was on the wrong branch. Closing, my apologies.

**Comment by sjackman** [comment]
No worries.
