### ISSUE TITLE
Git at version 1.9.1 not 2.7.0 ubunutu

### ISSUE THREAD

**Issue by jamesscholeyweb** [Linuxbrew/linuxbrew#757]
This may not be an issue as such but is there a reason linuxbrew installs git at 1.9.1 same as the default ubunutu repo version and not latest 2.7.0?

Many thanks in advance.

**Comment by maxim-belkin** [comment]
Linuxbrew installs git v2.7.0 for me...

**Comment by jamesscholeyweb** [comment]
Hmm interesting. My git version was 1.9.1 then installed with brew and
still 1.9.1 at first I thought it was my path being overridden but which
git points to my linuxbrew folder. I've just done a clean install on
another machine so will see what happens with that.

**Comment by retokromer** [comment]
Linuxbrew installs git 2.7.0 also on my side.

**Comment by maxim-belkin** [comment]
I bet this is due to hash. Try running `hash -r` after installing git with linuxbrew and see if "type -a git" returns linuxbrew's git first (it should appear at the top)

**Comment by jamesscholeyweb** [comment]
Thanks Maxim. Not home at moment bit will try this evening.

**Comment by jamesscholeyweb** [comment]
Nailed it Maxim. Thanks. Resetting hash did the trick. Should have realised.
