### ISSUE TITLE
Please add notes in README.md

### ISSUE THREAD

**Issue by C4Phone** [Linuxbrew/linuxbrew#759]
I fail to install anything using homebrew due to ./configure failure. And I found out that it was because my /tmp directory does not allow executable files.

Please add in README.md to remind people to change default temporary directory by adding the following lines into their .bashrc:
```bash
export HOMEBREW_TEMP=~/.local_tmp 
```

Thanks for your patience!

**Comment by sjackman** [comment]
Does `brew doctor` not report any errors? If so, this should be fixed by adding a `check_tmpdir_executable` test to `Library/Homebrew/diagnostic.rb`.

**Comment by sjackman** [comment]
Which distribution of Linux are you running?

**Comment by sjackman** [comment]
Fixed by 3ef02e64a1b484c6ff0388955496ba2b71074a08.
Can you please test that it has the desired effect? Running `brew doctor` should report
```
Warning: The directory /tmp does not permit executing programs.
It is likely mounted "noexec". Please add the following to your ~/.bashrc:
  export HOMEBREW_TEMP=~/tmp
```

**Comment by C4Phone** [comment]
Here is information about my Linux:
```
[~]$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.6 (Final)
Release:	6.6
Codename:	Final
```

Using the old version, ```brew doctor``` does not tell any error about tmpdir by default. Yes, with the new version ```brew doctor``` does report the information. Thanks!

**Comment by sjackman** [comment]
Great! Glad to hear it worked.

**Comment by sjackman** [comment]
What is the exact error message reported when you run
```sh
echo '#!/bin/sh' >/tmp/foo
chmod +x /tmp/foo
/tmp/foo
```

**Comment by C4Phone** [comment]
```bash
[~]$ echo '#!/bin/sh' > /tmp/foo
[~]$ chmod +x /tmp/foo
[~]$ /tmp/foo
-bash: /tmp/foo: Permission denied
[~]$ 
```

**Comment by sjackman** [comment]
Too bad the error message isn't more specific/helpful that it's due to the disk volume not being executable. Oh well.
