### ISSUE TITLE
Arch Linux Warning: python is symlinked to python3 This will confuse build scripts and in general lead to subtle breakage.

### ISSUE THREAD

**Issue by jamesscholeyweb** [Linuxbrew/linuxbrew#764]
Just moved to Arch Linux and installed linuxbrew. Brew doctor gives me this warning. Should I be worried about it? or does anyone know the correct solution.

Googling has proven inconclusive

Thanks in advance.

**Comment by sjackman** [comment]
I have no idea myself. Does Arch Linux provide a python2 package? If you wanted to be on the safe side, I'd install that python2 package and make sure that `python` points to Python 2 and `python3` points to Python 3. You can also `brew install python` and `brew install python3`.

**Comment by jamesscholeyweb** [comment]
Thanks for the speedy response Shaun. Just looking through the Arch Wiki now. I think the answer lies in here somewhere https://wiki.archlinux.org/index.php/python especially the Dealing with problems in build scripts. But I'm not sure how to implement this in a way specific to brew.

**Comment by jamesscholeyweb** [comment]
Just a thought Shaun, is a possible solution to install pyenv and set global to 3.5.1 and local on .linuxbrew to 2.7?

**Comment by sjackman** [comment]
I'm afraid that I'm beyond my Python systems knowledge here. I'm going to close this issue, but feel free to comment if you learn more or run into issues.

**Comment by jamesscholeyweb** [comment]
Thanks Shaun. Yeah it's above my knowledge aswell. My proposed idea
definitely makes things worse.

**Comment by Mikaela** [comment]
Which version of Python does Linuxbrew want? 

According to [PEP 0394](https://www.python.org/dev/peps/pep-0394/) (which was made because of Arch by the way) the application must use:

* `#!/usr/bin/env python` if it runs with Python **2 and 3**.
* `#!/usr/bin/env python2` if it runs with Python **2**.
* `#!/usr/bin/env python3` if it runs with Python **3**.

Some older Python 2.x versions might not have `python2` binary and if Linuxbrew doesn't support those versions, it should be updated to use `python2`.

**Comment by jamesscholeyweb** [comment]
Depends on the dependencies of installed packages I guess. I've actually
just gone back to using aur and pacman. Tweaking Python environments is not
outweighed by my aversion to typing sudo on this occasion.

**Comment by sjackman** [comment]
The Linuxbrew `python` package installs both `python2` and `python` symlinks. I don't know if there are any formula that expect `python` to be a `python2` interpreter. The doctor warning is only a warning. It may or may not be a problem.
