### ISSUE TITLE
Error: uninitialized constant Homebrew::Diagnostic::Checks::Tempfile

### ISSUE THREAD

**Issue by reo7sp** [Linuxbrew/linuxbrew#772]
After installing linuxbrew in xubuntu which is running under virtualbox I have error "uninitialized constant Homebrew::Diagnostic::Checks::Tempfile". The commit id of this linuxbrew version is b8d7f66c71b1d7f03050386cd0711fe84a776ca8.

Yesterday I installed linuxbrew on my laptop where xubuntu is installed too but without virtualbox. It works perfect. The commit id of linuxbrew on this laptop is 9c021439e4e13c657ffd5304d4391d8201012ce3.

I guess the bug is between these commits.

Gist with logs: https://gist.github.com/reo7sp/ba613d13f68f5ce76b70

**Comment by Danielflsr** [comment]
Me too, in Ubuntu 14.04.

**Comment by dubnde** [comment]
Observed in Ubuntu 14.04.

**Comment by sjackman** [comment]
Woops. My fault. Fixed thanks to @abelsiqueira
