### ISSUE TITLE
HOMEBREW_TEMP not executable wrong in Ubuntu

### ISSUE THREAD

**Issue by eugenesvk** [Linuxbrew/linuxbrew#775]
I've installed `Linuxbrew` in several virtual machines running Ubuntu (12 and 15 versions) and have the same issue: `brew doctor` misidentifies `$HOMEBREW_TEMP` as though it does `not permit executing programs. It is likely mounted "noexec". Please set HOMEBREW_TEMP in your ~/.bash_profile to a different directory`
The thing is I've already created a new temp folder, added `sticky` mode to it, so the permissions are `drwxrwxrwt`, but `brew doctor` still outputs this error.
Is the function that check folder permissions wrong or am I missing something?
Installation seems to run normally, but this still bugs me — maybe there is an error somewhere I need to fix.

**Comment by sjackman** [comment]
The code is at [`check_tmpdir_executable `](https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Homebrew/diagnostic.rb#L1126)

Can your report the output of
```sh
cd /tmp
echo "#!/bin/sh" >foo
chmod +x foo
./foo
echo $?
```

Does `brew install hello` succeed?

**Comment by eugenesvk** [comment]
Hey, @sjackman, thanks for an uber-prompt response.
`echo "#!/bin/sh" >foo` didn't work, I had to use single quotes instead of double quotes.
But otherwise the output of your chain of command is `0`, `foo` is created as an executable file with only one line of text.
Also, if I add some other command to `foo` (e.g. `echo "new"`), and then try to execute with `./foo` the commands output correctly.

The `brew install hello` package also install just fine and `hello -t` outputs "hello, world"

P.S.
I've found the code in the [check_tmpdir_executable](https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Homebrew/diagnostic.rb#L1126) earlier, but I just don't understand it.

**Comment by sjackman** [comment]
I'm not able to reproduce this issue myself, so it'll be difficult to troubleshoot. You can simply ignore the warning for the mean time. Sorry that I couldn't help you resolve it.

**Comment by sjackman** [comment]
I was able to reproduce this issue:
`Error: Text file busy - /var/tmp/sjackman/homebrew_check_tmpdir_executable20160201-13383-soy4dl`
Adding `f.close` fixed it.

**Comment by sjackman** [comment]
It's odd, but my best guess is that this issue only affects NFS file systems? Just a guess.

**Comment by sjackman** [comment]
Fixed. Thanks for the bug report, Evgeny.

**Comment by eugenesvk** [comment]
Nice! You fixed it faster than I was able to click on the 'Comment' button to submit my comment!
I've checked on my VM and it works!
Now my `system is ready to brew.` (not that the lack of readiness stopped me before :)

**Comment by sjackman** [comment]
Great. Glad to hear it.
