### ISSUE TITLE
sdl2 fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#778]
Various patches fail to apply:

> ==> Applying SDL2-2.0.3_OSX_104.patch
patching file include/SDL_config.h
Hunk #1 succeeded at 1 with fuzz 1.
patching file include/SDL_platform.h
patching file include/SDL_syswm.h
Hunk #1 FAILED at 83.
1 out of 1 hunk FAILED -- saving rejects to file include/SDL_syswm.h.rej
patching file src/audio/coreaudio/SDL_coreaudio.h
patching file src/file/cocoa/SDL_rwopsbundlesupport.m
patching file src/filesystem/cocoa/SDL_sysfilesystem.m
patching file src/joystick/darwin/SDL_sysjoystick.c
Hunk #1 FAILED at 384.
Hunk #2 succeeded at 394 with fuzz 2 (offset 1 line).
1 out of 2 hunks FAILED -- saving rejects to file src/joystick/darwin/SDL_sysjoystick.c.rej
patching file src/power/macosx/SDL_syspower.c
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED -- saving rejects to file src/power/macosx/SDL_syspower.c.rej
patching file src/video/cocoa/SDL_cocoaclipboard.m
Hunk #1 FAILED at 30.
1 out of 1 hunk FAILED -- saving rejects to file src/video/cocoa/SDL_cocoaclipboard.m.rej
patching file src/video/cocoa/SDL_cocoakeyboard.m
Hunk #1 succeeded at 419 with fuzz 2 (offset -7 lines).
Hunk #2 succeeded at 482 (offset -2 lines).
patching file src/video/cocoa/SDL_cocoamodes.m
Hunk #1 FAILED at 127.
Hunk #2 succeeded at 154 with fuzz 1 (offset 8 lines).
Hunk #3 FAILED at 185.
Hunk #4 FAILED at 258.
Hunk #5 FAILED at 320.
Hunk #6 FAILED at 338.
Hunk #7 FAILED at 352.
6 out of 7 hunks FAILED -- saving rejects to file src/video/cocoa/SDL_cocoamodes.m.rej
patching file src/video/cocoa/SDL_cocoamouse.h
patching file src/video/cocoa/SDL_cocoaopengl.m
Hunk #1 succeeded at 327 (offset -20 lines).
patching file src/video/cocoa/SDL_cocoavideo.h
Hunk #1 succeeded at 25 with fuzz 2.
Hunk #2 succeeded at 46 (offset 1 line).
patching file src/video/cocoa/SDL_cocoawindow.h
Hunk #2 succeeded at 79 with fuzz 2 (offset 2 lines).
patching file src/video/cocoa/SDL_cocoawindow.m
Hunk #2 succeeded at 188 (offset 86 lines).
Hunk #3 FAILED at 199.
Hunk #4 succeeded at 311 (offset 90 lines).
Hunk #5 succeeded at 385 (offset 92 lines).
Hunk #6 FAILED at 332.
Hunk #7 FAILED at 359.
Hunk #8 succeeded at 746 (offset 136 lines).
Hunk #9 succeeded at 771 (offset 136 lines).
Hunk #10 succeeded at 780 (offset 136 lines).
Hunk #11 FAILED at 839.
Hunk #12 succeeded at 1079 with fuzz 1 (offset 187 lines).
Hunk #13 FAILED at 1058.
Hunk #14 succeeded at 1268 (offset 203 lines).
Hunk #15 succeeded at 1704 (offset 195 lines).
5 out of 15 hunks FAILED -- saving rejects to file src/video/cocoa/SDL_cocoawindow.m.rej
Error: Failure while executing: patch -g 0 -f -p1 -i /home/bob/tmp/sdl2--patch20160202-12074-164v94g/SDL2-2.0.3_OSX_104.patch

I'll probably have time to look at this myself in the next few days, so no rush to fix it.

**Comment by sjackman** [comment]
Thanks, Bob.

**Comment by rwhogg** [comment]
Closing this now that #786 is merged.
