### ISSUE TITLE
Install postgres and start service automatically

### ISSUE THREAD

**Issue by ginolon** [Linuxbrew/linuxbrew#787]
I install Postgresql on my Ubuntu with:

`brew install postgres`

now I have:

    psql --version
    psql (PostgreSQL) 9.5.0

How can I start the service automatically?

On my Mac with homebrew I can do it with:

    ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist

but how on Ubuntu with Linuxbrew?

**Comment by sjackman** [comment]
Linuxbrew does not currently configure which daemons start at boot. [This post](http://askubuntu.com/a/715275/166699) says to run
```sh
sudo update-rc.d postgresql enable
```
You will first need to link the `rc.d` scripts from your Linuxbrew prefix into `/etc`.

**Comment by ginolon** [comment]
Can you explain it better, please?

**Comment by sjackman** [comment]
Read this page [17.3. Starting the Database Server](http://www.postgresql.org/docs/9.3/static/server-start.html)
> On Linux systems either add
```sh
/usr/local/pgsql/bin/pg_ctl start -l logfile -D /usr/local/pgsql/data
```
to `/etc/rc.d/rc.local` or `/etc/rc.local` or look at the file `contrib/start-scripts/linux` in the PostgreSQL source distribution.

**Comment by ginolon** [comment]
And what

`sudo update-rc.d postgresql enable` do?

**Comment by sjackman** [comment]
Ignore that suggestion. It won't help unless there's an appropriate file installed somewhere in `/etc/init.d/postgresql`.
