### ISSUE TITLE
openssl: install fails on Fedora. Error while executing patch

### ISSUE THREAD

**Issue by KomodoTech** [Linuxbrew/linuxbrew#804]
I cannot seem to install openssl with linuxbrew. I am running Fedora 23 and the error that I am getting is:

```
Error: Failure while executing: patch -g 0 -f -p1 -i /tmp/openssl--patch20160221-25615-m3fhf3/da7947e8c6915d86616425ecbc4906f079ef122f.diff
```

Unfortunately, I am pretty new to this and I cannot seem to get any more information regarding the error. Is there any way someone can help?

Thank you!

**Comment by sjackman** [comment]
A workaround is `brew install homebrew/dupes/gpatch` or alternatively `sudo yum install patch`.
Pull request #605 addressed this issue. I may revisit it.

**Comment by KomodoTech** [comment]
Worked like a charm! 
Thank you so much for the suggestion and in general for the awesome support that you are providing.
Like in pull request #605 , I am working on an "almost bare" system. It's probably quite obvious to experienced linux brew users that patch/gpatch is a dependency, but since I never had that issue on OS X, I was not aware.

In any case,
Thanks again!

**Comment by sjackman** [comment]
Thanks for the kind feedback.

**Comment by sjackman** [comment]
I've merged Piotr's patch. This issue should be resolved now. Thanks for the patch, Piotr, and for the bug report, @KomodoTech.
