### ISSUE TITLE
Installation error: cannot read /proc/cpuinfo

### ISSUE THREAD

**Issue by al-the-x** [Linuxbrew/linuxbrew#805]
Very excited to get linuxbrew to work on my Debian-based shared host. As I lack root access on this box, I'm trying to install updated versions of key packages like `git` and `tmux` into my home directory for my own personal sanity. Although `brew doctor` reports no problem, I'm running into trouble while attempting to install anything:

    $> brew install git
    Error: permission denied: /proc/cpuinfo

On my host, `/proc/cpuinfo` is owned by `root:root` with permissions 440. I understand the need for checking the architecture, and I can get this information via `uname -m` no problem -- `x86_64` -- along with the Debian distro name, etc. Is there a way to have `brew` skip this check or indicate the value manually?

**Comment by al-the-x** [comment]
While I'm not proud of the solution, I was able to fake `brew` into working by editing [`Library/Homebrew/os/linux/hardware.rb`](../blob/master/Library/Homebrew/os/linux/hardware.rb#26) to return a ficticious value for `cpuinfo` -- `"Intel x86_64\nflags foo"` -- to fool `brew`. It's a hack.

**Comment by sjackman** [comment]
Yours is the first system I've seen where users don't have access to `/proc/cpuinfo`. That's unusual, so I'm afraid that it's not a priority for me to fix this issue, although I realize that it must be a bit frustrating for you. I would ask your system admin if they can relax these permissions. There's no reason for this file to be private.

**Comment by al-the-x** [comment]
It may be related to the virtualization container they're running, but that's just a guess. I'll put in a request to support but typically the only answers that come back are links to (unhelpful) docs pages.
