### ISSUE TITLE
glibc: LD_LIBRARY_PATH shouldn't contain the current directory

### ISSUE THREAD

**Issue by albertz** [Linuxbrew/linuxbrew#807]
Glibc is a dependency of Git which I try to install.
Glibc fails to install:

```
...
==> Installing git dependency: glibc
==> Downloading http://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
==> Downloading from http://www.gutscheinrausch.de/mirror/gnu/glibc/glibc-2.19.tar.bz2
######################################################################## 100.0%
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/work/asr2/zeyer/linuxbrew/Ce
Last 15 lines from /u/zeyer/.cache/Homebrew/Logs/glibc/01.configure:
checking for gmsgfmt... no
checking for msgfmt... msgfmt
checking version of msgfmt... 0.18.1, ok
checking for makeinfo... makeinfo
checking version of makeinfo... 4.13, ok
checking for sed... sed
checking version of sed... 4.2.1, ok
checking for gawk... gawk
checking version of gawk... 4.0.1, ok
checking for nm... nm
checking LD_LIBRARY_PATH variable... contains current directory
configure: error: 
*** LD_LIBRARY_PATH shouldn't contain the current directory when
*** building glibc. Please change the environment variable
*** and run configure again.
```

The error is not because of my env:

```
$ echo $LD_LIBRARY_PATH
/usr/lib32  /usr/local/lib  /usr/local/cuda-6.5/lib64
```

**Comment by sjackman** [comment]
That's curious. I haven't seen that error myself. I see instead `checking LD_LIBRARY_PATH variable... ok`
Can you please report
```sh
unset LD_LIBRARY_PATH
brew install glibc || brew gist-logs glibc
```

**Comment by philippbayer** [comment]
I had the same error with a malformed LD_LIBRARY_PATH:

   >echo $LD_LIBRARY_PATH
   :/var/spool/torque/lib

In my case, simply removing that ":" fixed it (or `unset LD_LIBRARY_PATH`). In @albertz' case I assume these spaces shouldn't be there, these should be colons (or again, just `unset`)

**Comment by albertz** [comment]
@philippbayer My output looks like this because I use Fish. Fish interprets it as an array (separating by ":") and then prints every item of the array just separated by spaces.

**Comment by albertz** [comment]
Yes, fixing LD_LIBRARY_PATH fixes this error. I guess we can close this? Or is this a bug in Linuxbrew and it should unset itself such stuff?

**Comment by sjackman** [comment]
> Btw., I think Homebrew on MacOSX always unsets LD_LIBRARY_PATH (or even the whole env) before it runs any setup, or does it not? And earlier, I think it did at least do some cleanup/fixing of the env, like in this case, removing empty entries from LD_LIBRARY_PATH. Maybe on Linux we should do the same? Or would that break too much things?

I've added a `brew doctor` check for `LD_LIBRARY_PATH`. In the future Linuxbrew will remove `LD_LIBRARY_PATH`, but for now it's needed as a workaround when upgrading core libraries that are needed by the compiler toolchain, like for example `zlib`.

**Comment by philippbayer** [comment]
A year later and a blog post reminded me of this issue - https://joshumax.github.io/general/2017/06/08/how-torch-broke-ls.html

It turns out that an empty entry in LD_LIBRARY_PATH is converted into the current directory. Good to know!

**Comment by sjackman** [comment]
Pretty ugly behaviour. Linuxbrew now resets `LD_LIBRARY_PATH` when installing software.
https://github.com/Linuxbrew/brew/blob/master/Library/Homebrew/extend/ENV/shared.rb#L27
