### ISSUE TITLE
gcc: Error: stack level too deep

### ISSUE THREAD

**Issue by maxim-belkin** [Linuxbrew/linuxbrew#809]
Steps to reproduce:
1. Get a brand new copy of Linuxbrew (`brew doctor` reports that everything is normal but actually there are 3 bad symlinks: 2 here: `[path-to-linuxbrew]/Library/ENV/pkgconfig/fuse/{osx,}fuse.pc` and 1 here: `[path-to-linuxbrew]/lib64` that points to not-yet-existing `lib` folder.
2. Run `brew install glibc --with-current-kernel`
What linuxbrew does:
1. Pours `zlib`
2. Tries to install `binutils` but fails with the following message (I'm typing manually here, so I will omit some lines):
 ```
Error: stack level too deep
/usr/lib/ruby/1.8/pathname.rb:218:in `initialize'
/usr/lib/ruby/1.8/pathname.rb:604:in `new'
/usr/lib/ruby/1.8/pathname.rb:604:in `+'
... <tons of lines> ...
[path-to-linuxbrew]/Library/brew.rb:85 in `send'
[path-to-linuxbrew]/Library/brew.rb:85
```
After that, quite a few brew commands fail.
`brew list` reports that `zlib` is installed.
`brew prune` does not help.
What helps: `brew remove zlib` && `rmdir $(brew --prefix)/Cellar`

Tried building `zlib` from source but failed again with tons of error messages but I think those are irrelevant as they simply indicate that there is some problem in the recent changes because just a week or so ago I was able to build `zlib` and `glibc` without problems.

**Comment by sjackman** [comment]
I don't see this error myself. It's going to be tricky for me to troubleshoot. I wonder whether it's somehow dependent on the version of Ruby. Can you please report `ruby --version`? If possible, could you try using a newer version of Ruby? If you think the issue is related to bottles, and would like to try it without bottles, use `brew install glibc -s` or `export HOMEBREW_BUILD_FROM_SOURCE=1; brew install glibc`.

**Comment by sjackman** [comment]
Could you please gist and post the entire output (the `... <tons of lines> ...`)?

**Comment by sjackman** [comment]
> Tried building zlib from source but failed again with tons of error messages but I think those are irrelevant as they simply indicate that there is some problem in the recent changes because just a week or so ago I was able to build zlib and glibc without problems.

The error messages would help me troubleshoot.

**Comment by sjackman** [comment]
Setting `export HOMEBREW_BUILD_FROM_SOURCE=1` should return you to the previous behaviour, that doesn't use bottles.

**Comment by maxim-belkin** [comment]
Ruby version and `... <tons of lines>...` are in the 
[failure.txt](https://github.com/Linuxbrew/linuxbrew/files/130309/failure.txt)

**Comment by maxim-belkin** [comment]
And here is an attempt to build everything from source: [failure_build_from_source.txt](https://github.com/Linuxbrew/linuxbrew/files/130320/failure_build_from_source.txt)

**Comment by maxim-belkin** [comment]
I can build from source `Ruby 1.9` and report if the error message persists.

**Comment by maxim-belkin** [comment]
While I was having fun trying to install Ruby 1.9, I've found the following [thread](https://github.com/Homebrew/homebrew/issues/44837) and did a `brew readall` which returned a `Stack level too deep` error for the `gcc` formula. After checking out a previous version of `gcc.rb`, I was able to proceed with the "usual" standalone linuxbrew installation... So, it is `gcc` formula that is broken, not `zlib`. So, I changed the title of the issue.

**Comment by sjackman** [comment]
Thanks. That issue does not happen on my system. `brew readall` exits successfully. I have an idea though. Please follow these instructions and see if it helps:
https://github.com/Linuxbrew/linuxbrew/wiki/Standalone-Installation#create-symlinks-for-gcc

**Comment by maxim-belkin** [comment]
Presence of symlinks does not help.
```
[In the Linuxbrew folder]

$ git status
# On branch master
nothing to commit, working directory clean

$ ls bin/
brew  g++-4.4@  gcc-4.4@  gfortran-4.4@

$ brew readall
Error: problem in [Linuxbrew folder]/Library/Formula/gcc.rb
stack level too deep

$ git checkout d1d40b2 -- ./Library/Formula/gcc.rb
$ brew readall
[No output, so gcc.rb passes "the test"]
```

**Comment by sjackman** [comment]
Does `brew install hello` work?

**Comment by maxim-belkin** [comment]
Nope: `Error: stack level too deep` appears. If I checkout the previous version of gcc (`git checkout d1d40b2 ./Library/Formula/gcc.rb`), then it works.
So, the diff that spoils everything for me is:
```
git diff d1d40b2 cd40a55 ./Library/Formula/gcc.rb
diff --git a/Library/Formula/gcc.rb b/Library/Formula/gcc.rb
index 8dc8676..17dd83d 100644
--- a/Library/Formula/gcc.rb
+++ b/Library/Formula/gcc.rb
@@ -47,7 +47,8 @@ class Gcc < Formula

   depends_on "zlib" unless OS.mac?
   depends_on "binutils" if build.with? "glibc"
-  depends_on "glibc" => :optional
+  depends_on "glibc" => Formula["glibc"].installed? || !GlibcRequirement.new.satisfied? ?
+    :recommended : :optional
   depends_on "gmp"
   depends_on "libmpc"
   depends_on "mpfr"
```

**Comment by sjackman** [comment]
That's very helpful. Thanks, Maxim.

**Comment by sjackman** [comment]
I still haven't reproduced this issue. The following patch may help though. Can you test it for me?
```diff
diff --git a/Library/Homebrew/requirements/glibc_requirement.rb b/Library/Homebrew/requirements/glibc_requirement.rb
index 6439236..58470ac 100644
--- a/Library/Homebrew/requirements/glibc_requirement.rb
+++ b/Library/Homebrew/requirements/glibc_requirement.rb
@@ -10,7 +10,7 @@ class GlibcRequirement < Requirement
     super
   end
 
-  satisfy {
+  satisfy(:build_env => false) {
     next true unless OS.linux?
     begin
       next true if to_dependency.installed?
```

**Comment by maxim-belkin** [comment]
I think this patch fixes the problem! Great! But something strange happens when I run `brew test hello` (see below) -- no output... At the same time, if I manually run `[Linuxbrew-folder]/Cellar/hello/2.10/bin/hello --greeting=brew` -- it prints `brew` just fine.
```
$ git diff
diff --git a/Library/Homebrew/requirements/glibc_requirement.rb b/Library/Homebrew/requirements/glibc_requirement.rb
index 6439236..58470ac 100644
--- a/Library/Homebrew/requirements/glibc_requirement.rb
+++ b/Library/Homebrew/requirements/glibc_requirement.rb
@@ -10,7 +10,7 @@ class GlibcRequirement < Requirement
     super
   end

-  satisfy {
+  satisfy(:build_env => false) {
     next true unless OS.linux?
     begin
       next true if to_dependency.installed?

$ brew list

$ brew install hello
==> Downloading http://ftpmirror.gnu.org/hello/hello-2.10.tar.gz
Already downloaded: [cache-folder]/Homebrew/hello-2.10.tar.gz
==> ./configure --disable-silent-rules --prefix=[Linuxbrew]/Cellar/hello/2.10
==> make install
[Linuxbrew]/Cellar/hello/2.10: 52 files, 228.6K, built in 42 seconds

$ brew test hello
Testing hello
==> [Linuxbrew]/Cellar/hello/2.10/bin/hello --greeting=brew

$ brew readall
[no output here, which is great]
```

**Comment by sjackman** [comment]
Great! The output of `brew test hello` is elided by default. Use `brew test -v hello`.

**Comment by sjackman** [comment]
Fixed. Thanks for the bug report and help troubleshooting, Maxim.

**Comment by maxim-belkin** [comment]
No problem!
