### ISSUE TITLE
Changes to build terraform and packer on linux labeled "linux-specific" by Homebrew.

### ISSUE THREAD

**Issue by hartzell** [Linuxbrew/linuxbrew#812]
I submitted a couple of patches so that terraform and packer built right in both Homebrew and Linuxbrew and submitted them to Homebrew, https://github.com/Homebrew/homebrew/pull/49172 so that they would flow downstream.

Should I have just fixed them in the linuxbrew tree?

**Comment by sjackman** [comment]
Hi, George. I'll reword the CONTRIBUTING document. Patches to fix build issues that only affect Linux should be sent to Linuxbrew. Patches to fix build issues that affect both Mac and Linux should be sent to Homebrew.
