### ISSUE TITLE
Brew installed glibc as requirement but completed broken linuxbrew

### ISSUE THREAD

**Issue by njia** [Linuxbrew/linuxbrew#813]
```
‹njia@7ms-prod-ny4-kvmjump002:~› brew upgrade git
==> Upgrading 1 outdated package, with result:
git 2.7.1
==> Upgrading git
==> Installing dependencies for git: binutils, linux-headers, glibc, patchelf, gpatch
==> Installing git dependency: binutils
==> Downloading http://ftpmirror.gnu.org/binutils/binutils-2.25.1.tar.gz
==> Downloading from http://mirror.keystealth.org/gnu/binutils/binutils-2.25.1.tar.gz
######################################################################## 100.0%
==> ./configure  --with-sysroot=/ --prefix=/home/njia/.linuxbrew/Cellar/binutils/2.25.1 --infodir=/home/njia/.linuxbrew/Cellar/binutils/2.25.1/share/i
==> make
==> make install
/home/njia/.linuxbrew/Cellar/binutils/2.25.1: 3,031 files, 272.3M, built in 2 minutes 10 seconds
==> Installing git dependency: linux-headers
==> Downloading https://linuxbrew.bintray.com/bottles/linux-headers-3.15.9.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring linux-headers-3.15.9.x86_64_linux.bottle.tar.gz
/home/njia/.linuxbrew/Cellar/linux-headers/3.15.9: 731 files, 3.3M
==> Installing git dependency: glibc
==> Downloading http://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
==> Downloading from http://open-source-box.org/glibc/glibc-2.19.tar.bz2
######################################################################## 100.0%
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/home/njia/.linuxbrew/Cellar/glibc/2.19 --enable-obsole
==> make
==> make install
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall glibc`
==> Summary
/home/njia/.linuxbrew/Cellar/glibc/2.19: 1,364 files, 40.1M, built in 3 minutes 13 seconds
==> Installing git dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.8.x86_64_linux.bottle.tar.gz
Error: Failed to download resource "patchelf"
Download failed: https://linuxbrew.bintray.com/bottles/patchelf-0.8.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
Error: Suspicious failure
‹njia@7ms-prod-ny4-kvmjump002:~› brew postinstall glibc
Segmentation fault
‹njia@7ms-prod-ny4-kvmjump002:~› git --version
Segmentation fault
‹njia@7ms-prod-ny4-kvmjump002:~› brew remove glibc
Segmentation fault
‹njia@7ms-prod-ny4-kvmjump002:~› ansible
Segmentation fault
‹njia@7ms-prod-ny4-kvmjump002:~› brew
Segmentation fault
‹njia@7ms-prod-ny4-kvmjump002:~› ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
Segmentation fault
‹njia@7ms-prod-ny4-kvmjump002:~› exit
```

Then I manually removed `.linuxbrew` directory but had so many different problems trying to get linuxbrew/Ansible to work.

Now I am up to the point have to unlink `glibc` to install Ansible but `ansible-vault` is not working after installation another use on the same server does not have any problems.

```
‹njia@7ms-prod-ny4-kvmjump002:~› ansible-vault create a.yml
New Vault password:
Confirm New Vault password:
ERROR! ansible-vault requires a newer version of pycrypto than the one installed on your platform. You may fix this with OS-specific commands such as: yum install python-devel; rpm -e --nodeps python-crypto; pip install pycrypto
```

```
‹njia@7ms-prod-ny4-kvmjump002:~› brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Linuxbrew/linuxbrew.git
HEAD: 46013be9b4019b3186ceacf39e0acb636382a269
Last commit: 25 minutes ago
HOMEBREW_PREFIX: /home/njia/.linuxbrew
HOMEBREW_REPOSITORY: /home/njia/.linuxbrew
HOMEBREW_CELLAR: /home/njia/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: quad-core 64-bit sandybridge
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: 2.7.8 => /usr
System Ruby: 1.8.7-p374 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /home/njia/.linuxbrew/bin/python => /home/njia/.linuxbrew/Cellar/python/2.7.11/bin/python2.7
Ruby: /usr/bin/ruby
Java: N/A
```

**Comment by sjackman** [comment]
Which distribution of Linux are you using?

> Then I manually removed .linuxbrew directory but had so many different problems trying to get linuxbrew/Ansible to work.

Do you mean that you reinstalled Linuxbrew from scratch? Did that work?

Linuxbrew now uses bottles (pre compiled packages) by default. On systems with an old `glibc` < 2.19 it installs its own copy of `glibc`. If this process is not working for you, you can disable the use of bottles by setting the environment variable:
```
export HOMEBREW_BUILD_FROM_SOURCE=1
```

**Comment by njia** [comment]
Hi Sjackman

Our system is CentOS 6.4 and it is a jumpbox so I can't upgraded glibc. 

Yes I reinstalled linubrew, ansible-vault not working kept giving me the above error message.

Is there a way I can checkout a old version of linuxbrew that does not required glibc? Like it was all working fine with git 2.7, ansible 2.0. Now I can't even install vim via linuxbrew.

Thanks
Nan

**Comment by sjackman** [comment]
Glad to hear that you got it working.

Note that you can use triple backticks to escape blocks of text in Markdown. See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Installing `glibc` and `gcc` should work better now. You may need to start with a fresh installation of Linuxbrew, if yours is older than the last few months.

**Comment by rchikhi** [comment]
also encountered this issue today (latest linuxbrew) with linuxbrew installing glibc 2.19, and `export HOMEBREW_BUILD_FROM_SOURCE=1` solved it

**Comment by sjackman** [comment]
Sorry to hear that Rayan. What error message are you seeing? Please report the output of:
```sh
brew config
brew doctor
```
Please start with a fresh installation of Linuxbrew if possible and after the above two commands run `brew install gcc`. Everything should work smoothly after that.

**Comment by rchikhi** [comment]
Yep, did a clean install and the problem remained. Clearing `LD_LIBRARY_PATH` solved it.

I didn't investigate further.. but for reference, brew config/doctor on the node where everything segfaulted after glibc 2.19 install:
http://pastebin.com/iupX1ek4
and brew config/doctor on the front node, where it doesn't (they share the same homedir, but different `LD_LIBRARY_PATH`'s, etc):
http://pastebin.com/gvD2MqWA

Thanks for the help!

**Comment by sjackman** [comment]
Note the following warning from `brew doctor`:
```
Warning: Setting LD_* vars can break dynamic linking.
Set variables:
    LD_LIBRARY_PATH: /storage/home/rxc48/.linuxbrew/lib:/storage/home/rxc48/lib:/storage/home/rxc48/lib64:/usr/global/intel-
```

**Comment by rchikhi** [comment]
well-noted now, kind of would have ignored it unless it  said "can break your WHOLE SYSTEM" :)

**Comment by sjackman** [comment]
Good point. The message comes from Homebrew, and the situation is rather more dire on Linuxbrew that it is on Homebrew.
@rwhogg Rayan suggests we change `Warning: Setting LD_* vars can break dynamic linking.` to `Warning: Setting LD_* vars can break your WHOLE SYSTEM.` That might better get the point across. =)

**Comment by rwhogg** [comment]
Yeah, LD_LIBRARY_PATH can be pretty dangerous. Let's not encourage people to take it lightly.

**Comment by rchikhi** [comment]
upon further inspection, my whole system was broken after glibc installed even when LD_LIBRARY_PATH was set to just "$HOME/.linuxbrew/lib"

**Comment by sjackman** [comment]
Yep. Don't set `LD_LIBRARY_PATH`. It'll break everything.
