### ISSUE TITLE
glibc: Requires gcc ≥ 4.4. These critical programs are missing or too old: gcc

### ISSUE THREAD

**Issue by sni** [Linuxbrew/linuxbrew#816]
I am unable to install gcc. Installing gcc pulls in glibc as dependency which then fails with too old gcc.

```
~$ brew install gcc
==> Installing dependencies for gcc: binutils, linux-headers, glibc, gmp, mpfr, libmpc, isl
==> Installing gcc dependency: binutils
worked
==> Installing gcc dependency: linux-headers
worked
==> Installing gcc dependency: glibc
==> Downloading http://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
Already downloaded: /omd/sites/test/.cache/Homebrew/glibc-2.19.tar.bz2
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/opt/omd/sites/test/.linuxbrew/Cellar/glibc/2.19 --enable-obsolet
Last 15 lines from /omd/sites/test/.cache/Homebrew/Logs/glibc/01.configure:
checking version of gmake... 3.81, ok
checking for gnumsgfmt... no
checking for gmsgfmt... no
checking for msgfmt... msgfmt
checking version of msgfmt... 0.17, ok
checking for makeinfo... makeinfo
checking version of makeinfo... 4.12, ok
checking for sed... sed
checking version of sed... 4.1.5, ok
checking for gawk... gawk
checking version of gawk... 3.1.6, ok
checking for nm... nm
configure: error: 
*** These critical programs are missing or too old: gcc
*** Check the INSTALL file for required versions.
```

```
checking for gcc... /usr/bin/gcc-4.3 -B/home/test/.linuxbrew/Cellar/binutils/2.25.1/bin/
checking version of /usr/bin/gcc-4.3 -B/home/test/.linuxbrew/Cellar/binutils/2.25.1/bin/... 4.3.4, bad
```

The homepage says minimum gcc is 4.2. Is this still true?

```
~$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: git://github.com/Homebrew/linuxbrew.git
HEAD: 46013be9b4019b3186ceacf39e0acb636382a269
Last commit: 9 hours ago
HOMEBREW_PREFIX: /home/test/.linuxbrew
HOMEBREW_REPOSITORY: /home/test/.linuxbrew
HOMEBREW_CELLAR: /home/test/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 8-core 64-bit ivybridge
OS X: 0-x86_64
Xcode: N/A
CLT: N/A
Clang: N/A
X11: 2.7.8 => /usr
System Ruby: 1.8.7-p72 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.6
Ruby: /usr/bin/ruby
Java: N/A
```

**Comment by sjackman** [comment]
Interesting. I didn't know that GCC 4.3 is not able to build `glibc`. GCC 4.4 definitely works. I have tested that. Which distribution of Linux are you using?

A workaround is to set
```sh
export HOMEBREW_BUILD_FROM_SOURCE=1
```

**Comment by sni** [comment]
That did not change anything. The error is the same with HOMEBREW_BUILD_FROM_SOURCE set.
This is a sles 11 sp1 (64bit)

**Comment by sjackman** [comment]
Try `brew install gcc --without-glibc`.

**Comment by zbeekman** [comment]
I too have this issue on a RHEL 5 system.  I actually have access to gcc 4.8.3 (through GNU modules) but can't figure out how to get Linuxbrew to use it... maybe reinstall Linux brew setting CC and CXX to point to 4.8.3?

**Comment by sjackman** [comment]
@zbeekman Create symlinks for gcc like so: https://github.com/Linuxbrew/linuxbrew/wiki/Standalone-Installation#create-symlinks-for-gcc
Linuxbrew ignores `CC` and `CXX`.

**Comment by sjackman** [comment]
@sni Did the above workaround work for you?

**Comment by sni** [comment]
Unfortunatly this doesn't work either:

```
~$ brew install gcc --without-glibc
...
==> Installing gcc
==> Downloading http://ftpmirror.gnu.org/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
Already downloaded: /home/test/.cache/Homebrew/gcc-5.3.0.tar.bz2
==> ../configure --prefix=/home/test/.linuxbrew/Cellar/gcc/5.3.0  --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-5 --with-gmp=/opt/omd
==> make bootstrap
Last 15 lines from /home/test/.cache/Homebrew/Logs/gcc/02.make:
make[3]: *** [graphite-blocking.o] Error 1
make[3]: *** [graphite-isl-ast-to-gimple.o] Error 1
make[3]: *** [graphite-dependences.o] Error 1
make[3]: *** [graphite-interchange.o] Error 1
/bin/sh ../../gcc/../move-if-change tmp-attrtab.c    insn-attrtab.c
/bin/sh ../../gcc/../move-if-change tmp-dfatab.c     insn-dfatab.c
/bin/sh ../../gcc/../move-if-change tmp-latencytab.c insn-latencytab.c
echo timestamp > s-attrtab
rm gcc.pod
make[3]: Leaving directory `/tmp/gcc20160217-30409-1yd8s87/gcc-5.3.0/build/gcc'
make[2]: *** [all-stage1-gcc] Error 2
make[2]: Leaving directory `/tmp/gcc20160217-30409-1yd8s87/gcc-5.3.0/build'
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory `/tmp/gcc20160217-30409-1yd8s87/gcc-5.3.0/build'
make: *** [bootstrap] Error 2
```

**Comment by sni** [comment]
Updating gcc from the sles package repository is not an option. Isn't this the hole purpose of linuxbrew? :-)

**Comment by sjackman** [comment]
Yes, yes it is. Bootstrapping from >10 year-old systems is tricky though. It doesn't always work smoothly, but I'm working on it. CentOS 5 has GCC 4.1 by default, but can also optionally install GCC 4.4 `sudo yum install gcc44 gcc44-c++`. I was hoping that SLES 11 had something similar.

There's not enough info in the above log. Please report `brew gist-logs gcc`

**Comment by sni** [comment]
Here it is: https://gist.github.com/anonymous/3fac881b110ce98c8b97
I fixed that one by removing the trailing comma in .linuxbrew/opt/isl/include/isl/ctx.h line 83
Then it fails with "cannot find -lz" when trying to link. I will continue tomorrow...

Btw, is there a list of install options like --without-glibc, i was unable to find them in the manpage.

**Comment by sjackman** [comment]
> Btw, is there a list of install options like --without-glibc, i was unable to find them in the manpage.

See `brew options gcc`

> Then it fails with "cannot find -lz" when trying to link. I will continue tomorrow...

Please report `ls /lib64/libz*`

Try applying this patch:
```diff
diff --git a/Library/Formula/gcc.rb b/Library/Formula/gcc.rb
index 17dd83d..a7b17db 100644
--- a/Library/Formula/gcc.rb
+++ b/Library/Formula/gcc.rb
@@ -131,7 +131,7 @@ class Gcc < Formula
       "--with-isl=#{Formula["isl"].opt_prefix}",
     ]
     args += [
-      "--with-system-zlib",
+      ("--with-system-zlib" if OS.mac?),
       "--enable-libstdcxx-time=yes",
       "--enable-stage1-checking",
       "--enable-checking=release",
```

**Comment by sjackman** [comment]
> I fixed that one by removing the trailing comma in `.linuxbrew/opt/isl/include/isl/ctx.h` line 83

Please report this issue upstream to the authors of `isl` if you can.
