### ISSUE TITLE
Patch cannot find libattr

### ISSUE THREAD

**Issue by Neraste** [Linuxbrew/linuxbrew#822]
Hello everyone

First, I am not sure if this issue belongs to Linuxbrew, Homebrew or rather patch itself... (or if it is due to my system, maybe)

If I install gpatch in the usual way with `brew install gpatch`, it installs patch 2.7.5, and the patch command is unusable:

```
patch: error while loading shared libraries: libattr.so.1: cannot open shared object file: No such file or directory
```

Since patch is heavily used in many formulae, it virtually blocks any installation, with this error. Also, it occurs if I call patch without argument.

There is no attr formula. But I have tried to compile it manually from Savannah, and it does not build a libattr file. So I do not understand why patch even needs it.

A workaround for this is to disable `$HOME/bin/patch` and link it to you system `/usr/bin/patch`.

**Comment by sjackman** [comment]
I haven't run into this issue myself. Which distribution of Linux are you using?
I've just created a binary bottle of `gpatch`. `brew reinstall gpatch` should fix your issue.
I've also created a formula for `attr`. `brew install attr` should also work.
`attr` needed `make install install-lib` to install libraries. See http://www.linuxfromscratch.org/blfs/view/7.5/postlfs/attr.html

**Comment by Neraste** [comment]
Sorry for late reply

Thank you, this did the trick

**Comment by sjackman** [comment]
Which solution did you use, the bottled `gpatch` or the `attr` formula?

**Comment by Neraste** [comment]
I just installed `attr` and then `gpatch`.
