### ISSUE TITLE
Error: uninitialized constant Homebrew::Diagnostic::Checks::MacOS

### ISSUE THREAD

**Issue by muhasturk** [Linuxbrew/linuxbrew#823]
```
/home/mh/.linuxbrew/Library/Homebrew/diagnostic.rb:324:in `<class:Checks>'
/home/mh/.linuxbrew/Library/Homebrew/diagnostic.rb:72:in `<module:Diagnostic>'
/home/mh/.linuxbrew/Library/Homebrew/diagnostic.rb:7:in `<module:Homebrew>'
/home/mh/.linuxbrew/Library/Homebrew/diagnostic.rb:6:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/mh/.linuxbrew/Library/Homebrew/cmd/install.rb:2:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/mh/.linuxbrew/Library/Homebrew/cmd/upgrade.rb:1:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/mh/.linuxbrew/Library/brew.rb:21:in `require?'
/home/mh/.linuxbrew/Library/brew.rb:56:in `<main>'
```

### Version
`Homebrew 0.9.5 (git revision e4417; last commit 2016-02-17)`

**Comment by sjackman** [comment]
Please report
```sh
brew config
cd /home/mh/.linuxbrew
git remote -v
```
I think you may have the wrong `git` repository, pulling from `Homebrew/homebrew` instead of `Linuxbrew/linuxbrew`.

**Comment by Neraste** [comment]
I have this problem after first updating my Linuxbrew installation. The remote is set to Homebrew repo. If I change it in `$HOME/.linuxbrew/.git/config`, I get errors:

```
Error: Fetching /home/user/.linuxbrew failed!
Already up-to-date.
```

What to do?

**Comment by destroyerofbuilds** [comment]
I can confirm that cloning the Linuxbrew repo yesterday, followed by `brew update && brew upgrade --all` installed all my packages correctly, but my local copy of Linuxbrew was actually pulling from homebrew (the remote was set to homebrew, and the source code locally was homebrew.).

@Neraste to fix the issue you are encountering I did the following:
* Set the origin to Linuxbrew
* `git fetch origin`
* `git reset --hard HEAD`

Then `brew update && brew upgrade --all`

**Comment by sjackman** [comment]
Thanks for the bug report. The breakage is from this commit 981e9379a06e48acc743ad053060ac16b59aace2 which completely rewrites the `brew update` command. The workaround for now is to use `brew update-ruby` instead. I'll fix `brew update.

**Comment by sjackman** [comment]
Fixed. Thanks for the bug report. To fix your Linuxbrew installation, run…
```sh
cd `brew --prefix`
git remote set-url origin https://github.com/Linuxbrew/linuxbrew.git
```
