### ISSUE TITLE
fontconfig: Unable to build on Centos 6

### ISSUE THREAD

**Issue by mockbutler** [Linuxbrew/linuxbrew#824]
Looks like an issue with document generation and `nsgml`. Sorry I don't have time to dig further at this time.

[01.configure.txt](https://github.com/Linuxbrew/linuxbrew/files/135781/01.configure.txt)
[02.make.txt](https://github.com/Linuxbrew/linuxbrew/files/135779/02.make.txt)
[config.log.txt](https://github.com/Linuxbrew/linuxbrew/files/135780/config.log.txt)

**Comment by sjackman** [comment]
```
rm -f -r fontconfig-devel; \
	docbook2html -V '%use-id-as-filename%' -o fontconfig-devel local-fontconfig-devel.sgml
/bin/sh: line 1: docbook2pdf: command not found
```

**Comment by sjackman** [comment]
There's a related issue over here: https://github.com/servo/servo/issues/1790

**Comment by sjackman** [comment]
The following patch should workaround this issue. I don't know why I haven't see this issue myself.
For future bug reports, please use `brew gist-logs fontconfig`
```
diff --git a/Library/Formula/fontconfig.rb b/Library/Formula/fontconfig.rb
index 1835526..71731369 100644
--- a/Library/Formula/fontconfig.rb
+++ b/Library/Formula/fontconfig.rb
@@ -38,6 +38,7 @@ class Fontconfig < Formula
     system "./configure", "--disable-dependency-tracking",
                           "--disable-silent-rules",
                           "--enable-static",
+                          "--disable-docs",
                           "--with-add-fonts=/System/Library/Fonts,/Library/Fonts,~/Library/Fonts",
                           "--prefix=#{prefix}",
                           "--localstatedir=#{var}",
```

**Comment by maxim-belkin** [comment]
My solution which I recorded a while ago for myself:
```
path=$(brew --prefix)
# Fixing 'jw':
cp /usr/bin/jw "$path"/sbin/
sed -e 's|\[:space:\]|\[\[:space:\]\]|g' -e 's|tr\ \[\[:space:\]\]|tr\ \[:space:\]|g' /usr/bin/jw > "$path"/sbin/jw

# make sure we have pdfjadetex  ---  texlive  has it (brew install texlive)

# make sure we have docbook2pdf
echo "#! /bin/sh" > "$path"/sbin/docbook2pdf
echo "jw -f docbook -b pdf \"\$@\"" >> $path/sbin/docbook2pdf
chmod 0755 $path/sbin/docbook2pdf

# Have to remove libbz2.a before installing fontconfig
rm -f "$path"/lib/libbz2.a
brew install fontconfig
ln -s "$(brew --prefix bzip2)"/lib/libbz2.a "$path"/lib/libbz2.a
```
The `jw` file from `/usr/bin` is [here](https://github.com/Linuxbrew/linuxbrew/files/137277/jw.txt)
Just remove `.txt`

**Comment by sjackman** [comment]
I wonder why I haven't run into this error myself. I don't have `docbook2pdf` installed. I do have `docbook2man` and `docbook2texi`. Ah, I see. It checks if `docbook2html` is installed, and if it is, it assumes that `docbook2pdf` is also available.
See https://github.com/servo/servo/issues/1790#issuecomment-36426186
The workaround is to remove `docbook2html` from your `PATH` or add `docbook2pdf` to your `PATH`.

**Comment by sjackman** [comment]
You could report this bug upstream to the maintainers of `fontconfig` if you like.

**Comment by andrewyatz** [comment]
Just encountered this same problem on a RHEL7 box. Did not use the bottle because it's being installed to a non-default location. Managed to get it working by adding `--disable-docs` as you suggested above. What about adding in an optional flag to disable the docs building?

**Comment by sjackman** [comment]
A `--without-docs` option for `fontconfig` sounds like a good idea. Would you like to submit a pull request, Andrew?

**Comment by andrewyatz** [comment]
Sure thing shouldn't take long to rustle it up

**Comment by sjackman** [comment]
Packaging [docbook-tools](http://www.sourceware.org/docbook-tools/) for Linuxbrew would provide both `docbook2html` and `docbook2pdf`.
