### ISSUE TITLE
gpatch: libc.so.6: version `GLIBC_2.17' not found

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/linuxbrew#825]
There are no gist-logs produced. I get the following...

```
patch: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by patch)
Error: Failure while executing: patch -g 0 -f -p1
```

**Comment by sjackman** [comment]
Please report
```
brew list
brew config
```

One workaround is to reinstall `gpatch` from source. `brew reinstall gpatch -s`
Another is to install `glibc` with `brew install glibc`.

**Comment by jwhite007** [comment]
Thanks for the reply. I got the patch to work after "brew reinstall gpatch -s" I've attached files with output from "brew list" and "brew config" anyway.
[brew_list.txt](https://github.com/Linuxbrew/linuxbrew/files/138502/brew_list.txt)
[brew_config.txt](https://github.com/Linuxbrew/linuxbrew/files/138503/brew_config.txt)

I'm now getting build errors, however. The logs are here... https://gist.github.com/anonymous/73220c3c598665e04a42

**Comment by sjackman** [comment]
You had `glibc` installed, so the bottle for `patch` should have worked just fine for you. Can you report
```sh
brew reinstall patch
patch --version
```

**Comment by jwhite007** [comment]
Would you like me to run that on gpatch? I don't have patch installed. Did you mean "brew install patch"?

**Comment by sjackman** [comment]
Yes, I did. Sorry. I correct my above comment for future readers.

**Comment by jwhite007** [comment]
[brew_reinstall_gpatch.txt](https://github.com/Linuxbrew/linuxbrew/files/138556/brew_reinstall_gpatch.txt)

[ldd_which_patch.txt](https://github.com/Linuxbrew/linuxbrew/files/138559/ldd_which_patch.txt)

"patch --version"...
patch: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by patch)

**Comment by sjackman** [comment]
For files of only a few lines, you can post them inline in the comment enclosed in triple back ticks.

```
brew reinstall gpatch
==> Reinstalling gpatch
==> Downloading https://linuxbrew.bintray.com/bottles/gpatch-2.7.5.x86_64_linux.bottle.1.tar.gz
Already downloaded: /home/sbcuser/.cache/Homebrew/gpatch-2.7.5.x86_64_linux.bottle.1.tar.gz
==> Pouring gpatch-2.7.5.x86_64_linux.bottle.1.tar.gz
/toolbox/NGS/.linuxbrew/Cellar/gpatch/2.7.5: 9 files, 293.5K
```

```
ldd `which patch`
/toolbox/NGS/.linuxbrew/bin/patch: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /toolbox/NGS/.linuxbrew/bin/patch)
	linux-vdso.so.1 (0x00007ffca53fa000)
	libc.so.6 => /lib64/libc.so.6 (0x000000305fe00000)
	/toolbox/NGS/.linuxbrew/opt/glibc/lib/ld-linux-x86-64.so.2 (0x00007efc51c39000)
```

**Comment by sjackman** [comment]
The `RPATH` (where it looks for libraries) of `patch` is not set correctly, which is strange. Please report

Have you run `brew update` recently?
```sh
brew update
brew reinstall gpatch
ldd `which patch`
patch --version
```

If that fails, try
```sh
brew patchelf gpatch
ldd `which patch`
patch --version
```

**Comment by jwhite007** [comment]
I tried the triple-backtick in my comment above. I must be doing something wrong.

I run brew update before installing anything. I did it again with the same results.

As for the final bit... no luck. Same output as above.

**Comment by sjackman** [comment]
Please report the output of
```sh
brew patchelf gpatch -v
readelf -d `which patch` |head
```

**Comment by jwhite007** [comment]
brew patchelf gpatch -v...
==> Fixing up gpatch...
/toolbox/NGS/.linuxbrew/Cellar/patchelf/0.8/bin/patchelf --set-rpath /toolbox/NGS/.linuxbrew/lib --set-interpreter /toolbox/NGS/.linuxbrew/opt/glibc/lib/ld-linux-x86-64.so.2 /toolbox/NGS/.linuxbrew/Cellar/gpatch/2.7.5/bin/patch

readelf -d `which patch` | head...
Dynamic section at offset 0x21e18 contains 25 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [/toolbox/NGS/.linuxbrew/lib]
 0x000000000000000c (INIT)               0x401f68
 0x000000000000000d (FINI)               0x415698
 0x0000000000000019 (INIT_ARRAY)         0x61ee00
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x61ee08

**Comment by sjackman** [comment]
And… (please enclose the output in triple backticks)
```sh
which patch
ldd `which patch`
patch --version
```

**Comment by jwhite007** [comment]
which patch
/toolbox/NGS/.linuxbrew/bin/patch

ldd `which patch`
```/toolbox/NGS/.linuxbrew/bin/patch: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /toolbox/NGS/.linuxbrew/bin/patch)
        linux-vdso.so.1 (0x00007fff1d1d1000)
        libc.so.6 => /lib64/libc.so.6 (0x000000305fe00000)
        /toolbox/NGS/.linuxbrew/opt/glibc/lib/ld-linux-x86-64.so.2 (0x00007f923ada4000)```

patch --version
```patch: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by patch)```

**Comment by sjackman** [comment]
```sh
echo $LD_LIBRARY_PATH
```

**Comment by jwhite007** [comment]
```echo $LD_LIBRARY_PATH
/lib:/lib64:/usr/lib:/usr/lib64:/toolbox/NGS/.linuxbrew/lib:/toolbox/NGS/.linuxbrew/lib64:/toolbox/NGS/.linuxbrew/Cellar/lapack/3.6.0/lib64/:/toolbox/NGS/.linuxbrew/Cellar/openblas/0.2.15/lib```

**Comment by sjackman** [comment]
Triple back ticks have to go on their own line.

**Comment by sjackman** [comment]
Aha! I should have thought of that long before. Sorry. That took me way too long to catch on. You shouldn't need `/usr/lib` nor `~/.linuxbrew/lib` in your `LD_LIBRARY_PATH`. Try…
```
export LD_LIBRARY_PATH=/toolbox/NGS/.linuxbrew/Cellar/lapack/3.6.0/lib64/:/toolbox/NGS/.linuxbrew/Cellar/openblas/0.2.15/lib
ldd `which patch`
patch --version
```

**Comment by jwhite007** [comment]
I think we're getting somewhere...
```
ldd `which patch`
linux-vdso.so.1 (0x00007ffdd7ead000)
        libc.so.6 => /toolbox/NGS/.linuxbrew/lib/libc.so.6 (0x00007f90c6478000)
        /toolbox/NGS/.linuxbrew/opt/glibc/lib/ld-linux-x86-64.so.2 (0x00007f90c67f4000)
```
```
patch --version
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert
```

**Comment by jwhite007** [comment]
Compilation problems...

https://gist.github.com/2753db8191201cd0b706

**Comment by sjackman** [comment]
I get this error message when compiling `ea-utils`.
```
sam-stats.cpp:40:50: fatal error: samtools/sam.h: No such file or directory
```
Please open an issue over at https://github.com/Homebrew/homebrew-science

**Comment by jwhite007** [comment]
Ok. Thanks.

**Comment by philippbayer** [comment]
I ran into the same issue today on a weird Red Hat system I couldn't update, this issue is the first Google result so I'm putting my workaround here for future searchers.

Essentially I had to run

    brew reinstall gpatch -s

But the problem is that this will download a .tar.xz file, and on this system I could not extract .xz files, as that crashes the same way:

```
tar xJvf gpatch-2.7.5.tar.xz
xz: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by xz)
xz: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by linuxbrew/lib/liblzma.so.5)
```

To solve this I ran 

    brew edit gpatch

to replace the .xz link by a .gz link (as of today, there is a .gz file in the same folder with the same version, so just replace the x by g). I also had to replace the SHA256 sum in the same file, for `http://gnu.uberglobalmirror.com/patch/patch-2.7.5.tar.gz` the SHA256 sum is `7436f5a19f93c3ca83153ce9c5cbe4847e97c5d956e57a220121e741f6e7968f`. Running `brew reinstall gpatch -s` worked fine after that so that the output of

    ldd `which patch`

actually makes sense, from there I could run  `brew install glibc` and the rest worked OK.

**Comment by sjackman** [comment]
Hi, Philipp. Thanks for the work around. I've fixed this bug just now with https://github.com/Linuxbrew/homebrew-core/pull/1870

**Comment by philippbayer** [comment]
That's an even better solution. Thank you for your hard work on linuxbrew, it's tremendously useful!

**Comment by jwhite007** [comment]
@philippbayer both linuxbrew and @sjackman r0ck!!.
