### ISSUE TITLE
llvm: Cannot build llvm --with-lldb on linux

### ISSUE THREAD

**Issue by palad1** [Linuxbrew/linuxbrew#833]
The llvm.rb recipe blindly invokes KeyChain when building llvm : https://github.com/Linuxbrew/linuxbrew/blame/master/Library/Formula/llvm.rb#L160

Could you add a check for linux? Or am I missing a keychain equivalent here? Thanks

**Comment by sjackman** [comment]
Fixed. Thanks for the bug report.
