### ISSUE TITLE
Is Linuxbrew going to be part of the Software Freedom Conservancy?

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#835]
Since Homebrew is [officially a part of the Software Freedom Conservancy now](https://sfconservancy.org/news/2016/feb/22/homebrew-joins/), is Linuxbrew part of that?

Would be interested in @bkuhn's perspective on this as well.

**Comment by mikemcquaid** [comment]
It is not, it's a separate project.

**Comment by rwhogg** [comment]
Sad to hear that, but perfectly understandable.

**Comment by mikemcquaid** [comment]
There's nothing to stop Linuxbrew from applying separately but (as the person who drove the paperwork to get Homebrew to join): I'm not convinced it's worth the effort for the project at this time.

**Comment by sjackman** [comment]
I agree with Mike that it's not worth the effort at this time.

**Comment by bkuhn** [comment]
Conservancy does take applications from smaller projects, and there is a new program that we hope to launch to provide minimal services to small projects.  Watch our website for that, but in the meantime, can you make sure to carry a patchset in your fork to README.md (and any other relevant file that mentions Conservancy) so it doesn't give the impression that Linuxbrew is already a Conservancy member?  Currently, it seems you must have merged in upstream's README which leaves things a bit confusing.  I'd suggest a patch set that changes all that text about donations to Homebrew, etc. it to something like:

"Our upstream, Homebrew, is a member of Software Freedom Conservancy.  See their README.md (with a link) for more info and how to donate to them."

**Comment by sjackman** [comment]
Hi, Bradley. I've clarified in the README.md.

> Homebrew, the upstream project of Linuxbrew, is a member of the Software Freedom Conservancy
