### ISSUE TITLE
gobject-introspection force installs brewed Python

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/linuxbrew#836]
We noticed that something in Linuxbrew was force installing the brew version of Python. Shaun kindly did some investigation and figured out it was probably this package:

```
$ brew info gobject-introspection
==> Dependencies
Build: xz ✔, gpatch ✔
Required: pkg-config ✔, glib ✔, cairo ✔, libffi ✔, python ✔, bison ✔, flex ✔
```

I think the offending line might be this?

```
depends_on "python" if MacOS.version <= :mavericks
```

Should it have a `&& ! OS.Linux` or similar?
What does `MacOS.version` return on Linuxbrew?

**Comment by sjackman** [comment]
Does `gobject-introspection` fail to build if Python is not present?
I'm happy to merge a pull request changing it to
```ruby
depends_on "python" if OS.mac? && MacOS.version <= :mavericks
```

> What does MacOS.version return on Linuxbrew?

`MacOS.version` returns `0` on Linuxbrew.

**Comment by tseemann** [comment]
Shouldn't that pull request be too main Homebrew rather than Linuxbrew?

The formula already has lots of other `OS.mac?` type bits.

Or are they not accepting those anymore?

I'm not really clear on the policy/fallout of the split.

**Comment by sjackman** [comment]
Homebrew core does not accept `OS.mac?` conditionals. It has always been that way. Those `OS.mac?` bits that you see in the formula are only in Linuxbrew. Compare
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gobject-introspection.rb
and
https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Formula/gobject-introspection.rb
