### ISSUE TITLE
Can a Formula just link bin and not lib etc?

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/linuxbrew#837]
I am trying to write a package for Aspera (ascp).  it comes as a Unix shell installer with a uuencoded tar.gz embedded in it.  I can get it to install in `prefix` but it's file structure has `lib`, `etc` and so on.

The binaries are all launced via shell scripts which set up up paths to point to the correct bundled .so dynamic libraries (which i don't really want anyway as they are for the GUI bit).

So I want the `bin` to symlink in, but not the rest.  So it's a "partial keg".

Any suggestions?

Plan B: I could probably delete all the X11 gumpf and just keep the `ascp` binary.

**Comment by sjackman** [comment]
I would also like this feature, but it's not likely, I think. The Homebrew solution is to install to a subdirectory like `libexec`, and then create a symlink to the launching executable in `bin`.
