### ISSUE TITLE
R 3.2.3 - cairo-xlib.h: No such file or directory

### ISSUE THREAD

**Issue by tseemann** [Linuxbrew/linuxbrew#842]
Logs: https://gist.github.com/2cbb6eeb2192942d85c4

Could be related to this: https://github.com/Homebrew/homebrew/issues/48341

```
In file included from devX11.c:72:0:
devX11.h:64:26: fatal error: cairo-xlib.h: No such file or directory
compilation terminated.
../../../Makeconf:118: recipe for target 'devX11.o' failed
```

```
==> Dependencies
Build: pkg-config ✔, texinfo ✔, gpatch ✔
Required: readline ✔, gettext ✔, libtiff ✔, pcre ✔, jpeg ✔, libpng ✔, xz ✔
Optional: openblas ✔, pango ✔, valgrind ✔, cairo ✔
```

```
% find /bio/linuxbrew/ -name cairo-xlib.h
/bio/linuxbrew/Cellar/cairo/1.14.2/include/cairo/cairo-xlib.h
/bio/linuxbrew/Cellar/cairo/1.14.2_1/include/cairo/cairo-xlib.h
```

**Comment by sjackman** [comment]
`-I /bio/linuxbrew/Cellar/cairo/1.14.6_1/include/cairo` is in the search path. Do you have `cairo` 1.14.6_1 installed? Does `brew list | grep cairo-xlib` return anything?

**Comment by sjackman** [comment]
I have the same issue with recent cairo not installing `cairo-xlib.h`.
```
$ find `brew --cellar cairo` -name cairo-xlib.h
/gsc/btl/linuxbrew/Cellar/cairo/1.14.2/include/cairo/cairo-xlib.h
/gsc/btl/linuxbrew/Cellar/cairo/1.14.2_1/include/cairo/cairo-xlib.h
$ brew list cairo |grep cairo-xlib
# no matches
```

**Comment by sjackman** [comment]
I didn't have trouble installing R. I can't say why you are. Perhaps `brew install cairo --with-x11` will help you.

**Comment by sjackman** [comment]
I'm seeing this issue now as well. Did `brew install cairo --with-x11` resolve it for you? I'm trying that now. If it does, we should update either the `cairo` formula or the `r` formula for Linuxbrew, somehow.

**Comment by sjackman** [comment]
I fixed a build error in `libxml2 --with-python`, which is a dependency of `gtk-doc`, which is a dependency of `cairo --with-x11`.

**Comment by sjackman** [comment]
Building `cairo --with-x11` worked for me to fix this issue. Also `brew install r --with-x11` should also fix this issue. It's a bug that `brew install r --without-x11`, which is the default, still requires `cairo-x11`.

**Comment by sjackman** [comment]
Hmm. I was wrong. On Mac, the `x11` dependency of `r` is optional, but on Linux the dependency is recommended. Ah, I think this is the issue:
```ruby
  cairo_opts << :optional if OS.linux?
```
It looks as though `cairo` is no longer optional on Linux. Is there a `--without-cairo` option to pass to the configuration of R? Or should `cairo` be made a mandatory dependency on Linux, as it is on Mac?

**Comment by tseemann** [comment]
Building R without cairo or X11 would mean no graphical output? which is it's main use case here.

I've hit another brick wall:

```
brew reinstall cairo --with-x11
==> Reinstalling cairo with --with-x11
==> Downloading http://cairographics.org/releases/cairo-1.14.6.tar.xz
Already downloaded: /home/tseemann/.cache/Homebrew/cairo-1.14.6.tar.xz
==> ./configure --prefix=/bio/linuxbrew/Cellar/cairo/1.14.6_1 --enable-gobject=yes --enable-svg=yes --enable-tee=yes -
Last 15 lines from /home/tseemann/.cache/Homebrew/Logs/cairo/01.configure:
checking for X11/extensions/shmproto.h... yes
checking for X11/extensions/shmstr.h... yes
checking whether cairo's Xlib surface backend feature could be enabled... yes
checking for cairo's Xlib Xrender surface backend feature...
checking for xlib_xrender... no
checking for X11/extensions/Xrender.h... yes
checking for XRenderCreateSolidFill... yes
checking for XRenderCreateLinearGradient... yes
checking for XRenderCreateRadialGradient... yes
checking for XRenderCreateConicalGradient... yes
checking whether cairo's Xlib Xrender surface backend feature could be enabled... yes
checking for cairo's XCB surface backend feature...
checking for xcb... no
checking whether cairo's XCB surface backend feature could be enabled... no (requires xcb >= 1.6 xcb-render >= 1.6 http://xcb.freedesktop.org)
configure: error:  XCB surface backend feature could not be enabled

READ THIS: https://github.com/Linuxbrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

These open issues may also help:
harbour formula can't find "cairo.h" using --with-x11 option https://github.com/Homebrew/homebrew/issues/48341
```

**Comment by sjackman** [comment]
It's probably not searching your system directories. You can set up a fake keg as in #826. That's what I've done on my system. Check out #892 though, which is a WIP Linuxbrew formula for `xorg`.

**Comment by sjackman** [comment]
The `xorg` formula is working now.
```sh
brew install linuxbrew/xorg/xorg
brew install cairo --with-x11
brew install r
```

**Comment by tseemann** [comment]
**It worked!  **

**Comment by tseemann** [comment]
@sjackman - well that installed! But now I have the not-executable bug: https://github.com/Linuxbrew/linuxbrew/issues/614
