### ISSUE TITLE
bigloo fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#854]
bigloo fails to build on Ubuntu 14.04.

See https://gist.github.com/rwhogg/61b09802a09192d934e0

Message:
> + Configuring custom GC...
./configure: 24: export: -Wl,--dynamic-linker: bad variable name

Note that I'm not planning on actively working on this one.

**Comment by sjackman** [comment]
Okay. I won't be following up on this one either for now. Thanks for the bug report in any case, Bob.

**Comment by rwhogg** [comment]
This issue was moved to Linuxbrew/homebrew-core#145
