### ISSUE TITLE
Bottles, avoiding glibc and future changes?

### ISSUE THREAD

**Issue by yesimon** [Linuxbrew/linuxbrew#862]
It's been a while since I've updated linuxbrew but it seems like there's a new feature with bottled formula, but this requires a check against the version of `glibc`, and tries to install brewed `glibc` if necessary. I actually tried to do a clean standalone installation with a brewed `glibc`. Given that I'm running RHEL6 without sudo, the standalone installation process actually went quite smoothly, to which I applaud all the hard work the linuxbrew developers and contributors have put forth.

However I had numerous problems using standalone due to linking to a brewed `glibc` instead of whatever special sauce is in the RHEL `libc`. Now I'm going back to my hybrid installation that tries to link against system `libc` whenever possible. Therefore it turns out I need to set 

`export HOMEBREW_BUILD_FROM_SOURCE=1`

I think this should probably be documented in the regular linuxbrew installation, otherwise it wouldn't be too different from a standalone installation. Secondly, is there a mailing list for major feature changes such as this? Since linuxbrew is constantly evolving (kind of like arch linux), it seems reasonable to have an announcements for big news. I would definitely appreciate it!

**Comment by yesimon** [comment]
Some additional comments about linuxbrew standalone. I tried to go full scorched earth standalone, meaning that my `PATH` only contained linuxbrew bins. Unfortunately, a lot of formula have implicit dependencies, such as bash, perl, diffutils, tar, gzip etc. Honestly I don't think it's realistic to add these deps to formulas because we also need to support the non-standalone case. I don't know how to best manage this but just throwing out my 2 cents. Perhaps nobody is actually running a completely standalone install.

**Comment by sjackman** [comment]
> Perhaps nobody is actually running a completely standalone install.

I do! My `PATH` at work is set to `$HOMEBREW_PREFIX/bin` and nothing else. We could make a virtual package called `linuxbrew-core` that depends on all the utilities that are typically assume to be installed and available in the `PATH`.

Let's start a list:
`bash coreutils diffutils findutils gawk gnu-sed gnu-which grep gzip make perl ruby tar`

**Comment by sjackman** [comment]
> Secondly, is there a mailing list for major feature changes such as this?

No, there isn't. I'd like to keep everything on GitHub issues though. How about we start an issue called "Linuxbrew Updates", where I can post major changes?

**Comment by sjackman** [comment]
> However I had numerous problems using standalone due to linking to a brewed glibc instead of whatever special sauce is in the RHEL libc.

If you open an issue, I can try to resolve these issues. I don't have much to go on otherwise.

**Comment by sjackman** [comment]
> I think this should probably be documented in the regular linuxbrew installation, otherwise it wouldn't be too different from a standalone installation.

On system's with glibc 2.19 and newer, `glibc` is not installed by default, for example on Ubuntu 14 Trusty. On older systems, `glibc` is installed by default, and, yes, you're right it's about the same as Standalone Linuxbrew being the default on those older systems. I think that's a good thing, because the libraries on those systems are often very old as well.

Adding documentation is a good suggestion though. I'll add a paragraph to the `README.md`.

**Comment by sjackman** [comment]
Update documentation on bottles: https://github.com/Linuxbrew/linuxbrew#bottles

**Comment by sjackman** [comment]
Linuxbrew Updates is started over at #864

**Comment by sjackman** [comment]
The Debian virtual package [`build-essential`](https://packages.debian.org/sid/build-essential) depends on `gcc`, `glibc` and `make`. I expected more dependencies. I think that there are a lot more essential packages that are essential not just for building but for a running a Debian system.

**Comment by yesimon** [comment]
As for determining the base system. Would it be reasonable to have some way to test on travis a docker image of linuxbrew standalone, followed by installing the base packages. Then test the installation of every single package separately using this base system? (Each test will be -> start from base system + install the package). Then we can be confident that all implicit and transient dependencies will be satisfied? I'm not sure if this is how the brew test-bot currently works.

**Comment by sjackman** [comment]
I haven't got around to attempting to build all packages in Linuxbrew. It's a good idea, but a big undertaking.

**Comment by maxim-belkin** [comment]
I'm building everything from source. Now I'm struggling with `subversion --with-serf`...

**Comment by yesimon** [comment]
It might be good to add a little blurb on the homepage/README about subscribing to the Linuxbrew Updates issues to serve as a mailing list. (Didn't want to pollute the issue right now).

**Comment by sjackman** [comment]
> I'm building everything from source. Now I'm struggling with subversion --with-serf...

Do you need `--with-serf`? What doest it do? The patch #872 for `scons`, which I've just merged, may be related.

**Comment by sjackman** [comment]
> It might be good to add a little blurb on the homepage/README about subscribing to the Linuxbrew Updates issues to serve as a mailing list.

Done.

**Comment by maxim-belkin** [comment]
> Do you need `--with-serf`? What doest it do? The patch #872 for scons, which I've just merged, may be related.

Let me try that. I've tried adding that in SConstruct file before and it didn't work.

**Comment by sjackman** [comment]
I believe these issues are resolved. Feel free to open a new issue if you have unresolved questions.

**Comment by yesimon** [comment]
Thanks for your help!
