### ISSUE TITLE
mutt install fails on systems without "admin" group

### ISSUE THREAD

**Issue by marklee77** [Linuxbrew/linuxbrew#868]
# Please follow the general troubleshooting steps first:

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [NA] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

Commit 60595085dd25b19397cdcae1bca2f871236ce0ce introduced some some conditional behavior to setuid on the mutt_dotlock binary if the user is in the admin group. On systems without an admin group this causes the formula to fail. I was able to install mutt by commenting out the offending lines in the formula.

I took this up with homebrew, but it's wontfix as "admin" is a required system group on OSX.

**Comment by sjackman** [comment]
Thanks for the bug report, Mark. I don't have the time to fix it myself. Fell free to submit a pull request if you're so inclined.
