### ISSUE TITLE
Homebrew-versions linux support and keg paths

### ISSUE THREAD

**Issue by yesimon** [Linuxbrew/linuxbrew#874]
I was trying to install `gcc49` through homebrew-versions and realized that it didn't have any linuxbrew linux clauses (many OS X specific clauses). I would have thought that the old mainline `gcc` formula would simply become the versioned `gccxx.rb` formula once a new gcc formula was released (of course with tweaks for versioned dependencies as well). Support for linux seems a bit sparse for now.

The second issue is that versioned software formulae should have:

`Env.append "LDFLAGS", "-Wl,-rpath=${Formula["dependencyxy"].opt_prefix}"`

To set the rpath to the keg old versioned library. This is because the default rpath of `$(brew --prefix)/lib` won't work with keg dependencies because they are unlinked. As a general rule, it might make sense to do `$LDFLAGS` for the `opt_prefix` of each dependency automatically, but of course the caveat being that the build process might not respect the env `$LDFLAGS` variable.

**Comment by sjackman** [comment]
Homebrew/versions is not a supported tap of Linuxbrew. You could, if you like, adopt the maintenance of it. If it goes well, we can start a fork in Linuxbrew/versions.

I agree with your assessment of the RPATH.
