### ISSUE TITLE
Chapel is not linked correctly on Ubuntu 14.04

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#876]
Chapel does not link correctly on Ubuntu 14.04. It does compile correctly though; for example, you can run `~/.linuxbrew/opt/chapel/libexec/bin/linux64/chpl --version` and it works.

See https://gist.github.com/04fb73154746b7e279d5

Message:
> Warning: tried to install empty array to /home/bob/.linuxbrew/Cellar/chapel/1.12.0/bin

The fix for this looks fairly obvious, so I'll probably be able to make a PR soon.

**Comment by sjackman** [comment]
If you plan on submitting a pull request, there's no need to also submit an issue. Just the PR is fine.
