### ISSUE TITLE
brew: command not found

### ISSUE THREAD

**Issue by dagolinuxoid** [Linuxbrew/linuxbrew#878]
Elementary OS Freya 64-bit ( =ubuntu)

`sudo apt-get install build-essential curl git m4 python-setuptools ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev`

`git clone https://github.com/Linuxbrew/linuxbrew.git ~/.linuxbrew`

Add to your .bashrc or .zshrc: (I added in both):
`export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"`

linux@linux-desktop:~$ brew install node
No command 'brew' found, did you mean:
 Command 'brec' from package 'bplay' (universe)
 Command 'qbrew' from package 'qbrew' (universe)
brew: command not found
So sad :)

**Comment by DoomHammer** [comment]
You should probably re-read the shell config file, eg. `source ~/.bashrc` if you use `bash`.

**Comment by dagolinuxoid** [comment]
Sorry, my bad. It requires reboot.

**Comment by sjackman** [comment]
Opening a new terminal should fix it too.
