### ISSUE TITLE
Problem with brewed python

### ISSUE THREAD

**Issue by DoomHammer** [Linuxbrew/linuxbrew#889]
When I try to brew `python` system libraries mix up with brewed ones which causes crash like this: https://gist.github.com/anonymous/e5473c56b13252e73e3f . Is there a way to make brewed Python "self-contained"?

**Comment by sjackman** [comment]
Python is a mess because it likes to hardcode search paths into `/usr/lib`. The recently merged #886 may help with this, but I'm not convinced that it's comprehensive. Are you using the Linuxbrew installed `gcc`? That definitely helps. So in short, no, but pull requests are welcome if you can find a fix.

When posting a massive gist, please quote and link to the interesting line.

**Comment by DoomHammer** [comment]
Yes, I am using `gcc` that I also brewed (`--with-glibc`). Tried again after an update but still the problem persists.

On the side note: a friend of mine who prepares cross-compilation toolchains and distros also had a few bad words about Python ;)

Sorry about the gist.

**Comment by maxim-belkin** [comment]
According to the gist log you provided, you are using system's gcc:
```
Linuxbrew gcc: N/A
```

**Comment by DoomHammer** [comment]
EIther I posted a wrong gist or something funny is happening. Yesterday I tried installing Python I saw ~/.linuxbrew/bin/gcc-5.3 passing by.

**Comment by DoomHammer** [comment]
It's even more ridiculous with `python3`:

```
  File "/home/doomhammer/.linuxbrew/Cellar/python3/3.5.1/lib/python3.5/distutils/command/install.py", line 551, in run
    self.run_command(cmd_name)
  File "/home/doomhammer/.linuxbrew/Cellar/python3/3.5.1/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/doomhammer/.linuxbrew/Cellar/python3/3.5.1/lib/python3.5/distutils/dist.py", line 973, in run_command
    cmd_obj.ensure_finalized()
  File "/home/doomhammer/.linuxbrew/Cellar/python3/3.5.1/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 13, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/home/doomhammer/.linuxbrew/Cellar/python3/3.5.1/lib/python3.5/distutils/cmd.py", line 290, in set_undefined_options
    setattr(self, dst_option, getattr(src_cmd_obj, src_option))
  File "/home/doomhammer/.linuxbrew/Cellar/python3/3.5.1/lib/python3.5/distutils/cmd.py", line 103, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout

```

What's `/usr/lib/python2.7` doing there?

**Comment by sjackman** [comment]
I'm afraid I really don't know. I guess you'd have to figure out what Python's library search path is and debug that.

**Comment by DoomHammer** [comment]
Exactly what I am trying to do :)

BTW: is there an easy way to `brew` a package with debugging symbols?

**Comment by DoomHammer** [comment]
Maybe my system was insane (or even I, myself), but after some `brew install`, `brew uninstall` cha-cha `python` seems to be a) working fine b) no trace of strange paths in `sys.path`. I think the best solution now is a glass of wine.

**Comment by sjackman** [comment]
> is there an easy way to brew a package with debugging symbols?

It's the default now. It used to be the default to `strip` installed executables. I don't know when this changed.

**Comment by sjackman** [comment]
That sounds great, Piotr. =) :wine_glass:
Linuxbrew is still a moving target. It can tricky to determine exactly which previous patch resolved your issue.
