### ISSUE TITLE
neovim fails loading shared library libstdc++.so.6 on centos7

### ISSUE THREAD

**Issue by gacha** [Linuxbrew/linuxbrew#896]
# Please follow the general troubleshooting steps first:

- [ x] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?

### Bug report:

Tried to install novim on centos 7, fails. But recently installed successfully on debian 8. Also the lib it complains about is installed in `/usr/lib64/libstdc++.so.6`:
```
==> Building third-party dependencies.
==> cmake ../third-party -DUSE_BUNDLED_BUSTED=OFF -DUSE_EXISTING_SRC_DIR=ON -DCM
Last 15 lines from /home/gatis/.cache/Homebrew/Logs/neovim/01.cmake:
cmake
../third-party
-DUSE_BUNDLED_BUSTED=OFF
-DUSE_EXISTING_SRC_DIR=ON
-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG
-DCMAKE_INSTALL_PREFIX=/home/gatis/.linuxbrew/Cellar/neovim/0.1.2
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_FIND_FRAMEWORK=LAST
-DCMAKE_VERBOSE_MAKEFILE=ON
-Wno-dev
-DCMAKE_BUILD_WITH_INSTALL_RPATH=1
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=1

cmake: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

https://gist.github.com/anonymous/aa91707471e467dd797e.

**Comment by sjackman** [comment]
`brew install gcc` may work around this issue.

**Comment by gacha** [comment]
That worked, but now there is next problem with ncurses
```
xgettext failed to run correctly: /home/gatis/.linuxbrew/bin/xgettext:
  error while loading shared libraries: libncurses.so.5: cannot open shared
  object file: No such file or directory
```
I installed `brew install ncurses` but nothing changed.

**Comment by sjackman** [comment]
`gettext` was compiled against `ncurses 5.9` but `ncurses` was upgraded to `6.0`.
`brew reinstall gettext`
You may need to reinstall other packages.
`brew uses --installed ncurses`

**Comment by gacha** [comment]
Thank you very much, it worked, maybe you can put top 10 fixes in the readme.

**Comment by sjackman** [comment]
Glad to hear it worked. Figuring out how to better handle library upgrades is definitely on my radar.
