### ISSUE TITLE
openssl: LFCN_LOAD:could not load the shared library: libz.so: cannot open shared object file

### ISSUE THREAD

**Issue by ijkim88** [Linuxbrew/linuxbrew#897]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

Did not see any permission errors.

### Bug reports:

Am I missing dependencies? I followed all the linuxbrew dependency steps and troubleshooting steps.
https://gist.github.com/anonymous/246d24b39b630855c98e

**Comment by ijkim88** [comment]
The workaround @sjackman mentioned in [#732](https://github.com/Linuxbrew/linuxbrew/issues/732) works for me.

**Comment by sjackman** [comment]
Glad to hear that the workaround worked for you.
```sh
brew install gcc openssl
```

**Comment by sjackman** [comment]
https://gist.github.com/anonymous/246d24b39b630855c98e#file-04-make-L560
```
139901738440384:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libz.so): libz.so: cannot open shared object file: No such file or directory
139901738440384:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:233:
139901738440384:error:29064065:lib(41):BIO_ZLIB_NEW:zlib not supported:c_zlib.c:463:
140352479790784:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:187:filename(libz.so): libz.so: cannot open shared object file: No such file or directory
140352479790784:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:233:
140352479790784:error:29064065:lib(41):BIO_ZLIB_NEW:zlib not supported:c_zlib.c:463:
cmp: EOF on ./p.zlib.clear
make[1]: *** [test_enc] Error 1
make[1]: Leaving directory `/tmp/openssl20160307-8018-1ebzb41/openssl-1.0.2g/test'
```

**Comment by sjackman** [comment]
Here's another workaround for this issue:
```sh
LD_LIBRARY_PATH=`brew --prefix`/lib brew install openssl
```

**Comment by sjackman** [comment]
Fixed!

**Comment by sjackman** [comment]
Setting `LD_RUN_PATH` broke installs that have `glibc` installed but not `gcc`. See #904.

**Comment by sjackman** [comment]
I believe this issue is fixed! Can you test it for me?

**Comment by ijkim88** [comment]
It's working great now, thanks!

**Comment by sjackman** [comment]
Great!
