### ISSUE TITLE
libsoup fails to install when XDG_DATA_DIRS is not set to $(brew --prefix)/share

### ISSUE THREAD

**Issue by DoomHammer** [Linuxbrew/linuxbrew#899]
Tried upgrading `libsoup` and got greeted with

```
$HOME/.linuxbrew/Cellar/vala/0.30.1/bin/vapigen-0.30 --metadatadir=../libsoup --pkg gio-2.0 --library=libsoup-2.4 Soup-2.4.gir Soup-2.4.metadata Soup-2.4-custom.vala
error: Package `Gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Generation failed: 1 error(s), 0 warning(s)
make[2]: *** [libsoup-2.4.vapi] Error 1
```

After searching a bit I found out that `vapigen` makes use of `$XDG_DATA_DIRS` but in a curious way.
- If the variable is unset it succeeds.
- If the variable is set and contains `$(brew --prefix)/share` it also succeeds.
- But if the variable is set and does not contain `$(brew --prefix)/share` then it fails as seen above.

Now, in my case `$XDG_DATA_DIRS` is set by my window manager and contains only system paths. I have modified my shell's rc file to prepend `$(brew --prefix)/share` to this variable but this is obviously a workaround.

Question is: should `brew` modify this variable during installation (what about runtime then?) or should user be responsible for setting it correctly in one's own `.rc` (which should then be documented and `brew doctor` should whine about incorrect setting)?

More info on `$XDG_*` can be found in [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by sjackman** [comment]
I suppose it depends on how pervasive this problem is. If it affects only this one formula, then it could be hacked around within this one formula, but I'm going to guess that it affects many formula. In which case, the user should probably modify their environment globally. Adding a `brew doctor` check makes sense, I think. If `XDG_DATA_DIRS` is not set, then everything is fine. If it is set, check that it contains `$(brew --prefix)/share`.

**Comment by DoomHammer** [comment]
35 formulae depend on Vala so could be potentially problematic. I see two of them having special treatment, though, `libgweather` and `libsoup`:

```
# ensures that the vala files remain within the keg
inreplace "libsoup/Makefile.in", "VAPIDIR = @VAPIDIR@", "VAPIDIR = @datadir@/vala/vapi"
```

**Comment by DoomHammer** [comment]
Ok, just saw I was counting duplicates somehow. The list goes like this:

```
anjuta.rb
baobab.rb
gcab.rb
gitg.rb
gmime.rb
gnome-builder.rb
gspell.rb
gxml.rb
libchamplain.rb
libgdata.rb
libgee.rb
libgit2-glib.rb
libgweather.rb
liblunar.rb
libsecret.rb
libsoup.rb
msitools.rb
radare2.rb
submarine.rb
valabind.rb
vala.rb
vte3.rb
```

**Comment by sjackman** [comment]
I think that the `brew doctor` solution is the simplest. Does it only affect `vala` or also other packages that use `XDG_DATA_DIRS`?

**Comment by DoomHammer** [comment]
Tried to check those formulae on `sjackman/linuxbrew` but run into problem with `python`. Yak-shaving time, I presume.

**Comment by sjackman** [comment]
Why `sjackman/linuxbrew`? Did you mean `Linuxbrew/linuxbrew`?

**Comment by DoomHammer** [comment]
I meant the Docker image :)

**Comment by sjackman** [comment]
Right of course. There's actually a `linuxbrew/linuxbrew` docker image now too! Check it out.
https://hub.docker.com/r/linuxbrew/linuxbrew/

**Comment by DoomHammer** [comment]
Just when I thought I am finally doing what the cool kids are doing it seems everybody has a new toy now. Too old for this, I think :(

Will try it anyway and report my findings.

**Comment by DoomHammer** [comment]
OK, results of my audit are in:

anjuta - `libepoxy` fails
baobab - `libepoxy` fails
gcab - **affected**
gitg - `libepoxy` fails
gmime - unaffected
gnome-builder - `libepoxy` fails
gspell - `gtk+` fails
gxml - **affected**
libchamplain - `cogl` fails
libgdata - **affected**
libgee - unaffected
libgit2-glib - unaffected
libgweather - `libepoxy` fails
liblunar - unaffected
libsecret - fails due to lack of `gsed`
libsoup - **affected**
msitools - **affected**
radare2 - unaffected
submarine - **affected**
valabind - unaffected
vala - unaffected
vte3 - `libexpoy` fails

This means there are at least 6 packages that are affected by this variable.

**Comment by sjackman** [comment]
Seems like a global fix would be better than hacking each package then, since it probably affects some of the `fails` packages as well. A `doctor` check then? What do you think?

**Comment by DoomHammer** [comment]
Seems fine. Could you point me to the best place to steal, I mean, get inspiration from?

**Comment by sjackman** [comment]
Like this?
https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Formula/a2ps.rb#L33
```ruby
    system "./configure", "--disable-debug", "--disable-dependency-tracking",
                          "--prefix=#{prefix}", "--sysconfdir=#{etc}",
                          "--with-lispdir=#{share}/emacs/site-lisp/#{name}"
```

**Comment by DoomHammer** [comment]
Was thinking about hacking `https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Homebrew/diagnostic.rb` since this is where it belongs, isn't it?

**Comment by DoomHammer** [comment]
The most interesting question is: how to add a function that would be used by `brew doctor` only on Linux (as I understand Mac OS X is unaffected)? I see eg. `check_user_path_1` definition, but cannot find any usage. Or is it powered by some hoppy magic?

**Comment by sjackman** [comment]
There's no need for it to be platform specific, because it will only report a message if `XDG_DATA_DIRS` is set, and it won't be on Mac.
Yes, add a `check_x` function to `diagnostic.rb`.
Any function named `check_*` is run automatically, by zany magics.

**Comment by DoomHammer** [comment]
Yeah, found it out on my own in the meantime. I hacked a wee bit of
checking so will submit in not so distant future. BTW: How to run tests as
I would like to add them as well?

**Comment by sjackman** [comment]
```
brew tests TEST=test_filename.rb
```
Will run only the test in that one file. `brew tests` runs them all.

**Comment by DoomHammer** [comment]
Done in #919
