### ISSUE TITLE
OpenSSL install breaking on Uberspace

### ISSUE THREAD

**Issue by phime42** [Linuxbrew/linuxbrew#904]
Hello!
I ran linuxbrew for months without any issue on my Uberspace, then it stopped working, I tried to reinstall - now, OpenSSL's build is constantly failing.
Do you have any idea?

https://gist.github.com/f962327b84b18c7f8f36

Thank you so much.

phime42

**Comment by sjackman** [comment]
Does either `brew postinstall openssl` or `brew reinstall openssl` help?

**Comment by sjackman** [comment]
These error messages don't make much sense to me. =/
https://gist.githubusercontent.com/anonymous/f962327b84b18c7f8f36/raw/c4327c5f9c1c59c49b29dd8a3f87f18e9eba5dab/04.make
```
Response Verify Failure
140458564159144:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:rsa_pk1.c:103:
140458564159144:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:rsa_eay.c:705:
140458564159144:error:0D0C5006:asn1 encoding routines:ASN1_item_verify:EVP lib:a_verify.c:218:
140458564159144:error:27069065:OCSP routines:OCSP_basic_verify:certificate verify error:ocsp_vfy.c:138:Verify error:certificate signature failure
=== INVALID SIGNATURE on the ISSUER CERTIFICATE ===
NON-DELEGATED; Intermediate CA -> EE
Response verify OK
NON-DELEGATED; Root CA -> Intermediate CA
Response verify OK
NON-DELEGATED; Root CA -> EE
Response verify OK
DELEGATED; Intermediate CA -> EE
Response verify OK
DELEGATED; Root CA -> Intermediate CA
Response verify OK
DELEGATED; Root CA -> EE
Response verify OK
ALL OCSP TESTS SUCCESSFUL
Test X509v3_check_*
../util/shlib_wrap.sh ./v3nametest
../util/shlib_wrap.sh ./heartbeat_test
make[1]: *** [test_heartbeat] Speicherzugriffsfehler
make[1]: Leaving directory `/tmp/openssl20160311-10464-6c0742/openssl-1.0.2g/test'
make: *** [tests] Fehler 2
```

**Comment by phime42** [comment]
I'm trying `brew reinstall openssl` right now.
I also do not understand the error messages, but `make[1]: *** [test_heartbeat] Speicherzugriffsfehler` means `... Memory access error` and `make: *** [tests] Fehler 2` means `... Error 2`.
I however have no idea what these error messages mean technically.

**Comment by sjackman** [comment]
Can you try compiling OpenSSL without using Linuxbrew? If you get the same error message, please report it to the upstream OpenSSL developers.

**Comment by retrography** [comment]
I get similar errors here on Centos 6. Standalone build works. Only Linuxbrew's build fails. Please note that it is the `make test` that fails. Here is the same set of messages in English:

```
==> make test
Last 15 lines from /home/mszargar/.cache/Homebrew/Logs/openssl/04.make:
NON-DELEGATED; Root CA -> EE
Response verify OK
DELEGATED; Intermediate CA -> EE
Response verify OK
DELEGATED; Root CA -> Intermediate CA
Response verify OK
DELEGATED; Root CA -> EE
Response verify OK
ALL OCSP TESTS SUCCESSFUL
Test X509v3_check_*
../util/shlib_wrap.sh ./v3nametest
../util/shlib_wrap.sh ./heartbeat_test
make[1]: *** [test_heartbeat] Segmentation fault
make[1]: Leaving directory `/tmp/openssl20160311-13539-13nym8t/openssl-1.0.2g/test'
make: *** [tests] Error 2
```

**Comment by phime42** [comment]
Is there a way to skip the tests in order to get the install working? It's kind of a redneck solution, but atm I'm stuck...

**Comment by retrography** [comment]
Yes there is a switch for that: 
    brew install --without-test openssl

**Comment by phime42** [comment]
That worked for me, but it's not fixing it entirely... I may have to try to run `make test` on its own and check with upstream, like sjackman suggested.

**Comment by sjackman** [comment]
`brew install gcc openssl` may also fix it.

**Comment by sjackman** [comment]
Testing this now over here: https://travis-ci.org/Linuxbrew/linuxbrew/builds/115954002
