### ISSUE TITLE
Torch7 package

### ISSUE THREAD

**Issue by albertz** [Linuxbrew/linuxbrew#910]
Some Torch7 package would be nice. It's really complicated to do the setup (without root access, so I cannot easily install the dependencies, and their setup script doesn't find my Linuxbrew libs in all cases).

Maybe this is helpful: https://github.com/torch/distro/issues/70

Ultimately, I fail to install it now because of: https://github.com/zeromq/lzmq/issues/45

**Comment by sjackman** [comment]
Submit a pull request with the formula if you have the inclination. There are links to docs to help you with how to create a formula in CONTRIBUTING.md.

**Comment by sjackman** [comment]
I don't have the time myself unfortunately to take packaging requests.

**Comment by CDLuminate** [comment]
@albertz Actually Debian packaging script may provide some help for creating new brew formulas in ruby . However the style of Brew formulas are similar to `pkgbuild` (Archlinux) or `ebuild` from Gentoo, so one might get more helpful snippets from AUR(archlinux user repo) packaging scripts related to Torch.

**Comment by CDLuminate** [comment]
@albertz You may need to change some CMAKE variables for the Torch CMake files. e.g. appending your brew lib directory to cmake LDFLAGS.
