### ISSUE TITLE
GNU Common C++ package

### ISSUE THREAD

**Issue by albertz** [Linuxbrew/linuxbrew#911]
We already have GNU uCommon C++ (package [ucommon](https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Formula/ucommon.rb)) but not GNU Common C++.

https://www.gnu.org/software/commoncpp/

**Comment by sjackman** [comment]
Assuming this software will also compile on Mac OS please submit this issue upstream to Homebrew/Homebrew. Submit a formula with a pull request if you can.

**Comment by albertz** [comment]
I think actually I was wrong and uCommon includes Common.
