### ISSUE TITLE
curl: symbol lookup error

### ISSUE THREAD

**Issue by albertz** [Linuxbrew/linuxbrew#912]
```
zeyer@sulfid ~/c/torch> brew install -s ruby
==> Installing dependencies for ruby: openssl
==> Installing ruby dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2g.tar.gz
/work/asr2/zeyer/linuxbrew/opt/curl/bin/curl: symbol lookup error: /work/asr2/zeyer/linuxbrew/Cellar/curl/7.45.0/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos
Trying a mirror...
==> Downloading https://dl.bintray.com/homebrew/mirror/openssl-1.0.2g.tar.gz
/work/asr2/zeyer/linuxbrew/opt/curl/bin/curl: symbol lookup error: /work/asr2/zeyer/linuxbrew/Cellar/curl/7.45.0/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos
Trying a mirror...
==> Downloading https://www.mirrorservice.org/sites/ftp.openssl.org/source/openssl-1.0.2g.tar.gz
/work/asr2/zeyer/linuxbrew/opt/curl/bin/curl: symbol lookup error: /work/asr2/zeyer/linuxbrew/Cellar/curl/7.45.0/lib/libcurl.so.4: undefined symbol: SSL_CTX_set_alpn_protos
Error: Failed to download resource "openssl"
Download failed: https://www.mirrorservice.org/sites/ftp.openssl.org/source/openssl-1.0.2g.tar.gz
```

I already did `brew unlink curl` because of this (somehow my Curl got broken it seems) but this does not make a difference.

**Comment by albertz** [comment]
This fixed it for me:

```
rm /work/asr2/zeyer/linuxbrew/opt/curl
```

Now it again uses my system Curl which works.

Shouldn't `brew unlink curl` have also removed that link?

**Comment by DoomHammer** [comment]
Best way is to `brew fetch openssl && brew install openssl` then proceed to working as always. Same for `brew upgrade`.

**Comment by sjackman** [comment]
Try
```sh
brew remove openssl curl
brew fetch openssl curl
brew install curl
```
If that fails, `brew install gcc` and repeat above.
Check `LD_LIBRARY_PATH` for conflicting `openssl` libraries.

**Comment by albertz** [comment]
Well, `rm /work/asr2/zeyer/linuxbrew/opt/curl` fixed it already. After that, it uses my system curl and it worked just fine. After reinstalling Linuxbrew openssl and curl, also Linuxbrew curl worked again.

Maybe Linuxbrew should detect if Curl is broken? It wrongly assumes that the download server is down and tries another mirror.

**Comment by DoomHammer** [comment]
I like @albertz's suggestion. @sjackman, do you have an idea how this could be implemented?

**Comment by sjackman** [comment]
I don't feel that's necessary. Yes, `curl` can break due to shared library issues, but so can any command line application.

**Comment by sjackman** [comment]
Glad that you got it working, Albert.
