### ISSUE TITLE
Bash: Failure while executing: patch

### ISSUE THREAD

**Issue by iggyvolz** [Linuxbrew/linuxbrew#913]
When running brew upgrade bash, I get this:
https://gist.github.com/6b97bedbdfdd443f9acf

I'd love to run a gist-logs on it, but I get "Error: No logs." - which might be a separate bug altogether.

**Comment by sjackman** [comment]
Interesting. It looks like the patch may be outdated and possibly fails to apply cleanly.

**Comment by rwhogg** [comment]
It fails in the exact same way on `brew install` too.

**Comment by sjackman** [comment]
It's odd that `/usr/bin/patch` 2.5.8 on Mac has no trouble with this patch.

**Comment by iggyvolz** [comment]
[Removing the first three lines](https://gist.github.com/iggyvolz/53f630ac1623f1dae247/revisions) managed to get rid of the "-i" error, but it still failed with the same error, and failed to produce logs.

Updated gist: https://gist.github.com/iggyvolz/e930c45f638cdb86a693

**Comment by rwhogg** [comment]
I've got a patch that works: https://gist.github.com/rwhogg/01577b5fa1820edfd31d

I'm not going to make a PR for this right this instant for two reasons:

a) I think we need to figure out why this wasn't affecting OS X as @sjackman hinted at above and
b) I'd like to know what exactly _bg.po is. I know it's a translation file for Bulgarian, but I'm not sure why it needed to be deleted. My *guess* based on the bizarre leading underscore is that it was an editor-created temp/backup file that got committed accidentally and was subsequently removed upstream, but I'd want to check the changelogs to be sure.

**Comment by sjackman** [comment]
My guess is that the `patch` behaviour difference is due to different versions of `patch`.

**Comment by iggyvolz** [comment]
I just downloaded the tar.gz, and the _bg.po file isn't in there.  I have a [reference to the file being deleted](https://fossies.org/diffs/bash/4.3_vs_4.3.30/) at some point between 4.3 and 4.3.30, so my guess is the patch is just outdated and it was added by accident.  I'm guessing OS X's patch just ignores the error, but linux's patch is more strict and fails - if this is the case then it's an error with the patch, and rwhogg's fork should be updated at Homebrew (since it's technically an error on Mac, it's just failing).  I'll check on my mac later today whether this is the case, I can make a PR over there.

**Comment by sjackman** [comment]
Yes, I agree with Iggy. If it's not failing on Mac, Homebrew may or may not accept the patch, but you can certainly try.

**Comment by iggyvolz** [comment]
This was fixed with Homebrew/homebrew#50123.  The offending patch was manually generated, and the nonexistent files were added by mistake.

Will leave open until it is merged in, and then confirmed to work on linux.

**Comment by sjackman** [comment]
I believe this issue is resolved.
