### ISSUE TITLE
Bowtie2 doesn't install on CentOS

### ISSUE THREAD

**Issue by grandeabobora** [Linuxbrew/linuxbrew#914]
I tried to install bowtie2 on a CentOS machine and I couldn't. Here is the link with the gist log: https://gist.github.com/anonymous/a1b3d4bc12e9c928faf6

It was the first time I tried to use brew on a Linux machine, but I've been using it on a Mac since 2010.

Also, 

$ brew doctor
Your system is ready to brew.

**Comment by sjackman** [comment]
It looks as though it fails to build with GCC 4.8.
Try `brew install gcc bowtie2`

**Comment by grandeabobora** [comment]
I tried to compile with gcc 5.3.0, but still doesn't work.

**Comment by sjackman** [comment]
This issue was moved to Homebrew/homebrew-science#3440
