### ISSUE TITLE
nettle does not compile on Uberspace

### ISSUE THREAD

**Issue by phime42** [Linuxbrew/linuxbrew#915]
Hello!

I still try to install WeeChat via linuxbrew and am stuck with the nettle dependency. Here's what I'm getting after I try to install nettle:
```
$ brew install nettle
==> Downloading https://www.lysator.liu.se/~nisse/archive/nettle-3.2.tar.gz
Already downloaded: /home/mp6/.cache/Homebrew/nettle-3.2.tar.gz
==> ./configure --prefix=/home/mp6/.linuxbrew/Cellar/nettle/3.2 --enable-shared
==> make
==> make install
==> make check
Error: File exists @ dir_s_mkdir - /home/mp6/.linuxbrew/Cellar/nettle/3.2/lib
```

The directory  `/home/mp6/.linuxbrew/Cellar/nettle/` does not exist, creating it creates this message: 
```
$ brew install nettle
Warning: nettle-3.2 already installed, it's just not linked`
```
If i do `brew link nettle`, this is the result:
```
$ brew link nettle
Linking /home/mp6/.linuxbrew/Cellar/nettle/3.2... 0 symlinks created`
```

Which makes installing gnutls further down the road fail with: 
```
configure: error: 
  ***
  *** Libnettle 3.1 was not found.
```

Gist-Logs for nettle are here: https://gist.github.com/62558efbab64662a3e21

Thank you so much for your help!

**Comment by sjackman** [comment]
To escape multiple lines in back ticks, you need to use triple back ticks. See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

**Comment by sjackman** [comment]
Fixed! Thanks for the bug report.

**Comment by phime42** [comment]
Thank you for your help!
