### ISSUE TITLE
qwt fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by rwhogg** [Linuxbrew/linuxbrew#927]
`qwt` fails to build on Ubuntu 14.04. See https://gist.github.com/rwhogg/61fcc768582132fd8f86

Message:
> g++: error: 6.1: No such file or directory
g++: error: 6.1.2: No such file or directory
g++: error: libqwt.6.dylib: No such file or directory
g++: error: OpenGL: No such file or directory
g++: error: AGL: No such file or directory
g++: error: unrecognized command line option '-h'
g++: error: unrecognized command line option '-single_module'
g++: error: unrecognized command line option '-compatibility_version'
g++: error: unrecognized command line option '-current_version'
g++: error: unrecognized command line option '-install_name'
g++: error: unrecognized command line option '-framework'
g++: error: unrecognized command line option '-framework'
Makefile:370: recipe for target '../lib/libqwt.6.1.2.dylib' failed
make[1]: *** [../lib/libqwt.6.1.2.dylib] Error 1
make[1]: Leaving directory '/home/bob/tmp/qwt20160313-3077-jtc4os/qwt-6.1.2/src'
Makefile:42: recipe for target 'sub-src-make_default-ordered' failed
make: *** [sub-src-make_default-ordered] Error 2

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

**Comment by sjackman** [comment]
Patch this line:
https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Formula/qwt.rb#L39

**Comment by sjackman** [comment]
```ruby
    if ENV.compiler == :clang && MacOS.version >= :mavericks
      args << "unsupported/macx-clang-libc++"
    else
      args << "macx-g++"
    end
```
