### ISSUE TITLE
Glibc postinstall error with LC_CTYPE=fr_FR.utf8

### ISSUE THREAD

**Issue by Luthaf** [Linuxbrew/linuxbrew#929]
This environment variable is set by default on my machine (CentOS 7) by my system administrator I presume. 

The exact error is 
```
$ brew install glibc
[...]
==> Installing glibc
==> Downloading http://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
Already downloaded: ~/.cache/Homebrew/glibc-2.19.tar.bz2
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=~/.linuxbrew/Cellar/glibc/2.19 --enable-obsolete-rpc --without-selinux --with-binutils=~
==> make
==> make install
==> ~/.linuxbrew/Cellar/glibc/2.19/bin/localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
==> ~/.linuxbrew/Cellar/glibc/2.19/bin/localedef -i fr_FR -f utf8 fr_FR.utf8
Last 15 lines from ~/.cache/Homebrew/Logs/glibc/02.localedef:
2016-03-14 15:17:38 +0100

~/.linuxbrew/Cellar/glibc/2.19/bin/localedef
-i
fr_FR
-f
utf8
fr_FR.utf8

fichier de la table des caractères « utf8 » non repérable: Aucun fichier ou dossier de ce type
aucun fichier de sortie généré en raison d'avertissements émis
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall glibc`
```

`brew gist-logs` takes forever to finish, I can try to get the output if you need. 

I can fix the problem by running 
```
$ LC_CTYPE=C brew postinstall glibc 
==> ~/.linuxbrew/Cellar/glibc/2.19/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
==> ~/.linuxbrew/Cellar/glibc/2.19/bin/localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
```

**Comment by sjackman** [comment]
Please report `env |egrep 'LANG|LC'` and also `locale`
Try changing `utf8` to `UTF-8` in whichever environment variable has `utf8` define.

**Comment by Luthaf** [comment]
```
$ env |egrep 'LANG|LC'
LANG=fr_FR.UTF-8
GDM_LANG=fr_FR.utf8
LC_CTYPE=fr_FR.utf8

$ locale
LANG=fr_FR.UTF-8
LC_CTYPE=fr_FR.utf8
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

To reinstall glibc I had to remove hombrew (`cd .linuxbrew && rm -rf* && git reset --hard HEAD`) because I was getting errors about brew ld which could not find `-lc` ...

And then everything works
```
$ LC_CTYPE=fr_FR.UTF-8 GDM_LANG=fr_FR.UTF-8 brew install glibc
==> Installing dependencies for glibc: zlib, binutils, linux-headers
[...]
==> Installing glibc
==> Downloading http://ftpmirror.gnu.org/glibc/glibc-2.19.tar.bz2
Already downloaded: ~/.cache/Homebrew/glibc-2.19.tar.bz2
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=~/.linuxbrew/Cellar/glibc/2.19 --enable-obsolete-rpc --without-selinux --with-binutils=~
==> make
==> make install
==> ~/.linuxbrew/Cellar/glibc/2.19/bin/localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
==> ~/.linuxbrew/Cellar/glibc/2.19/bin/localedef -i en_US -f UTF-8 en_US.UTF-8
~/.linuxbrew/Cellar/glibc/2.19: 1,367 files, 41.6M, built in 5 minutes 14 seconds
```

I'll investigate where does this environment variable come from.

**Comment by sjackman** [comment]
Great! Glad it works.

**Comment by Luthaf** [comment]
Should the glibc formula check for buggy environment variables? Or just having this issue will redirect people with trouble to the fix when the build fails?

**Comment by sjackman** [comment]
This is the first time that it's come up. I'll wait and see if it comes up again.

**Comment by andrewyatz** [comment]
Just encountered this on a new build where `LANG` was set to `en_GB.UTF-8`. However running the postinstall as described (`LC_CTYPE=C brew postinstall glibc`) fixed it. Is it worthwhile/correct to embed this into the formula?

**Comment by sjackman** [comment]
Please report
```sh
echo $LC_CTYPE
env | egrep 'LANG|LC'
locale
```

**Comment by andrewyatz** [comment]
Sure thing.

```[ensw]: echo $LC_CTYPE
[ensw@ebi-006 ~]$ env | egrep 'LANG|LC'
LANG=en_GB.UTF-8
[ensw@ebi-006 ~]$ locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

I was running this via Ansible which did do some explicit setting on the LANG ENV variable to `en_GB.UTF-8` (only saw that once I turned up the debug)

**Comment by sjackman** [comment]
https://www.gnu.org/savannah-checkouts/gnu/libc/manual/html_node/Locale-Categories.html
> LC_CTYPE
This category applies to classification and conversion of characters, and to multibyte and wide characters; see Character Handling, and Character Set Handling.

Do we know anything about why setting `LC_CTYPE` causes `glibc` to fail? Is this a known upstream bug? Can you please report the output of
```sh
LC_CTYPE=en_GB.UTF-8 brew postinstall glibc
```

**Comment by andrewyatz** [comment]
```
LC_CTYPE=en_GB.UTF-8 loom/RHEL7/linuxbrew/bin/brew postinstall glibc
==>
/nfs/software/ensembl/loom/RHEL7/linuxbrew/Cellar/glibc/2.19/bin/localedef
-i en_GB -f UTF-8 en_GB.UTF-8
==>
/nfs/software/ensembl/loom/RHEL7/linuxbrew/Cellar/glibc/2.19/bin/localedef
-i en_US -f UTF-8 en_US.UTF-8
```

Output looks okay. I'm stumped ...

**Comment by sjackman** [comment]
I'm just as stumped as I was before. Perhaps the next person who encounters this issue will know more…

**Comment by ens-ds23** [comment]
Just some more clues, in case this is the missing piece for anyone.

We now have a slightly custom linuxbrew glibc in our install, owing to needing 2.25, but with the formula based on the usual linuxbrew glibc formula. Again, a fresh install recreated this issue, but it was fixed by a manual run of localdef, though only after mkdir-ing /Cellar/glibc/2.25/lib/locale first. Without the mkdir the command line fails with a line indicating an ENOENT. Could a required mkdir of this directory be missing from the formula, but required, maybe? If this is a directory that in a non-prefixed install you'd expect to exist as part of the FSSTD, maybe there's no mkdir in the makefile. I'll carry on investigating tomorrow, and see if I can get more info.

cannot create temporary file: /[...]/Cellar/glibc/2.25/lib/locale/locale-archive.yRe9WM: No such file or directory

(Same machine/system/setup/tree as @andrewyatz , who's my manager!).

**Comment by sjackman** [comment]
If you're able to confirm your suspicion and fix it, a pull request would be most welcome!

**Comment by ens-ds23** [comment]
Sadly, in tidying up various apparently unrelated scary things we were doing to bootstrap linuxbrew on RHEL6 box without an installed system compiler (mainly related to dodgy rpaths), this glibc problem unexpectedly went away and, after about a year of us putting up with it, I can't reproduce it any more. :-( So I can't produce a patch. Sorry.

**Comment by sjackman** [comment]
Well, glad to hear that you got it working, in any case. Feel free to contribute a RHEL6 wiki page like this one for CentOS6: https://github.com/Linuxbrew/brew/wiki/CentOS6
The wiki is publicly editable.
