### ISSUE TITLE
The best approach for dealing with missing dependencies

### ISSUE THREAD

**Issue by DoomHammer** [Linuxbrew/linuxbrew#933]
As I am playing again with Linuxbrew I am running into those dark corners when sometimes a package is missing that in OS X is probably in base system. I have a list of such Formulae but wondered whether this list should go public.

I can test and fix those packages in my own time, of course, but maybe there are others who would grab them and hack around them in the meanwhile.

What approach would you suggest @sjackman ? I think a new issue per Formula is a bit of an overkill.

**Comment by sjackman** [comment]
If you can, open a single issue per formula who's subject is
`curl: Depends on openssl for Linuxbrew`
ideally with a gist, but even without is fine for now.
You can also post your list on this issue.

**Comment by DoomHammer** [comment]
Savvy!

**Comment by DoomHammer** [comment]
BTW: should I assign them to myself (if this is even possible) so that I would know they are my "drafts"?

**Comment by sjackman** [comment]
It's only possible to assign tickets to members. For now just label the issue WIP (work in progress) and leave it unassigned.
