### ISSUE TITLE
Error: No available formula with the name "homebrew/dupes/ncurses" 

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/linuxbrew#938]
Installing a formula that depends on `:python` before `homebrew/dupes` is tapped results in the error message `No available formula with the name "homebrew/dupes/ncurses"`. Note that on Linuxbrew `python` depends on `readline`, which depends on `homebrew/dupes/ncurses`. Installing a formula, which depends on `"python"` rather than `:python` works fine. e.g. `brew install gobject-introspection`. See below for examples.

@xu-cheng I believe this behaviour has changed recently, in the last week or so. Any thoughts on what changed?

### Fails

```
❯❯❯ brew install sphinx-doc
Error: No available formula with the name "homebrew/dupes/ncurses" 
Please tap it and then try again: brew tap homebrew/dupes
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

### Succeeds

```
❯❯❯ brew install gobject-introspection
==> Tapping homebrew/dupes
Cloning into '/home/sjackman/.linuxbrew/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 42, done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 42 (delta 0), reused 5 (delta 0), pack-reused 0
Unpacking objects: 100% (42/42), done.
Checking connectivity... done.
Tapped 38 formulae (103 files, 105.5K)
==> Installing dependencies for gobject-introspection: xz, pkg-config, li
==> Installing gobject-introspection dependency: xz
==> Downloading https://linuxbrew.bintray.com/bottles/xz-5.2.2.x86_64_linux.bott
Already downloaded: /home/sjackman/.cache/Homebrew/xz-5.2.2.x86_64_linux.bottle.tar.gz
==> Pouring xz-5.2.2.x86_64_linux.bottle.tar.gz
…
```

**Comment by xu-cheng** [comment]
Could you submit this issue to Homebrew? This is just one of many bugs in our fragile dependency system.

**Comment by sjackman** [comment]
Fixed by @ilovezfs in https://github.com/Homebrew/legacy-homebrew/issues/50271
