### ISSUE TITLE
glibc: depends on gawk

### ISSUE THREAD

**Issue by DoomHammer** [Linuxbrew/linuxbrew#953]
Building from source because of #952 I got:

```
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-rules --prefix=/home/linuxbrew/.linuxbrew/Cellar/glibc/2.19 --enable-obsolete-rpc --without-selinu
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/glibc/01.configure:
checking for gnumake... no
checking for gmake... no
checking for make... make
checking version of make... 3.81, ok
checking for gnumsgfmt... no
checking for gmsgfmt... no
checking for msgfmt... no
checking for makeinfo... no
checking for sed... sed
checking version of sed... 4.2.2, ok
checking for gawk... no
checking for nm... nm
configure: error: 
*** These critical programs are missing or too old: gawk
*** Check the INSTALL file for required versions.
```

Doing further tests whether simply adding a dependency will solve the issue.

Env: Docker `linuxbrew/linuxbrew` `7c827ee662db`, Homebrew `f0e235a`

**Comment by rwhogg** [comment]
At https://sourceware.org/glibc/wiki/FAQ#Compiling_glibc, there's a list of necessary build dependencies, including `gawk` and `perl`.

Thanks for the bug report @DoomHammer!

**Comment by DoomHammer** [comment]
Fascinating thing is that installing deps one by one seems to work. Only trying to `brew` something that installs a dep first fails.

Separate issue: `glibc` won't build with `gcc-4.3`. Seems the :chicken: is eating its :egg: or something alike... Catch 22?

**Comment by sjackman** [comment]
Yes, even CentOS 5 has `gcc 4.4` available as an optional package, which is able to build `glibc`. I'm not sure how to install `glibc` with a system that has `gcc 4.3`. Install a deb for a newer release of GCC if you can. Perhaps a backport?
It might be possible to do something like
```
brew install gcc --without-glibc
brew install glibc
brew install gcc --with-glibc
```
but it would be tricky.

**Comment by sjackman** [comment]
Currently the `README.md` says that the minimum version off GCC is `4.2`. I'm going to increase that to `4.4`.

**Comment by DoomHammer** [comment]
Pieces don't fit. `gcc-4.4` in Debian pulls in `glibc` 2.11 so back to the drawing board.

**Comment by sjackman** [comment]
Move to https://github.com/Linuxbrew/brew/pull/34 and https://github.com/Linuxbrew/homebrew-core/pull/231
