### ISSUE TITLE
gmp: fails to build with --c++11

### ISSUE THREAD

**Issue by benmwebb** [Linuxbrew/linuxbrew#967]
The `gmp` formula includes a `--c++11` option, but it doesn't work on Linux:

    brew install gmp --c++11
    ==> Downloading https://gmplib.org/download/gmp/gmp-6.1.0.tar.xz
    Already downloaded: /home/ben/.cache/Homebrew/gmp-6.1.0.tar.xz
    Error: The selected compiler doesn't support C++11: gcc

I don't really understand the error since I'm on a Fedora 23 system with gcc 5.3.1, which **does** support C++11 (maybe it's trying to compile C code rather than C++ with `-std=c++11` and is getting confused?) Unfortunately I'm installing a formula which needs both C++11 and gmp, so brew is automatically trying to recompile gmp with `--c++11` for me.

FWIW, I can make things "work" by mangling the `gmp` formula and removing the `option :cxx11`. But I suspect this only works because the other formula doesn't use any C++ code from gmp.

**Comment by sjackman** [comment]
This is an anachronism that we've inherited from Homebrew. `/usr/bin/gcc` is assumed to be GCC 4.2 as it is on old Mac OS distributions, and I haven't fixed this in Linuxbrew. The workaround is to creating a symlink from `/usr/bin/gcc` to `$HOMEBREW_PREFIX/bin/gcc-5`, `g++` and `gfortran` as well. See
https://github.com/Linuxbrew/linuxbrew/wiki/Standalone-Installation#create-symlinks-for-gcc
