### ISSUE TITLE
brew install gd

### ISSUE THREAD

**Issue by jwhite007** [Linuxbrew/linuxbrew#972]
### Something wrong with options print-out in GD.rb?:
```
$ brew info gd
gd: stable 2.1.1, HEAD
Graphics library to dynamically manipulate images
https://libgd.github.io/
/toolbox/NGS/.linuxbrew/Cellar/gd/2.1.1_2 (34 files, 1.1M) *
  Built from source
From: https://github.com/Homebrew/linuxbrew/blob/master/Library/Formula/gd.rb
==> Dependencies
Build: xz ✔
Recommended: fontconfig ✔, freetype ✔, jpeg ✔, libpng ✔, libtiff ✔
Optional: libvpx ✔
==> Options
--universal
        Build a universal binary
--with-libvpx
        Build with libvpx support
--without-fontconfig
        Build without fontconfig support
--without-freetype
        Build without freetype support
--without-jpeg
        Build without jpeg support
--without-libpng
        Build without libpng support
--without-libtiff
        Build without libtiff support
--HEAD
        Install HEAD version
```
#### I had to do:
```
$ brew install gd --with-libvpx --with-fontconfig --with-freetype --with-jpeg --with-libpng --with-libtiff
```

**Comment by jwhite007** [comment]
#### Not working:
```
$ brew install gd --with-libvpx --with-fontconfig --with-freetype --with-jpeg --with-libpng --with-libtiff
```
#### Logs:
https://gist.github.com/jwhite007/a7e9ad6a8c04427daff4

**Comment by sjackman** [comment]
https://gist.github.com/jwhite007/a7e9ad6a8c04427daff4#file-02-make-L138-L141
```
libtool: compile:  /toolbox/NGS/.linuxbrew/bin/gcc-5 -DHAVE_CONFIG_H -I. -isystem/toolbox/NGS/.linuxbrew/include -I/toolbox/NGS/.linuxbrew/Cellar/libpng/1.6.21/include/libpng16 -I/toolbox/NGS/.linuxbrew/Cellar/freetype/2.6.3/include/freetype2 -I/toolbox/NGS/.linuxbrew/opt/fontconfig/include -I/toolbox/NGS/.linuxbrew/opt/libvpx/include -I/toolbox/NGS/.linuxbrew/opt/libtiff/include -Os -w -pipe -march=core2 -I/toolbox/NGS/.linuxbrew/opt/jpeg/include -fvisibility=hidden -c gd_io_dp.c -o gd_io_dp.o >/dev/null 2>&1
webpimg.c: In function 'VPXEncode':
webpimg.c:714:24: error: 'IMG_FMT_I420' undeclared (first use in this function)
     vpx_img_wrap(&img, IMG_FMT_I420,
```

**Comment by sjackman** [comment]
Did you close this issue intentionally? Were you able to find a resolution?

**Comment by jwhite007** [comment]
I did close it intentionally. I'm a bit confused as the "--with" options are default according to the brew-info output; however, I was getting different output when I stated them explicitly. I then looked at the logs of the install in which I did not explicitly state the "--with" options only to see that they are used.

**Comment by sjackman** [comment]
I think the options are a red herring. My best guess is that it's a parallel build error caused by your 64 cores due to a bug in the Makefile. I see these occasionally on my big machines. You could try
```sh
HOMEBREW_MAKE_JOBS=1 brew install gd
```

**Comment by jwhite007** [comment]
On my end...
```
HOMEBREW_MAKE_JOBS=1 brew install gd
```
doesn't seem to make a difference over...
```
brew install gd
```
The reason that I'm fooling around with the install of brewed GD is that I'm getting some errors when I try to install the GD module in brewed Perl. It seems that the install of the module finds /usr/include/gd.h and not the brewed GD's gd.h. I guess this isn't really a linuxbrew, so you can just ignore it, unless you know what's going on.

Thanks, Shaun.

**Comment by jwhite007** [comment]
Yes... totally just a Perl issue. For some reason, installing the YAML module fixed the gd.h issue. Computer voodoo.

**Comment by sjackman** [comment]
Glad to hear that the voodoo worked its magic!

**Comment by jwhite007** [comment]
I spoke too soon. The build is still finding /usr/include/gd.h and not the brewed gd's gd.h... back to the drawing board.

**Comment by sjackman** [comment]
Which command are you running that is giving those warnings?

**Comment by jwhite007** [comment]
```
$ perl -MCPAN -e shell
cpan[1]> install GD
```

**Comment by sjackman** [comment]
Something is adding `-I/usr/include` to your compiler before `-I/toolbox/NGS/.linuxbrew/include`, which is the source of the trouble. I'm not sure how to fix it though. I've had good luck with `cpanm` for installing Perl modules.
```sh
brew install perl cpanm
cpanm GD
```

**Comment by jwhite007** [comment]
```
cpanm GD
```
results in same error, so I decided to...
```
cpanm GD --force
```
Hopefully this doesn't cause any serious problems.

**Comment by sjackman** [comment]
Try
```sh
brew sh <<<"cpanm GD"
```

**Comment by jwhite007** [comment]
```
$ brew sh <<<"cpanm GD"
Your shell has been configured to use Homebrew's build environment:
this should help you build stuff. Notably though, the system versions of
gem and pip will ignore our configuration and insist on using the
environment they were built under (mostly). Sadly, scons will also
ignore our configuration.
When done, type `exit'.
GD is up to date. (2.56)
```
