### ISSUE TITLE
Running update gives: "Error: update-report should not be called directly"

### ISSUE THREAD

**Issue by infokiller** [Linuxbrew/linuxbrew#979]
When running `brew update` I get the following error:
```
Reinitialized existing Git repository in /usr/infokiller/.git/modules/bin/sources/linuxbrew/
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
HEAD is now at c6d7aad ghc: Depends on m4 for Linuxbrew
Error: update-report should not be called directly!
```

I'm using Ubuntu 14.04.

**Comment by sjackman** [comment]
I'm not able to reproduce this error. Do you get the same error message if you run `brew update` again?
I'm confused by this directory name: `/usr/infokiller/.git/modules/bin/sources/linuxbrew/`
Please report the output of `brew config` and `brew doctor`

**Comment by infokiller** [comment]
Thanks a lot for your quick response and looking into this!

Yes, this happens consistently every time I run `brew update`.
Sorry, the directory name in that error message should have actually been `/home/infokiller/.git/modules/bin/sources/linuxbrew/`. 
I think it will be useful to describe my configuration. I have a git repo in my home directory (`/home/infokiller/`) that tracks all my dotfiles. This git repo has multiple git submodules located in `/home/infokiller/bin/sources`. One of them is `linuxbrew` which is located in `/home/infokiller/bin/sources/linuxbrew`. Is that what's causing the issue?

Output of `brew config`:
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Linuxbrew/linuxbrew.git
HEAD: c6d7aad7a118e4242f888bd0d2e526c886f8486c
Last commit: 14 hours ago
HOMEBREW_PREFIX: /home/infokiller
HOMEBREW_REPOSITORY: /home/infokiller/bin/sources/linuxbrew
HOMEBREW_CELLAR: /home/infokiller/bin/sources/linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 12-core 64-bit sandybridge
Kernel: Linux 3.13.0-77-generic x86_64 GNU/Linux
OS: Ubuntu 14.04.1 LTS
Codename: trusty
OS glibc: 2.19
OS gcc: 4.8.4
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Clang: N/A
X11: 2.7.8 => /usr
System Ruby: 1.9.3-p484 => /usr/bin/ruby1.9.1
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby1.9.1
Java: openjdk version "1.8.0"
```

[Output of `brew doctor`](https://gist.github.com/infokiller/83dfe8c311d656dc1ded).

**Comment by sjackman** [comment]
The problem is related to this:
```
HOMEBREW_PREFIX: /home/infokiller
HOMEBREW_REPOSITORY: /home/infokiller/bin/sources/linuxbrew
HOMEBREW_CELLAR: /home/infokiller/bin/sources/linuxbrew/Cellar
```

Is it intentional that your `HOMEBREW_PREFIX` is `/home/infokiller` rather than `/home/infokiller/bin/sources/linuxbrew`?

**Comment by infokiller** [comment]
Nope, it's not intentional. How do I set it correctly?

**Comment by sjackman** [comment]
Here's by my best guess. `/home/infokiller/bin/sources/linuxbrew` does not contain `.git` directory, so `git` is marching up through parent directories looking for a `.git` directory, and it finds one in `/home/infokiller`, but that's not the Linuxbrew `.git` directory, but instead your `dotfiles` `.git` directory, and everything breaks.
Workaround:
```sh
mv ~/.git ~/.git-backup
brew update
mv ~/.git-backup ~/.git
```
Once you've done that once, `brew update` *should* work from then on.

**Comment by sjackman** [comment]
I put my `dotfiles` in `~/.dotfiles/.git` for this reason, and symlink the individual files into `~`.

**Comment by infokiller** [comment]
Thanks, that did the trick!
I agree it's better to put the `dotfiles` outside the root home directory, it's on my task list for some time now :)

**Comment by sjackman** [comment]
Glad to hear it worked!

**Comment by Sailia** [comment]
Hey sjackman, I was wondering whether I have the same issue as infokiller as I got the same error, and if you could please help me out on this one!

brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew
HEAD: a5a930c48bec7bb7bdc6bbf7e0fe7fe5f564a7fe
Last commit: 25 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fd4fe97197d76ff4f256fa57a647cfdcd22bfba2
Core tap last commit: 3 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 7.3 build 703
Git: 2.7.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
Java: 1.8.0_77, 1.6.0_65-b14-468
OS X: 10.11.6-x86_64
Xcode: 7.3.1
CLT: 7.3.1.0.1.1461711523
X11: 2.7.8 => /opt/X11

Thank you!

**Comment by Sailia** [comment]
Never mind, I looked twice at what you said, and managed to fix it. Thanks!

**Comment by sjackman** [comment]
Glad to hear it!

**Comment by evgeniyd** [comment]
Could you please help me with the similar issue?

My error output:

    $ brew update
    /usr/local/Library/brew.sh: line 32: /usr/local/Library/ENV/scm/git: No such file or directory
    /usr/local/Library/brew.sh: line 32: /usr/local/Library/ENV/scm/git: No such file or directory
    /usr/local/Library/brew.sh: line 32: /usr/local/Library/ENV/scm/git: No such file or directory
    /usr/local/Library/brew.sh: line 32: /usr/local/Library/ENV/scm/git: No such file or directory
    /usr/local/Library/brew.sh: line 32: /usr/local/Library/ENV/scm/git: No such file or directory
    /usr/local/Library/brew.sh: line 32: /usr/local/Library/ENV/scm/git: No such file or directory
    /usr/local/Library/brew.sh: line 32: /usr/local/Library/ENV/scm/git: No such file or directory
    /usr/local/Library/brew.sh: line 32: /usr/local/Library/ENV/scm/git: No such file or directory
    /usr/local/Library/brew.sh: line 32: /usr/local/Library/ENV/scm/git: No such file or directory
    Error: update-report should not be called directly!

..and config:

    $ brew config
    HOMEBREW_VERSION: 0.9.9
    ORIGIN: https://github.com/Homebrew/brew.git
    HEAD: 38209aadbfe4fd0c6772467c4bc5c63325d53f6c
    Last commit: 25 hours ago
    Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
    Core tap HEAD: c195f62500a3e41f9fd4fe48e537e2d41dc359e6
    Core tap last commit: 5 weeks ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: quad-core 64-bit haswell
    Homebrew Ruby: 2.0.0-p648
    Clang: 7.3 build 703
    Git: 2.7.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    Java: 1.8.0_92
    OS X: 10.12-x86_64
    Xcode: 7.3.1
    CLT: N/A
    X11: N/A

**Comment by maxim-belkin** [comment]
Evgeniy, three issues:
- this is Linuxbrew land
- this is **old** Linuxbrew land
- you've got Homebrew

**Comment by sjackman** [comment]
`brew update` (again) should resolve your issue.

**Comment by evgeniyd** [comment]
it did! thank you!

**Comment by astro313** [comment]
Hi,

I am experiencing the same issue, could you please let me know how to solve this. Thanks!

> brew update
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
/usr/local/Library/Homebrew/cmd/update.sh: line 13: /usr/local/Library/ENV/scm/git: No such file or directory
Error: update-report should not be called directly!
> 

> 
brew config
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 295e937f270826aef4e64f0056950a948e3502b1
Last commit: 16 minutes ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 0485e5a69b7c771970262d9aa601b255d84ab563
Core tap last commit: 5 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648 => /usr/local/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: 5.1 build 503
Git: 1.8.5.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/admin/anaconda/bin/python => /Users/admin/anaconda/bin/python2.7
Ruby: /usr/local/bin/ruby => /usr/local/Cellar/ruby/2.3.0/bin/ruby
Java: 1.6.0_65-b14-466.1
OS X: 10.8.5-x86_64
Xcode: 5.1.1
CLT: 5.1.0.0.1.1396320587
X11: 2.7.8 => /opt/X11
>

**Comment by sjackman** [comment]
Hi, Daisy. You're using Homebrew on Mac. This repo is for Linuxbrew on Linux. Try `brew update` again. If that doesn't work, open an issue at https://github.com/Homebrew/brew
