### ISSUE TITLE
Missing libdbus libraries

### ISSUE THREAD

**Issue by OmeGak** [Linuxbrew/linuxbrew#980]
This is more of a question than an issue. It might be that I didn't quite get linuxbrew standalone installation philosophy, but otherwise I'd like to know if there's a better way to deal with this. I'll explain.

---

Recently I was trying to use `dbus-python` package and I wanted to install it through `pip` since doing so with `apt-get` would result on it being installed for system Python instead of linuxbrew's. For that I first needed to have `libdbus-1` and `libdbus-glib-1` libraries and these are not available on `brew`, so I had to install them from `apt-get`. This is where the fun begins.

They obviously end up in system directories, not visible to linuxbrew's `pkg-config`, so my first attempt looked like this:

```bash
export PKG_CONFIG_PATH=$(/usr/bin/pkg-config --variable pc_path pkg-config)
pip install dbus-python
```

This manages to successfully install the package, but upon `import dbus` I got an exception about unresolved symbols in `/home/omegak/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/_dbus_bindings.so`. After much pain I found that `libdbus-1.so.3` was not linked, so I had to go for this:

```bash
export PKG_CONFIG_PATH=$(/usr/bin/pkg-config --variable pc_path pkg-config)
export LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/
pip install dbus-python
```

Now `libdbus-1.so.3` was correctly linked. However, if I don't keep `/lib/x86_64-linux-gnu/` in `LD_LIBRARY_PATH` I will still get this:

```python
>>> import dbus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/omegak/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/dbus/__init__.py", line 77, in <module>
    import dbus.types as types
  File "/home/omegak/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/dbus/types.py", line 6, in <module>
    from _dbus_bindings import (
ImportError: libdbus-1.so.3: cannot open shared object file: No such file or directory
```

And the reason is that even though `libdbus-1.so.3` was found and linked as a dependency at compile time can't be found anymore:

```bash
ldd /home/omegak/.linuxbrew/Cellar/python/2.7.11/lib/python2.7/site-packages/_dbus_bindings.so
        linux-vdso.so.1 (0x00007ffead78a000)
        libdbus-1.so.3 => not found
        libc.so.6 => /home/omegak/.linuxbrew/lib/libc.so.6 (0x00007fa369395000)
        /home/omegak/.linuxbrew/Cellar/glibc/2.19/lib64/ld-linux-x86-64.so.2 (0x0000563321796000)
```

---

If I understood correctly, I'd say that adding `/lib/x86_64-linux-gnu/` in `LD_LIBRARY_PATH` breaks the philosophy of the standalone installation, ant thus my questions:

* Is it possible to add these libraries to linuxbrew so that this hacks can be avoided?
* Is there a cleaner way to make the libraries visible in linuxbrew-standalone realm?

**Comment by sjackman** [comment]
> Is it possible to add these libraries to linuxbrew so that this hacks can be avoided?

They're already in there. `brew install dbus`

> Is there a cleaner way to make the libraries visible in linuxbrew-standalone realm?

You can create a "host keg", also called a "fake keg" in previous discussions.
```sh
mkdir -p `brew --cellar`/dbus/host/lib/
ln -s /lib/x86_64-linux-gnu/libdbus* `brew --cellar`/dbus/host/lib/
brew link dbus
```

**Comment by OmeGak** [comment]
The problem with installing `dbus-glib` is that it depends on `d-bus`, which looked to me like an OSX only package as #987 is reporting. The host keg worked like a charm.

**Comment by sjackman** [comment]
Glad to hear the workarond worked. It should be pretty easy to fix this issue by disabling `launchd` support in `d-bus`:
```diff
-                          "--enable-launchd",
+                          ("--enable-launchd" if OS.mac?),
```
I believe @rwhogg is looking into it in #987.

**Comment by rwhogg** [comment]
FYI, #987 is now closed and `dbus` should now work.

**Comment by sjackman** [comment]
Thanks, Bob.

**Comment by OmeGak** [comment]
Thank you guys. This makes it much cleaner to install.
