### ISSUE TITLE
repeatscout: Error: Directory not empty

### ISSUE THREAD

**Issue by nextgenusfs** [Linuxbrew/linuxbrew#982]
```
$ brew install repeatscout
==> Reinstalling homebrew/science/repeatscout
==> Downloading http://repeatscout.bioprojects.org/RepeatScout-1.0.5.tar.gz
Already downloaded: /home/ngs/.cache/Homebrew/repeatscout-1.0.5.tar.gz
==> make
Error: Directory not empty - /home/ngs/.linuxbrew/Cellar/repeatscout/1.0.5
```

The error seems to be in this line of the install `prefix.rmdir`.  If you change this to `rm_r prefix` it installs correctly on linux.  Not sure why the `prefix.rmdir` removes all files from directory on mac but not on linux.

**Comment by sjackman** [comment]
There's a hack on Linux for a bug in `ld.so` of `glibc 2.19` that creates an empty directory `$prefix/lib`, so `$prefix` is not empty on Linux. That's causing a few occasional build errors like this, so I think we may have to find a different solution to that bug.

**Comment by sjackman** [comment]
Fixed!
