### ISSUE TITLE
postgresql: Depends on xslt

### ISSUE THREAD

**Issue by sjackman** [Linuxbrew/linuxbrew#999]
https://travis-ci.org/Linuxbrew/linuxbrew/builds/119350327#L2610-L2611
```
checking for xsltCleanupGlobals in -lxslt... no
configure: error: library 'xslt' is required for XSLT support
```

**Comment by rwhogg** [comment]
Looks like it depends on `libuuid` too.

```
checking for uuid_generate in -luuid... no
configure: error: library 'uuid' is required for E2FS UUID
```

**Comment by rwhogg** [comment]
I just got it to build successfully, so I'm assigning this to me.

**Comment by sjackman** [comment]
`libuuid` is provided by three packages, which drives me crazy: `libuuid`, `ossp-uid` and `util-linux`.
On Linuxbrew the canonical provider of `libuuid` is `util-linux`, which I believe is actually contains a fork of `libuuid`. I'm thinking that this may need to be abstracted away to a Requirement `:libuuid`.

**Comment by rwhogg** [comment]
> I'm thinking that this may need to be abstracted away to a Requirement `:libuuid`.

Sounds like a plan to me :smile:

I'll put #1019 on hold for now.

**Comment by sjackman** [comment]
In the meantime feel free to use
```ruby
depends_on "util-linux" if OS.linux? # for libuuid
```
That's what I've done in other cases.
Or if you like, take a stab at creating `LibuuidRequirement`.
See https://github.com/Linuxbrew/linuxbrew/blob/master/Library/Homebrew/requirements.rb
